const HINTS_TR = {
  "fruits": {
    "A": {
      "Armut": "Sonbahat hasadı yapılan, yeşil veya kahverengi renkli, tatlı meyve.",
      "Ananas": "Taç yapraklı, sarı renkli, tropikal bölgelerde yetişen ekzotik meyve.",
      "Avokado": "Yeşil kremsi dokusu, guacamole yapımında kullanılan besleyici meyve.",
      "Acai": "Brezilya'dan gelen, antoksidanlar açısından çok zengin koyu mor meyve.",
      "Adi Kivi": "Kahverengi tüylü dış, yeşil et ve siyah tohumlarla dolu.",
      "Asya Armudı": "Fıçı şeklinde, taşsız çekirdeği olan Çin'den gelen armut türü.",
      "Atemoya": "Şeker elması ile atemoya melez, kremsi ve tatlı meyve.",
      "Acerola": "Vitamin C açısından çok zengin, kırmızı renkli Karayip meyvesi.",
      "Ambarella": "Hindistan'dan gelen, sarı renkli, asidik tadı olan tropikal meyve.",
      "Araza": "Amazonya bölgesinde yetişen, kırmızı renkli besleyici meyve."
    },
    "B": {
      "Muz": "Sarı renkli, potasyum açısından zengin, şilte halinde satılan meyve.",
      "Yaban Mersini": "Orman içinde yetişen, mavi-siyah renkli, besleyici tatlı meyve.",
      "Böğürtlen": "Dikenli çalılarda yetişen, siyah renkli, tart tadı olan meyve.",
      "Boysenberry Türü": "Frambuaz ve böğürtlen melez, koyu kırmızı renkli.",
      "Ekmek Meyvesi": "Ağır ve büyük, Pasifik adalarında hasat edilen nişastacı meyve.",
      "Kanlı Portakal": "Kırmızı etli, mor renkli kabuğu olan özel portakal türü.",
      "Bael": "Hindistan meyvesi, sarı kabuk, kremsi beyaz et, tıbbi özellikleri var.",
      "Bilberry Türü": "Kuzey Avrupa'da yaygın, mavi-siyah renkli yaban mersini.",
      "Acı Portakal": "Seville portakalı, çok ekşi tadı, marmelat yapımında kullanılan.",
      "Barbadine": "Passiflora ailesinden, büyük sarı renkli sulu meyve."
    },
    "C": {
      "Kiraz": "Kırmızı renkli, ince çekirdeği, yaz meyvesi, antik meyve.",
      "Hindistan Cevizi": "Kahverengi kabuğu, içinde beyaz et ve su, tropikal meyve.",
      "Turna Yemişi": "Turuncu renkli, hafif asidik tat, meyvesi küçük ve nadir.",
      "Karavun": "Kırmızı-turuncu renkli, tatlı-asidik tadı olan tropikal meyve.",
      "Klementini": "Tatlı, portakal ailesinden, kabuksuz kolay soyulan meyve.",
      "Frenk Üzümü": "Kırmızı veya beyaz renkli, asidik tatlı tat, besleyici.",
      "Cherimoya": "Kremsi dokulu, tadı vanilya benzeri, Andean meyvesi.",
      "Calamondin": "Küçük, turuncu, ekşi tadı olan Filipin meyvesi.",
      "Bulut Böğürtleni": "Nadir, zor bulunan, açık renk böğürtlen türü.",
      "Capulin": "Siyah-kırmızı renkli, tatlı tat, Meksika'dan gelen kiraz."
    },
    "D": {
      "Ejder Meyvesi": "Pembe-kırmızı dış, siyah tohumlı, tropikal meyve.",
      "Durian": "Dış dönerli, güçlü kokulu, sarı et, kral meyvesi.",
      "Hurma": "Kahverengi-kırmızı, tatlı, çekirdeği yapısal olan meyve.",
      "Damson Ericek": "Koyu mor-siyah, tart tadı, konserve için ideal.",
      "Dew Berry Türü": "Mor-siyah renkli, tatlı-asidik, böğürtlen benzeri.",
      "Çöl Limonu": "Sarı-turuncu, sulu, çöl bölgelerine uyumlu meyve.",
      "Duku": "Kahverengi-tan renkli, tatlı, Güneydoğu Asya meyvesi."
    },
    "E": {
      "Mürver Meyvesi": "Mor-siyah, böğürtlene benzeri, mersin ağacının meyvesi.",
      "Emblica": "Yeşil-sarı, asidik, vitamin C açısından çok zengin.",
      "Etrog": "Limon benzeri, kalın kabuk, dini törenler için kullanılan.",
      "Entawak": "Sarı renkli, tatlı, Borneo'dan gelen tropikal meyve."
    },
    "F": {
      "İncir": "Koyu kırmızı-mor, tatlı, tarih boyunca yetiştirilen meyve.",
      "Feijoa": "Yeşil-turuncu, tropik tadı, egzotik meyve.",
      "Parmak Limonu": "Ince turuncu şerit, limon kokulu, alışılmadık meyve.",
      "Fuyu Persimonu": "Turuncu-kırmızı, tatlı, tannin ağı az hiyar.",
      "Yalancı Mastik": "Pembe renkli, tatlı, Filipin meyvesi."
    },
    "G": {
      "Üzüm": "Yeşil veya mor-kırmızı, tatlı, besin açısından zengin.",
      "Guava": "Yeşil-sarı, pembe-kırmızı iç, tropikal meyve.",
      "Greyfurt": "Büyük portakal benzeri, ekşi-tatlı, turuncu-pembe.",
      "Muşmula": "Turuncu renkli, tatlı, sonbahat meyvesi.",
      "Greengage Ericek": "Yeşil renkli, tatlı, eriş türü.",
      "Grumichama": "Koyu kırmızı-siyah, tatlı, Brezilyalı meyvesi.",
      "Gamboge": "Sarı renkli, asidik, Güneydoğu Asya meyvesi.",
      "Gac Meyvesi": "Turuncu-kırmızı, Vietnam'dan, karotenler açısından zengin."
    },
    "H": {
      "Sarı Kavun": "Turuncu renkli, tatlı, ağlı doku, yaz meyvesi.",
      "Huckleberry Türü": "Koyu mor-siyah, tatlı-asidik, Amerika'dan.",
      "Hackberry Meyvesi": "Kahverengi-kırmızı, küçük, ağaçtan gelen meyve.",
      "Boynuzlu Kavun": "Uzun şekli, yeşil-sarı, ortadoğu meyvesi."
    },
    "I": {
      "Ilama": "Yeşil-sarı, tatlı, Andean tropikal meyve.",
      "Hint Ericek": "Pembe renkli, tatlı, Hindistan meyvesi.",
      "Imbe": "Turuncu-kırmızı, asidik-tatlı, Afrika meyvesi.",
      "Buz Elması": "Beyaz-pembe, tatlı-asidik, çıt çıtlı doku.",
      "Inga Meyvesi": "Uzun fasulye şekli, beyaz pulp, tatlı, tropik."
    },
    "J": {
      "Jack Meyvesi": "Sarı renkli, büyük, jackfruit benzeri, tropikal.",
      "Jujube": "Kırmızı-koyu kahverengi, tatlı, tarihsel meyve.",
      "Jaboticaba": "Mor-siyah, tatlı, Brezilyalı ağaç meyvesi.",
      "Java Ericek": "Pembe-kırmızı, tatlı-asidik, eriş türü.",
      "Jocote": "Sarı-turuncu-kırmızı, asidik-tatlı, Orta Amerika.",
      "Jobo": "Sarı renkli, asidik, Arjantin'de popüler."
    },
    "K": {
      "Kivi": "Yeşil veya sarı-turuncu iç, kara tohumlar, sulu-asidik.",
      "Kumkuat": "Mini turuncu, kabuğu tatlı, turunçgille.",
      "Kiwano": "Hain tepeli, yeşil iç, jöle doku, egzotik.",
      "Kaki": "Turuncu renkli, tatlı, sonbahat meyvesi.",
      "Kaffir Limonu": "Tatlı kabuk, ekşi iç, Tayland'dan.",
      "Kei Elması": "Turuncu, tatlı-asidik, Afrika'dan."
    },
    "L": {
      "Limon": "Sarı renkli, asidik, limonata yapımında kullanılan.",
      "Yeşil Limon": "Yeşil renkli, dönem serbest, asidik, tropikal.",
      "Lychee": "Kırmızı-koyu kahverengi, beyaz iç, tatlı-asidik.",
      "Longan": "Kahverengi-tan, beyaz iç, lychee benzeri, tropikal.",
      "Loganberry Türü": "Kırmızı-mor, böğürtlen-ahududu melez.",
      "Langsat": "Sarı renkli, asidik, Güneydoğu Asya meyvesi.",
      "Lucuma": "Kahverengi, tatlı, vanilya tadında, Peruvian.",
      "Limequat": "Küçük turuncu, limon-kumkuat melez, kabuğu."
    },
    "M": {
      "Mango": "Turuncu-kırmızı-yeşil, tatlı, tropikal meyve, krallık.",
      "Kavun": "Tatlı, turuncu iç, ağlı doku, yaz meyvesi.",
      "Dut": "Pembe-kırmızı-koyu, tatlı, ağaçtan gelen meyve.",
      "Mandalina": "Turuncu, kolay soyulan, tatlı, portakal benzeri.",
      "Maracuja": "Turuncu-sarı, asidik pulp, passion fruit türü.",
      "Mamey": "Turuncu renkli, tatlı, Karayip meyvesi.",
      "Marula": "Turuncu-sarı, tatlı-asidik, Afrika'dan.",
      "Mucize Meyvesi": "Turuncu, tatlı, tropik, Batı Afrika."
    },
    "N": {
      "Şeftali": "Turuncu-pembe, tatlı-asidik, yumuşak doku, yaz.",
      "Noni": "Sarı-yeşil, bitter tat, tıbbi özellikli tropikal.",
      "Naranjilla": "Turuncu-kırmızı, asidik, Andean tropikal.",
      "Natal Ericek": "Pembe-kırmızı, tatlı, Güney Afrika eriş.",
      "Nance": "Sarı-turuncu, asidik-tatlı, Orta Amerika."
    },
    "O": {
      "Portakal": "Turuncu renkli, tatlı-asidik, vitamin C zengin.",
      "Zeytin": "Yeşil veya siyah, yağlı pulp, salamura yapılan.",
      "Ortanique": "Turuncu, tatlı, portakal-tangerine melez.",
      "Osage Portakalı": "Turuncu, benzeri portakal, Amerika'dan.",
      "Orangelo": "Turuncu, portakal-pomelo melez, tatlı-asidik."
    },
    "P": {
      "Şeftali": "Turuncu-pembe, tatlı-asidik, yumuşak doku, yaz.",
      "Armut": "Yeşil veya turuncu-kırmızı, tatlı, sonbahat.",
      "Ananas": "Sarı renkli, taç yapraklı, tropikal meyve.",
      "Eriş": "Tatlı, turuncu-pembe, taş çekirdeği, yaz.",
      "Nar": "Kırmızı renkli, garnet benzeri, asidik-tatlı.",
      "Papaya": "Turuncu-sarı, tatlı, ilginç dokusu, tropikal.",
      "Tutku Meyvesi": "Turuncu veya mor, asidik pulp, passion fruit.",
      "Persimonu": "Turuncu-kırmızı, tatlı, sonbahat meyvesi.",
      "Pawpaw": "Sarı-yeşil, kremsi tatlı, Amerika'dan tropikal.",
      "Pitaya": "Pembe-kırmızı veya sarı, siyah tohumlar, ejder."
    },
    "Q": {
      "Ayva": "Sarı renkli, astringent, marmelat yapımında ideal.",
      "Quenepa": "Sarı-tan renkli, tatlı-asidik, Karayip meyvesi.",
      "Queensland Ericek": "Pembe-kırmızı, tatlı, Avustralya eriş.",
      "Quandong": "Kırmızı-turuncu, asidik, Avustralya ağacı."
    },
    "R": {
      "Ahududu": "Kırmızı-sarı-siyah, tatlı-asidik, kırılgan.",
      "Rambutan": "Kırmızı-turuncu, kıllı dış, beyaz iç, tropikal.",
      "Kırmızı Frenk Üzümü": "Kırmızı renkli, asidik, küçük tane.",
      "Gül Elması": "Kırmızı renkli, tatlı, eski zamanlardan.",
      "Rollinia": "Turuncu-sarı, tatlı, custard apple benzeri.",
      "Riberry": "Kırmızı renkli, asidik, Avustralya ağacı."
    },
    "S": {
      "Çilek": "Kırmızı renkli, tatlı, kolay bozulan, beğenilen.",
      "Yıldız Meyvesi": "Sarı-turuncu, yıldız şekli, asidik-tatlı.",
      "Sapodilla": "Kahverengi, tatlı, kremsi doku, Orta Amerika.",
      "Asitli Elma": "Turuncu-kırmızı, asidik, Orta Amerika meyvesi.",
      "Şeker Elması": "Yeşil-sarı, kremsi-tatlı, tatlı tat.",
      "Salak": "Turuncu-kahverengi, tatlı-asidik, ölüm meyvesi.",
      "Santol": "Turuncu-sarı, tatlı, Güneydoğu Asya."
    },
    "T": {
      "Tanerin": "Turuncu renkli, tatlı, portakal benzeri meyve.",
      "Tamarind": "Kahverengi, asidik pulp, tropikal meyve.",
      "Domates": "Kırmızı-yeşil, asidik-tatlı, sebze gibi meyve.",
      "Tamarillo": "Turuncu-kırmızı, asidik pulp, andean meyvesi.",
      "Tangelo": "Turuncu, tangerine-pomelo melez, tatlı.",
      "Tayberry Türü": "Kırmızı-mor, böğürtlen benzeri, tatlı-asidik."
    },
    "U": {
      "Ugli Meyvesi": "Turuncu, başarısız görünüm, tatlı-asidik.",
      "Ugni": "Kırmızı, tatlı-asidik, Güney Amerika meyvesi.",
      "Ayı Üzümü": "Kırmızı-turuncu, tatlı, yaban meyvesi."
    },
    "V": {
      "Valensiya Portakalı": "Turuncu, tatlı, portakal çeşidi.",
      "Voavanga": "Turuncu-kırmızı, tatlı, Afrika ağacı.",
      "Vanilya Fasulyesi": "Uzun şekli, aromalı, vanilya aroma."
    },
    "W": {
      "Karpuz": "Yeşil dış, kırmızı iç, tatlı, yaz meyvesi.",
      "Kurt Böğürtleni": "Siyah-kırmızı, tatlı, yaban meyvesi.",
      "Wampee": "Turuncu renkli, asidik-tatlı, Çin meyvesi.",
      "Beyaz Frenk Üzümü": "Beyaz-yeşil renkli, tatlı üzüm.",
      "Vahşi Çilek": "Kırmızı, küçük, tatlı, yaban meyvesi."
    },
    "X": {
      "Xigua Kavunu": "Karpuz türü, yeşil dış, kırmızı-sarı iç.",
      "Ximenia": "Turuncu, asidik-tatlı, Afrika meyvesi.",
      "Xoconostle": "Kırmızı-turuncu, asidik, cacti meyvesi."
    },
    "Y": {
      "Yuzu": "Sarı-turuncu, asidik, Japon limonu benzeri.",
      "Sarı Tutku Meyvesi": "Sarı renkli, asidik, passion fruit türü.",
      "Yangmei": "Kırmızı-koyu, tatlı-asidik, Çin meyvesi.",
      "Sarı Eriş": "Sarı renkli, tatlı, eriş çeşidi.",
      "Yumberry": "Kırmızı-koyu, tatlı-asidik, Güneydoğu Asya."
    },
    "Z": {
      "Ziziphus": "Kırmızı-koyu, tatlı, jujube benzeri meyve.",
      "Zhe": "Turuncu-sarı, tatlı, Çin meyvesi."
    }
  },

  "animals": {
    "A": {
      "Timsah": "Suda yaşayan, güçlü çenesi, antik sürüngenci hayvan.",
      "Antilop": "Boynuzlu, çevik, Afrika savanında yaşayan ceylan.",
      "Armadillo": "Zırh benzeri kabuğu, Güney Amerika'dan toplamacı.",
      "Karınca Ayısı": "Uzun dili, ağaçta yaşayan, karınca yiyen.",
      "Alpaka": "Tüylü, Andean yüksek ırakta yaşayan evcil.",
      "Anakonda": "Dev yılan, suda yaşayan, güçlü yıkıcı.",
      "Aksolotl": "Suda yaşayan, ayakları olan, amfibi salamander.",
      "Aye-aye": "Gece hayvancı, tuhaf parmakları, lemur türü.",
      "Afrika Yaban Köpeği": "Sosyal avlama, rengarenk kabuğu, kurtça."
    },
    "B": {
      "Ayı": "Kahverengi, güçlü, kış uykusu yapan, memeli.",
      "Manda": "Suda yaşayan, iri boynuzlu, tropikal hayvan.",
      "Babun": "Primat, kırmızı yüzlü, sosyal gruplara yaşayan.",
      "Bizon": "Büyük boynuzlu, sürüler halinde yaşayan, Amerika.",
      "Yarasa": "Kanatlandırılmış, gece aktivitesi yapan, böcek yiyen.",
      "Kunduz": "Su hayvancı, kalın kuyruğu, ağaç söken.",
      "Binturong": "Tüylü, ağaç yaşayan, musky koku, Asya.",
      "Yaban Domuzu": "Sert kılları, keskin dişleri, ormanda yaşayan.",
      "Bongo": "Çizgili antilop, ormanda yaşayan, Afrika.",
      "Mavi Balina": "Dünya'nın en büyük hayvanı, okyanus, mavi."
    },
    "C": {
      "Çita": "Dünyanın en hızlı hayvanı, siyah lekeli, Afrika.",
      "Timsah": "Çenekli, suda yaşayan, mesozoik kalıntısı.",
      "Deve": "Deve höpkesi, çöl yaşayan, çöl gemisi diye.",
      "Kobra": "Zehirli yılan, boynu genişletebilir, Asya.",
      "Şempanze": "Akıllı primat, insan benzeri, Afrika ormanında.",
      "Çakal": "Yırtıcı, gece hayvancı, sürüler halinde.",
      "Karakulak": "Kırmızı çakal, koyu kulakları, Afrika-Asya.",
      "Kapibara": "Dev kemirgen, su yaşayan, sosyal hayvan.",
      "Çinçilla": "Tüylü, küçük, Andean hordu hayvanı."
    },
    "D": {
      "Geyik": "Boynuzlu, hızlı, ormanda yaşayan memeli.",
      "Yunus": "Zeki, okyanus yaşayan, sosyal memeli.",
      "Dingo": "Yaban köpeği, Avustralya'nın, predatör.",
      "Eşek": "Burası daha düşük sesli, stubborn, çiftlik.",
      "Dhole": "Afrika yaban köpeği, sosyal avlama, kurtça.",
      "Dugong": "Deniz memeli, otçul, kız balığına benzer.",
      "Dik-dik": "Küçük antilop, Afrika'nın, boynuzlu mini."
    },
    "E": {
      "Fil": "Büyük hayvan, uzun hortumu, sosyal memeli.",
      "Elk": "Geyik türü, büyük boynuzlu, kuzey ormanda.",
      "Emu": "Kanatlamayan kuş, Avustralya'nın, hızlı koşu.",
      "Ekidne": "Dil ile hayvan, dişi yumurta, Avustralya.",
      "Kakım": "Zehirli memeli, yumurta bıraktığı, Avustralya."
    },
    "F": {
      "Tilki": "Kırmızı, akıllı, gece hayvancı, kurtça.",
      "Kurbağa": "Su yaşayan, sekmeli, değişken renk, amfibi.",
      "Turna": "Uzun bacaklı kuş, suda yaşayan, göçmen.",
      "Flamingo": "Pembe renk, suda yaşayan, sosyal kuş.",
      "Şahin": "Gümrük kuşu, hızlı avcı, gökyüzü hakimi.",
      "Uçan Sincap": "Kanat benzeri deri, ağaçtan atlayabilen.",
      "Balık Kedisi": "Suya gelmek seven, tırmanan, su avlayan."
    },
    "G": {
      "Goril": "Güçlü primat, ormanda yaşayan, insanca.",
      "Zürafa": "Dünyanın en uzun hayvanı, Afrika.",
      "Kertenkele": "Sürüngenci, dış renk değiştirebilir, ağaçta.",
      "Ceylan": "Hafif antilop, çevik, Afrika savanında.",
      "Keçi": "Boynuzlu, tırmanan, çiftlik hayvanı.",
      "Gemsbok": "Uzun boynuzlu antilop, çöl yaşayan.",
      "Dev Karınca Yılanı": "Devasa, zehirli, Afrika hayvanı.",
      "Gri Kurt": "Sosyal, sürü yaşayan, gece hayvancı."
    },
    "H": {
      "Su Aygırı": "Büyük, suda yaşayan, başlı çoğaldığı.",
      "At": "Hızlı, evcil, saç kuyruklu memeli.",
      "Hiena": "Güçlü çene, gece hayvancı, Afrika.",
      "Hamster": "Küçük kemirgen, yanağında asma, evcil.",
      "Kirpi": "Dikenli, topak şeklinde, gece hayvancı.",
      "Hartebeest": "Antilop türü, boynuzlu, Afrika hayvan.",
      "Tavşan": "Uzun kulaklı, hızlı, tarla hayvanı."
    },
    "I": {
      "Iguana": "Sürüngenci, ağaçta yaşayan, ölçülü, tropikal.",
      "İmpala": "Hafif antilop, çevik sekmesi, Afrika.",
      "Ibis": "Uzun gagalı kuş, su kuşu, beynelmilel.",
      "Indri": "Lemur türü, siyah-beyaz, gürültülü primat."
    },
    "J": {
      "Jaguar": "Benekli büyük kedi, güçlü çene, Amerika.",
      "Denizanası": "Stinging tentacles, deniz yaşayan, basit.",
      "Çakal": "Yırtıcı, gece hayvancı, sürüler yaşayan.",
      "Japon Makakalı": "Kıllı primat, sıcak su seyen, sosyal."
    },
    "K": {
      "Kanguru": "Sıçrayan, gözlemleme torba, Avustralya.",
      "Koala": "Yumuşak, ağaç yaşayan, Avustralya.",
      "Komodo Ejderi": "Dev kertenkele, zehirli, Endonezya.",
      "Kinkajou": "Meyveci, ağaçta yaşayan, tropikal.",
      "Kudu": "Uzun boynuzlu antilop, Afrika, çizgili."
    },
    "L": {
      "Aslan": "Yeleli erkek, sosyal, Afrika büyük.",
      "Leopar": "Benekli, ağaçta yaşayan, Afrika kurttan.",
      "Lama": "Tüylü, Andean yüksek, evcil hayvan.",
      "Vaşak": "Benekli kedi, ağaçta yaşayan, Amerika.",
      "Lemur": "Uzun kuyruklu primat, Madagaskar, gece.",
      "Liger": "Aslan-kaplan melez, en büyük kedi.",
      "Loris": "Yavaş primat, gece hayvancı, Asya."
    },
    "M": {
      "Maymun": "Primat, ağaçta yaşayan, sosyal hayvan.",
      "Geyik": "Boynuzlu, hızlı, ormanda yaşayan.",
      "Surikat": "Sosyal, çöl yaşayan, dik-bacak durma.",
      "Fare": "Küçük kemirgen, çabuk çoğalan, gece.",
      "Mangust": "Yılan yiyen, hızlı, Afrika-Asya.",
      "Manatee": "Büyük deniz memeli, otçul, tembel.",
      "Marten": "Ağaçta yaşayan, esnek vücut, gece.",
      "Markhor": "Uzun boynuzlu, dağ keçisi, Asya."
    },
    "N": {
      "Narval": "Sarı dişi, Kuzey deniz memelisi, arktik.",
      "Newt": "Su salamanderi, amfibi, rengarenk.",
      "Numbat": "Termit yiyen, Avustralya'nın, benekli.",
      "Nil Monitörü": "Dev kertenkele, suda yaşayan, Afrika."
    },
    "O": {
      "Orangutan": "Ağaçta yaşayan primat, kırmızı, entelektüel.",
      "Deve Kuşu": "Kanatlamayan kuş, hızlı koşucu, Afrika.",
      "Su Samuru": "Tüylü, suda yaşayan, sosyal memeli.",
      "Ahtapot": "Sekiz kolu, zekalı, deniz hayvanı.",
      "Baykuş": "Gece kuşu, büyük gözler, sessiz uçuşan.",
      "Ocelot": "Benekli kedi, ağaçta yaşayan, Amerika.",
      "Oryx": "Beyaz antilop, çöl yaşayan, uzun."
    },
    "P": {
      "Panda": "Siyah-beyaz, bambu yiyen, Çin hayvanı.",
      "Penguen": "Kanatlamayan kuş, suda yaşayan, kutup.",
      "Puma": "Hızlı kedi, ağaçta yaşayan, Amerika.",
      "Pantera": "Benekli, güçlü predatör, Afrika-Asya.",
      "Platypus": "Gözlemek, yumurta bıraktığı, Avustralya.",
      "Kirpi": "Dikenli, topak şekilde, gece hayvancı.",
      "Proboscis Makakalı": "Uzun burunlu, sosyal, Borneo hayvan.",
      "Pangolin": "Pul kaplı, karınca yiyen, dış."
    },
    "Q": {
      "Quokka": "Gülümseyen kesintisi, Avustralya'nın, küçük.",
      "Quoll": "Benekli katten marsupial, Avustralya.",
      "Kuetzal Kuşu": "Yeşil, uzun kuyruğu, Meksika kuşu.",
      "Quahog": "Deniz kabuğu, yerleşim kuşu, yenilebilir."
    },
    "R": {
      "Tavşan": "Uzun kulaklı, hızlı, tarla hayvanı.",
      "Gergedan": "Boynuz ırzlı, büyük, Afrika-Asya.",
      "Rakun": "Maskeli yüzlü, çöpçü, gece hayvancı.",
      "Çıngıraklı Yılan": "Zehirli, çıngıra sesi, Amerika hayvanı.",
      "Kırmızı Panda": "Kırmızı-siyah, ağaçta yaşayan, vegan.",
      "Çift Kuyruklu Lemur": "İki kuyruk, Madagaskar, primat."
    },
    "S": {
      "Yılan": "Kasnaksız, sürüngenci, zehirli türler var.",
      "Köpekbalığı": "Avcı balık, keskin dişler, deniz.",
      "Tembel": "Yavaş, ağaç yaşayan, tropikal memeli.",
      "Fok Balığı": "Suda yaşayan memeli, yüzgeçler, arktik.",
      "Sincap": "Tüylü kuyruklu, ağaç yaşayan, ceviz.",
      "Kar Leoparı": "Benekli, dağ yaşayan, nadir predatör.",
      "Serval": "Benekli kedi, uzun bacaklar, Afrika.",
      "Semender": "Salamander, suda yaşayan, amfibi."
    },
    "T": {
      "Kaplan": "Şeritleri, güçlü, büyük kedi predatörü.",
      "Kaplumbağa": "Kabuk, yavaş, toprak yaşayan hayvan.",
      "Tapir": "Uzun burunlu, miskin, Amerika-Asya.",
      "Tukan": "Büyük gaga, renkli, tropikal kuş.",
      "Tasmanya Canlısı": "Gürültülü, çöpçü, Avustralya hayvanı.",
      "Tarsier": "Büyük gözler, gece primat, Endonezya.",
      "Tamarin": "Küçük primat, sosyal, tropikal hayvan."
    },
    "U": {
      "Uakari": "Kırmızı yüzlü primat, sosyal, Amazon.",
      "Urial": "Koyun türü, dağlık, Asya hayvanı.",
      "Deniz Kestanesi": "Başına dikenli, deniz yaşayan, kırılgan."
    },
    "V": {
      "Akbaba": "Saçak uçlu, yüksek uçuşan, temizleme.",
      "Viper": "Zehirli yılan, yılma sokmak, Avrupa.",
      "Vicuna": "Lama benzeri, Andean, ince kıl.",
      "Vervet Makakalı": "Yeşilçe, sosyal, Afrika primati."
    },
    "W": {
      "Kurt": "Sosyal, sürü yaşayan, gece hayvancı.",
      "Balina": "Okyanus memeli, dev, hava soluyan.",
      "Wombat": "Oyucu, Avustralya'nın, eksi bacak.",
      "Mors Balığı": "Uzun dişli, arktik, sosyal memeli.",
      "Gelincik": "Dişili benekli, leotard, Amerika hayvan.",
      "Wolverine": "Güçlü, yırtıcı, Kuzey hayvanı.",
      "Wildebeest": "Göç yapan antilop, Afrika, büyük sürü."
    },
    "X": {
      "Xerus": "Çöl sincap, Afrika, toprağa kazdığı.",
      "Xenops": "Küçük kuş, ağaçta yaşayan, tropikal.",
      "Röntgen Balığı": "Saydam vücut, derin deniz, elektronik."
    },
    "Y": {
      "Yak": "Tüylü, Tibetyan, yüksek dağda yaşayan.",
      "Sarı Mangust": "Yılan yiyen, Afrika, hızlı dönüşü.",
      "Yacare Timsahı": "Timsah türü, Amerika, suda yaşayan.",
      "Yabby": "Tatlı su istakoz, Avustralya, kazdığı."
    },
    "Z": {
      "Zebra": "Çizgili, Afrika, sosyal memeli hayvan.",
      "Zebu": "Boynuz sayısı, ısı tolerant, tropikal.",
      "Zorilla": "Kokulu, nocturnal, Afrika memeli."
    }
  },

  "cities": {
    "A": {"Amsterdam": "Hollanda başkenti, kanallar şehri, bisiklet.", "Atina": "Antik Yunanistan kalbi, Akropolis var.", "Auckland": "Yeni Zelanda şehri, iki deniz arası.", "Ankara": "Türkiye başkenti, Anadolu bölgesinde."},
    "B": {"Barcelona": "İspanya ünlü şehri, Gaudí mimarisi.", "Bangkok": "Tayland başkenti, canlı pazarlar.", "Buenos Aires": "Arjantin başkenti, tango dansı.", "Berlin": "Almanya başkenti, tarihsel şehir."},
    "C": {"Cairo": "Mısır başkenti, Nil kıyısında.", "Chicago": "Amerika şehri, büyük gölü var.", "Copenhagen": "Danimarka başkenti, mimari güzel.", "Casablanca": "Fas şehri, sahil kenti."},
    "D": {"Dubai": "Birleşik Arap, yüksek binalar.", "Delhi": "Hindistan şehri, tarihi merkez.", "Dublin": "İrlanda başkenti, sıcak çay.", "Dhaka": "Bangladeş başkenti, yoğun şehir."},
    "E": {"Edinburgh": "İskoçya başkenti, antik.", "Entebbe": "Uganda şehri, gölü yakın.", "El Paso": "Amerika şehri, sınır konumu."},
    "F": {"Florence": "İtalya sanat kenti, Rönesans.", "Frankfurt": "Almanya şehri, finansal merkez.", "Fuzhou": "Çin şehri, sahil konumu."},
    "G": {"Geneva": "İsviçre şehri, uluslararası.", "Glasgow": "İskoçya şehri, endüstri.", "Guangzhou": "Çin şehri, ticaret merkezi.", "Gothenburg": "İsveç şehri, liman kenti."},
    "H": {"Hong Kong": "Çin şehri, gökdelenleri yüksek.", "Havana": "Küba başkenti, klasik binalar.", "Hamburg": "Almanya şehri, liman kenti.", "Helsinki": "Finlandiya başkenti, kuzey."},
    "I": {"Istanbul": "Türkiye şehri, iki kıtada.", "Islamabad": "Pakistan başkenti, dağları yakın.", "Izmir": "Türkiye sahil şehri, plajlar.", "Indianapolis": "Amerika şehri, Kuzey Merkezi."},
    "J": {"Jakarta": "Endonezya başkenti, büyük şehir.", "Jerusalem": "İsrail şehri, kutsal toplama.", "Johannesburg": "Güney Afrika şehri, büyük."},
    "K": {"Karachi": "Pakistan şehri, liman kenti.", "Kyoto": "Japonya şehri, tarihi tapınak.", "Kuala Lumpur": "Malezya başkenti, kuleler.", "Kinshasa": "Kongo başkenti, nehir kenti."},
    "L": {"London": "İngiltere başkenti, Thames nehri.", "Los Angeles": "Amerika şehri, gölgesiz.", "Lima": "Peru başkenti, sahil şehir.", "Lisbon": "Portekiz başkenti, tepeli."},
    "M": {"Madrid": "İspanya başkenti, merkez.", "Moscow": "Rusya başkenti, Kızıl Meydan.", "Mumbai": "Hindistan şehri, sahil.", "Montreal": "Kanada şehri, Fransız kültür."},
    "N": {"New York": "Amerika şehri, Manhattan.", "Nairobi": "Kenya başkenti, Afrika.", "Naples": "İtalya şehri, Vesüvius yakın.", "New Delhi": "Hindistan başkenti, merkezi."},
    "O": {"Oslo": "Norveç başkenti, fiord bölge.", "Ottawa": "Kanada başkenti, parlamentosu.", "Osaka": "Japonya şehri, ticaret.", "Odessa": "Ukrayna şehri, liman kenti."},
    "P": {"Paris": "Fransa başkenti, aşk şehri.", "Prague": "Çek başkenti, Vltava nehri.", "Perth": "Avustralya şehri, izole.", "Philadelphia": "Amerika şehri, tarih merkezi."},
    "Q": {"Quebec City": "Kanada şehri, Fransız.", "Quito": "Ekvador başkenti, yüksek.", "Quezon City": "Filipin şehri, Metro Manila."},
    "R": {"Rome": "İtalya başkenti, antik şehir.", "Rio de Janeiro": "Brezilya şehri, plajları ünlü.", "Rotterdam": "Hollanda şehri, liman.", "Riyadh": "Suudi Arabistan başkenti, çöl."},
    "S": {"Sydney": "Avustralya şehri, Opera House.", "Seoul": "Güney Kore başkenti, büyük.", "Singapore": "Singapur devleti-şehir, multikultur.", "Stockholm": "İsveç başkenti, adacık.", "Shanghai": "Çin şehri, ticaret merkezi."},
    "T": {"Tokyo": "Japonya başkenti, modern.", "Toronto": "Kanada şehri, CN Tower.", "Tehran": "İran başkenti, dağları yakın.", "Tel Aviv": "İsrail şehri, sahil kenti."},
    "U": {"Ulaanbaatar": "Moğolistan başkenti, steppelerde.", "Utrecht": "Hollanda şehri, uluslararası."},
    "V": {"Vienna": "Avusturya başkenti, müzik.", "Vancouver": "Kanada şehri, dağlı.", "Venice": "İtalya şehri, kanallar.", "Vilnius": "Litvanya başkenti, baltık."},
    "W": {"Warsaw": "Polonya başkenti, Vistula.", "Washington DC": "Amerika başkenti, merkezsel.", "Wellington": "Yeni Zelanda başkenti.", "Winnipeg": "Kanada şehri, soğuk."},
    "X": {"Xi'an": "Çin şehri, Terracotta Ordu."},
    "Y": {"Yokohama": "Japonya şehri, Tokyo yakın.", "Yangon": "Myanmar başkenti, Shwedagon.", "Yerevan": "Ermenistan başkenti, Kaukas."},
    "Z": {"Zurich": "İsviçre şehri, finans.", "Zagreb": "Hırvatistan başkenti, Balkan.", "Zanzibar": "Tanzanya adası, Hint Okyanusu."}
  },

  "foods": {
    "A": {"Almira": "Makarna salata, sos karışık.", "Avokado Tosti": "Ekmek-avokado, kahvaltı.", "Alfredo": "Krem soslu makarna, İtalyan.", "Kuşkonmaz Çorbası": "Bahar çorbası, yeşil."},
    "B": {"Burger": "Ekmek-et patty, klasik.", "Burrito": "Meksika, tortilla dolması.", "Baklava": "Türk tatlısı, kıraç yaprak.", "Brüşetta": "İtalyan, sos ekmek."},
    "C": {"Köri": "Baharatlı, Hindistan yemeği.", "Carbonara": "Makarna, krema-peynir.", "Kruvasan": "Pastane, katmansal.", "Chili Con Carne": "Meksika, fasulye-et."},
    "D": {"Dumpling": "Cıvata şekli, doldurulmuş.", "Dal": "Hint mercimek yemeği.", "Donut": "Tatlı, açılı, glazürü.", "Ördek Confit": "Fransa, yavaş pişirilen."},
    "E": {"Enchilada": "Meksika, biber sos.", "Empanada": "Pasta, dolması etli.", "Yumurta Benedict": "Kahvaltı, Hollandaise.", "Salyangoz": "Fransa, sos ağırı."},
    "F": {"Kızartılmış Patates": "Altın, çıt çıtlı, yan.", "Falafel": "Nohut, Orta Doğu.", "Balık ve Patates": "İngiltere, klasik.", "Kızartılmış Pirinç": "Asya, tavuklu pirinç."},
    "G": {"Gyoza": "Japon dumpling, yapışkan.", "Gumbo": "Louisianna, okra ağırı.", "Guacamole": "Avokado sos, Meksika.", "Gazpacho": "Soğuk çorba, domates."},
    "H": {"Hummus": "Nohut ezmesi, tahini, Orta.", "Hot Dog": "Sosis, ekmek, klasik.", "Patates Hasselback": "Fırında, dilimleme.", "Halloumi": "Kıbrıs peyniri, pişirilebilir."},
    "I": {"Dondurma": "Soğuk tatlı, kremsi.", "Idli": "Hint, pirinç buğday.", "İrlanda Güveç": "Patates-et, Kelt."},
    "J": {"Jambalaya": "Louisianna pirinç, sos.", "Jerk Tavuk": "Jamaika, baharat-grilla.", "Jollof Pirinç": "Afrika, pomadolu.", "Japon Kare": "Japon, hafif."},
    "K": {"Kebap": "Türk, tandır et.", "Kimchi": "Koreli, fermente lahana.", "Katsu Kare": "Japon, kaplama kare.", "Knish": "Yahudi, kartof cıvata."},
    "L": {"Lazanya": "İtalyan, katmansal makarna.", "İstakoz": "Seafood, lüks yemek.", "Mercimek Çorbası": "Türk, ısıtıcı.", "Latke": "Yahudi, patates topak."},
    "M": {"Musakka": "Alafranga, patlıcan, beyaz.", "Miso Çorbası": "Japon, fermente.", "Makaroni": "Makarna, peynir.", "Mole": "Meksika, karmaşık sos."},
    "N": {"Nachos": "Meksika, çip-peynir.", "Noodles": "Makarna, Asya.", "Naan": "Hint, tandır ekmek.", "Nougat": "Şeker tatlısı, antik."},
    "O": {"Omlet": "Yumurta, kıvrılmış.", "Soğan Halkası": "Kızartılmış, açılı.", "Okonomiyaki": "Japon, pancar.", "İstiridye": "Seafood, lüks."},
    "P": {"Pizza": "İtalyan, çeşitli üzeri.", "Paella": "İspanya, pirinç.", "Pad Thai": "Tayland, makarna.", "Pankek": "Kahvaltı, şuruplu."},
    "Q": {"Quiche": "Fransa, pastry-yumurta.", "Quesadilla": "Meksika, peynir tortilla.", "Quindim": "Brezilya, yumurta tatlı."},
    "R": {"Ramen": "Japon, makarna çorba.", "Risotto": "İtalyan, pirinç krema.", "Ravioli": "İtalyan, pasta dolma.", "Rendang": "Malezya, et."},
    "S": {"Sushi": "Japon, pirinç-balık.", "Biftek": "Kızartılmış, et kesildi.", "Sandwich": "Ekmek-dolma, taşınabilir.", "Shawarma": "Orta Doğu, et döner."},
    "T": {"Tacos": "Meksika, et-kısrak.", "Tikka Masala": "Hint, tandır-krem.", "Tempura": "Japon, kaplama kızartma.", "Tiramisu": "İtalyan, kahve tatlı."},
    "U": {"Udon": "Japon, makarna kalın.", "Ugali": "Afrika, mısır buğday.", "Ube Pastası": "Filipin, ube tatlı."},
    "V": {"Vichyssoise": "Fransa, soğuk çorba.", "Vindaloo": "Hint, baharat ağırı.", "Veal Scallopini": "İtalyan, dana."},
    "W": {"Waffle": "Paniyer, ızgara şekli.", "Wontons": "Çin, dumpling.", "Beyaz Pirinç": "Temel, pirinç.", "Wiener Schnitzel": "Avusturya, dana."},
    "X": {"Xiaolongbao": "Çin, dumpling broth.", "Xo Sosu": "Asya, balıkçı sos."},
    "Y": {"Yakitori": "Japon, tavuk çiş.", "Yoğurt": "Fermente, tatlı.", "Yorkshire Pudding": "İngiltere, puding.", "Yakisoba": "Japon, noodle-grill."},
    "Z": {"Zabaglione": "İtalyan, yumurta tatlı.", "Ziti": "Makarna, tüp.", "Zeppole": "İtalyan, donut tatlı.", "Kabak Kızartması": "Meksika, kabak fırın."}
  },

  "vegetables": {
    "A": {"Kuşkonmaz": "Bahar sebze, yeşil dal, ince.", "Enginar": "Dikenli, yeşil, akdeniz.", "Roka": "Yeşil yaprak, keskin tat.", "Avokado": "Yeşil, kremsi, besleyici."},
    "B": {"Brokoli": "Yeşil çiçek, besleyici, başlı.", "Brüksel Lahanası": "Küçük lahana, yeşil, kış.", "Pancar": "Kırmızı, kök, tatlı."},
    "C": {"Havuç": "Turuncu, tatlı, kök.", "Karnabahar": "Beyaz çiçek, besleyici.", "Lahana": "Yeşil-kırmızı, yapraklar.", "Kereviz": "Yeşil dal, tatlı-asidik."},
    "D": {"Daikon": "Beyaz turp, Asya sebze.", "Karahindiba Yaprağı": "Koyu yeşil,苦.", "Delicata Balkabağı": "Yeşil dış, turuncu iç."},
    "E": {"Patlıcan": "Mor-siyah, esnek, İtalyan.", "Edamame": "Yeşil soya fasulye, tatlı.", "Endive": "Açık yeşil, acılı.", "Escarole": "Yeşil yaprak, estetik."},
    "F": {"Rezene": "Beyaz-yeşil, nadir, tat.", "Fiddlehead Eğreltisi": "Yeşil kıvrıntı, nadir.", "Yeşil Fasulye": "Uzun, yeşil, besleyici.", "Fasulye": "Yeşil veya kuru olarak tüketilen, protein açısından zengin bir baklagil."},
    "G": {"Sarımsak": "Beyaz çiçek, güçlü tat.", "Zencefil": "Kök sebze, tat-ilac.", "Yeşil Soğan": "Beyaz-yeşil, hafif tat.", "Galangal": "Kök, Asya, limon."},
    "H": {"Beyin Otu": "Yeşil yaprak, çiğ, beslenme.", "Palmiye Kalbi": "Beyaz dali, nadir.", "Haricot Fasulyesi": "Beyaz fasulye, tatlı."},
    "I": {"Hint Ispanağı": "Yeşil yaprak, spinach benzeri.", "Buz Marulu": "Açık yeşil, çıt çıtlı."},
    "J": {"Jicama": "Beyaz, tatlı kök, Meksika.", "Kudüs Enginarı": "Kök, tatlı, yer elması.", "Jalapeno": "Yeşil biber, keskin."},
    "K": {"Kara Lahana": "Yeşil kıvrılmış, beslenme.", "Kohlrabi": "Yeşil-kırmızı, gövde.", "Komatsuna": "Yeşil yaprak, Asya."},
    "L": {"Pırasa": "Beyaz-yeşil, soğan benzeri.", "Marul": "Açık yeşil, yaprak.", "Mercimek": "Kırmızı-yeşil, kuru.", "Lima Fasulyesi": "Yeşil-krem, tatlı."},
    "M": {"Mantar": "Beyaz-kahverengi, fungi.", "Sarı Hardal Yaprağı": "Yeşil, keskin, Asya.", "Mangetout": "Yeşil bölüm, yenilebilir.", "Mung Fasulyesi": "Yeşil, kuru, Asya."},
    "N": {"Napa Lahanası": "Açık yeşil, Çin, yaprak.", "Nori": "Siyah deniz yosunu, Asya."},
    "O": {"Soğan": "Beyaz-kırmızı-sarı, kat.", "Okra": "Yeşil, uzun, tatlı.", "Ismen Mantarı": "Beyaz, belirgin.", "Otlu Peynir Biber": "Taze yeşil biber çeşidi, otlu peynir ile birlikte tüketilir."},
    "P": {"Patates": "Beyaz-kırmızı, krahu, yüksek.", "Bezelye": "Yeşil küçük, tatlı.", "Biber": "Kırmızı-yeşil-sarı, tatlı.", "Balkabağı": "Turuncu, tatlı, sonbahat."},
    "Q": {"Kinoa": "Beyaz tane, besleyici, Andean."},
    "R": {"Turp": "Kırmızı-beyaz, çiğ, tatlı-acı.", "Şalgam": "Beyaz kök, hafif, Avrupa.", "Radicchio": "Kırmızı-beyaz, acılı.", "Kırmızı Lahana": "Kırmızı, tatlı, beslenme."},
    "S": {"Ispanak": "Koyu yeşil, demir, yaprağı.", "Tatlı Patates": "Turuncu, tatlı, beslenme.", "Balkabağı": "Turuncu, tatlı, sonbahat.", "Scallion": "Beyaz-yeşil, hafif soğan."},
    "T": {"Domates": "Kırmızı, tatlı-asidik, beslenme.", "Şalgam": "Beyaz kök, hafif tat.", "Taro": "Kahverengi, kök, nişastacı.", "Tomatillo": "Yeşil, portakal benzeri."},
    "U": {"Ulluco": "Andean patates, renkli.", "Upo": "Uzun kabak, Asya."},
    "V": {"Asma Domates": "Kırmızı, güzel lezzet.", "Kadife Fasulyesi": "Yeşil-mor, tatlı."},
    "W": {"Su Teresi": "Yeşil yaprak, çiğ, beslenme.", "Su Kestanesi": "Beyaz gövde, tatlı.", "Wakame": "Deniz yosunu, Asya.", "Beyaz Turp": "Beyaz, uzun, Asya.", "Wasabi Kökü": "Japon mutfağında kullanılan, acı ve yakıcı yeşil bir kök sebze."},
    "X": {"Xigua": "Kavun türü, Çin, büyük.", "Xigua Kabuğu": "Karpuz kabuğu turşusu olarak hazırlanan bir sebze garnitürü."},
    "Y": {"Yam": "Dünya patates, beslenme, tuberöz.", "Yuka": "Kök sebze, nişastacı, Asya.", "Sarı Balkabağı": "Turuncu, tatlı, sonbahat."},
    "Z": {"Kabak": "Sarı-yeşil, beslenme, yaz.", "Kabak Çiçeği": "Sarı çiçek, yenilebilir."}
  },

  "sports": {
    "A": {"Okçuluk": "Yay ve ok, hedef vurmak, antik.", "Atletizm": "Koşu, sıçrama, atma sporları.", "Amerikan Futbolu": "Takımlar, kontakt, top, Amerikan."},
    "B": {"Basketbol": "Top sepete, iki takım, dış.", "Beyzbol": "Sopalar, toplar, Amerikan, baz.", "Badminton": "Raket, tüyü top, çift."},
    "C": {"Kriket": "Sopalar, toplar, İngiliz spor.", "Bisikletçilik": "Pedal bisiklet, hızlı, dış.", "Curling": "Buz, taş, slide, Kuzey."},
    "D": {"Dalış": "Suya batmak, oksijen, sıkı.", "Disk Atışı": "Metal disk, uzaklık, antik.", "Dodgeball": "Top, kaçma, grup sporu."},
    "E": {"Atlı Spor": "At üstünde, bariyer, düzey.", "Dayanıklılık Yarışması": "Uzun mesafe, direniş, thatched.", "Ekstrem Sporlar": "Riskli, heyecan, adrenalin."},
    "F": {"Futbol": "Top ayak, gol, dünya ünlü.", "Floret": "Kılıç sporu, beraber, sanat.", "Artistik Patinaj": "Buz pateni, musik, sanat.", "Saha Hokeyi": "Sopa, top, yer, hızlı."},
    "G": {"Golf": "Top delik, açık alan, hafif.", "Jimnastik": "Hareket, denge, asılı, sanat.", "Go-Kart Yarışması": "Mini araba, yer, hızlı."},
    "H": {"Hokey": "Sopalar, puck, buz veya alan.", "Hentbol": "Top atma, gol, takım.", "Yüksek Atlama": "Bar, yükseklik, atlama.", "Engel Yarışı": "Koşu, bariyerler, hızlı."},
    "I": {"Buz Hokeyi": "Buz paten, sopalar, hızlı.", "Buz Pateni": "Buz, eğlence veya yarış.", "İç Voleybol": "Top ağ, kapalı, takım."},
    "J": {"Judo": "Japon sanat, yatırma, ağır.", "Cirit Atışı": "Metal cirit, uzaklık, antik.", "Jai Alai": "Hızlı top, bahis, Bask."},
    "K": {"Karate": "Japon dövüş, boş el, güç.", "Kayak": "Kar, inişli iniş, spora.", "Kick Boks": "Tekme dövüş, Tayland, kontakt.", "Kendo": "Japon kılıç, sanat, geleneksel."},
    "L": {"Lacrosse": "Ağ sopası, top, Kuzey.", "Luge": "Buz, kızak, hızlı yokuş.", "Uzun Atlama": "Sandbox, uzaklık, antik.", "Log Yüzen": "Denge, tay, su sporu."},
    "M": {"Maraton": "Uzun koşu, 42km, direniş.", "Dağ Tırmanışı": "Yükseklik, dış, macera.", "Karışık Dövüş": "Çok teknik, kontakt, dahili.", "Motocross": "Motorsiklet, çamur, yer."},
    "N": {"Netball": "Basketbol benzeri, duvar, takım.", "Nordik Kayağı": "Kar, dış, uzun.", "Nordik Kombinesi": "Kayak-atlama, kar, Skandinav."},
    "O": {"Olimpik Halter": "Ağır kaldırma, Olimpik, güç.", "Engel Koşusu": "Koşu, bariyerler, hızlı."},
    "P": {"Polo": "Atlar, sopalar, top, zengin.", "Ping Pong": "Masa tenisi, tatlı, hızlı.", "Parkour": "Parkta atlama, bariyerler, oryantir.", "Pentathlon": "Beş spor, kombinasyon, Olimpik."},
    "Q": {"Quoits": "Halka atma, kazan, eski.", "Dört Sporlu Yarış": "Kombinasyon, Olimpik, dahili."},
    "R": {"Rugby": "Oval top, kontakt, İngiliz.", "Kürek": "Tahta, su, takım.", "Kaya Tırmanışı": "Dış, dişler, macera.", "Racquetball": "Raket, top, kapalı."},
    "S": {"Yüzme": "Suya batmak, uzaklık, Olimpik.", "Futbol": "Top ayak, gol, dünya.", "Kayak": "Kar, inişli iniş, spora.", "Squash": "Raket, top, kapalı hızlı."},
    "T": {"Tenis": "Raket, top, iki oyuncu.", "Saha ve Pist": "Bileşik spor, Olimpik, dahili.", "Taekwondo": "Kore dövüş, tekme, antrenman.", "Üç Sporlu Yarış": "Yüzme-bisiklet-koşu, kombinasyon.", "Masa Tenisi": "Masada, raket, hızlı."},
    "U": {"Ultimate Frisbee": "Frisbee, alan, ofansif spor.", "Ultramaraton": "Çok uzun koşu, direniş, dış.", "Su Altı Hokeyi": "Su, puck, maske sporu."},
    "V": {"Voleybol": "Top ağ, takım, kapalı.", "Vault": "Atılış, bariyer, jimnastik."},
    "W": {"Güreş": "Iki vücut, kontakt, antik.", "Su Polosu": "Su, top, takım, Olimpik.", "Halter": "Ağır kaldırma, güç, antik.", "Rüzgar Kayağı": "Su, rüzgar, kite, modern."},
    "X": {"X-Games": "Ekstrem sporlar, triks, heyecan."},
    "Y": {"Yoga": "Esneklik, meditasyon, Hint.", "Yacht Yarışması": "Tekne, rüzgar, su."},
    "Z": {"Zorbing": "Büyük top içinde, inişli, dış."}
  },

  "instruments": {
    "A": {"Akordeon": "Tuş-hava, bellows, folk müzik.", "Alto Saksafon": "Tunç, orta ton, caz.", "Autoharp": "Tuşlu, akor, otomatik."},
    "B": {"Banjo": "Beş tel, yüksek ses, folk.", "Bas Gitar": "Dört tel, kalın ses, ritim.", "Keçi Borusu": "Eski borusu, uzun, derinlik."},
    "C": {"Klarnet": "Tahta işlenen, reed, orkestra.", "Çello": "Dört tel, derin, orkestra.", "Kornet": "Pirinç, valves, caz."},
    "D": {"Davul": "Perdes, ritim, orkestra.", "Dulcimer": "Çekiç-tel, tatlı, antik.", "Didgeridoo": "Aborjin, uzun tüp, bölge."},
    "E": {"Elektrik Gitar": "Tel, elektrik, rock müzik.", "Elektrik Keman": "Yay, elektrik, modern.", "Euphonium": "Pirinç, derin, orkestra."},
    "F": {"Flüt": "Üflemeli, hava, treble ses.", "Fransız Borusu": "Pirinç, spiral, caz.", "Keman": "Tel, yay, orkestra.", "Flugelhorn": "Pirinç, mellow, caz."},
    "G": {"Gitar": "Tel enstrüman, akustik, klasik.", "Aksan Piyano": "Güzel-inşaat, klasik.", "Gong": "Vurma enstrüman, geniş, meditasyon.", "Cam Harmonikas": "Cam tel, titreşim, nadir."},
    "H": {"Ağız Harmonikası": "Küçük, üflemeli, taşınabilir.", "Arp": "Şerit-kütüphane, elektronik, vintage.", "Klavisembal": "Tuş, aynaklı, antik.", "Borusu": "Üflemeli, metal, eski."},
    "I": {"İrlanda Flütü": "Tin whistle, hafif, folk.", "İrlanda Uilleann Borusu": "Durum, kompleks, geleneksel."},
    "J": {"Caz Trompeti": "Pirinç, valves, caz müzik."},
    "K": {"Klavye": "Tuş, elektronik, modern müzik.", "Koto": "Telili, Japon, geleneksel.", "Kalimba": "Parmak-tel, Afrika, tatlı."},
    "L": {"Lute": "Tel, eski, Rönesans müzik.", "Lir": "Antik telili, lyra, Yunan."},
    "M": {"Mandolin": "Sekiz tel, küçük, folk.", "Marimba": "Vurma, xylophone büyük, canlı.", "Melodika": "Tuş, üflemeli, hafif."},
    "N": {"Burun Flütü": "Nazal üflenen, nadir, etnoloji."},
    "O": {"Obua": "Çift reed, pürüzlü ses.", "Organ": "Tuş, hava, kilise.", "Ocarina": "Keramik, flüt, antik."},
    "P": {"Piyano": "88 tuş, çekiç, klasik.", "Piccolo": "Küçük flüt, yüksek, orkestra.", "Pan Flütü": "Tüpler, üflemeli, eski."},
    "Q": {"Qin": "Yedi tel, Çin, eski müzik.", "Qanun": "Çok tel, Orta Doğu, değerli."},
    "R": {"Recorder": "Tahta üflemeli, şarkı, öğrenme.", "Rhodes Piyano": "Elektrik piyano, retro, caz."},
    "S": {"Saksafon": "Pirinç, reed, caz-pop.", "Sitar": "Hint telili, rezonans, exotik.", "Sousaphone": "Pirinç, spiral, marş-bant.", "Çelik Davul": "Davul türü, melodi, Karayip."},
    "T": {"Trompet": "Pirinç, valves, parlak ses.", "Trombon": "Pirinç, slide, orkestra.", "Tuba": "Pirinç, derin, orkestra.", "Def": "Vurma, frame, geleneksel.", "Theremin": "Elektronik, hava-kontrol, nadir."},
    "U": {"Ukulele": "Dört tel, küçük, Hawaiki.", "Ud": "Armut şekilli gövdesi olan, Ortadoğu kökenli telli bir çalgı."},
    "V": {"Keman": "Tel, yay, orkestra başarılı.", "Viola": "Dört tel, derin keman.", "Vibrafon": "Vurma, rezonans, metal."},
    "W": {"Washboard": "Çamaşır panosu, ritimleme, folk.", "Rüzgar Çanları": "Metal tüpler, rüzgar, meditasyon.", "Düdük": "Antik, tatlı, Ermenistan.", "Wagner Tuba": "Wagner operalarında kullanılan, korno ve tuba arası bir bakır üflemeli çalgı."},
    "X": {"Ksilofon": "Tahta çubuklar, vurma, orkestra."},
    "Y": {"Yangqin": "Çekiç-çubuk, Çin, hammered.", "Yueqin": "Yuvarlak lutlu, Çin, el."},
    "Z": {"Zither": "Çoklu tel, vurma-plek, eski.", "Zurna": "Ütüsüz pirinç, Orta Doğu, gür."}
  },

  "occupations": {
    "A": {"Oyuncu": "Sahne-film, rol oynamak, eğlence.", "Mimar": "Bina tasarım, yapı, uzman.", "Muhasebe Elemanı": "Mali kayıt, hesaplama, işletme."},
    "B": {"Fırıncı": "Ekmek yapma, fırın, sabah.", "İnşaat Ustası": "Yapı inşa, emek, uzman.", "Bankacı": "Mali hizmet, para, işlemler."},
    "C": {"Aşçı": "Yemek yapma, mutfak, beslenme.", "Marangoz": "Ahşap işleme, mobilya, zanaatkar.", "Kasiyer": "Para işlemi, kasa, satış."},
    "D": {"Doktor": "Sağlık, hasta tedavi, tıp.", "Diş Hekimi": "Diş sağlığı, laboratuvar, tıp.", "Dedektif": "Suç çalışma, polis, araştırma."},
    "E": {"Mühendis": "Makine tasarım, yapı, teknoloji.", "Elektrikçi": "Elektrik işleri, döşeme, teknisyen.", "Editör": "Metin düzen, yayın, yazılı."},
    "F": {"Çiftçi": "Tarım-hayvancılık, arazi, mevsim.", "İtfaiyeci": "Yangın söndürme, kurtarma, tehlike.", "Çiçekçi": "Çiçek satış, arrazne, dekorasyon."},
    "G": {"Bahçıvan": "Bitki yetiştirme, peyzaj, dış.", "Jeolog": "Yer bilimleri, kayaç, inceleme.", "Grafik Tasarımcı": "Görsel tasarım, bilgisayar, sanat."},
    "H": {"Tarihçi": "Geçmiş araştırma, kaynak, bilim.", "Avcı": "Yaban hayvanı avı, mevsimlik, geleneksel.", "Kuaför": "Saç kesim, salon, güzellik."},
    "I": {"Tercüman": "Dil tercüme, iki dil, iletişim.", "Müfettiş": "Uyum denetimi, kural, yönetim.", "İllüstratör": "Resim yapma, kitap, sanat."},
    "J": {"Yargıç": "Hukuk karar, adalet, mahkeme.", "Gazeteci": "Haber toplama, gazete, basın.", "Kuyumcu": "Kuyumcu işleri, altın, sanat."},
    "K": {"Kinesiolog": "Hareket terapisi, rehabilitasyon, sağlık."},
    "L": {"Avukat": "Hukuk danışmanlık, dava, adalet.", "Kütüphaneci": "Kitap yönetimi, arşiv, bilgi.", "Dilbilimci": "Dil çalışma, teorisi, akademik."},
    "M": {"Teknisyen": "Araç onarım, elektrik, mekanik.", "Müzisyen": "Müzik yapma, caz, sahnesi.", "Yönetici": "İş yönetim, kararlar, liderlik.", "Matematikçi": "Sayı araştırma, teori, akademik."},
    "N": {"Hemşire": "Hasta bakımı, sağlık, tıbbi.", "Beslenme Uzmanı": "Diyet danışmanlık, sağlık, beslenme.", "Navigator": "Rota planlama, gemi, havacılık."},
    "O": {"Optisyen": "Göz sağlığı, gözlük, mercekler.", "Operatör": "Makine işletme, teknoloji, işletme.", "Obstetrik Uzmanı": "Doğum tıbbı, kadın, tıp."},
    "P": {"Fotoğrafçı": "Resim çekme, kamera, sanat.", "Pilot": "Uçak pilotluğu, gökyüzü, hava.", "Tesisatçı": "Su işleri, boru, mekanik.", "Programcı": "Yazılım yazma, kod, bilgisayar.", "Eczacı": "İlaç dağıtma, farmasi, sağlık."},
    "Q": {"Yorgan Ustası": "Kumaş işlemesi, yorgan, zanaat.", "Taş Ocağı İşçisi": "Taş çıkarma, emek, madencilik."},
    "R": {"Muhabir": "Haber toplama, gazete, basın.", "Orman Koruma Memuru": "Orman yönetimi, doğa, koruma.", "Araştırmacı": "Bilimsel araştırma, akademik, bilim.", "Radyoloji Teknisyeni": "X-ray işlemi, tıbbi, görüntü."},
    "S": {"Cerrah": "Ameliyat yapma, tıp, operasyon.", "Bilim İnsanı": "Bilim araştırması, deneyler, akademik.", "Satış Danışmanı": "Ürün satış, müşteri, pazarlama.", "Denizci": "Gemi işleri, deniz, navigasyon.", "Yazılım Mühendisi": "Yazılım tasarım, kod, teknoloji."},
    "T": {"Öğretmen": "Eğitim verme, sınıf, bilgi.", "Teknisyen": "Araç onarım, mekanik, teknoloji.", "Terapeut": "Terapist hizmet, sağlık, danışmanlık.", "Çevirmen": "Metin çevirme, diller, iletişim.", "Toksikoloji Uzmanı": "Zehir çalışma, tıbbi, araştırma."},
    "U": {"Undertaker": "Cenaze hazırlığı, gömme, dini.", "Şehir Plancısı": "Şehir tasarım, planlama, mimari.", "UX Tasarımcı": "Kullanıcı deneyim, arayüz, tasarım."},
    "V": {"Veteriner": "Hayvan sağlığı, tıp, tedavi.", "Keman Virtuozu": "Müzik ustası, keman, sahnesi.", "Video Oyunu Tasarımcısı": "Oyun tasarım, programlama, sanat."},
    "W": {"Yazar": "Kitap yazma, yaratıcı, edebiyat.", "Kaporta Ustası": "Kapı açma, emek, zanaatkar.", "Garson": "Yiyecek servisi, restoran, hizmet.", "Web Geliştirici": "Web sitesi tasarım, kod, teknoloji."},
    "X": {"Xylografi Sanatçısı": "Ahşap oyma, bas relief, sanat.", "X-Ray Teknisyeni": "Hastanelerde röntgen çekimi yapan ve görüntüleri hazırlayan sağlık personeli."},
    "Y": {"Yoga Eğitmeni": "Yoga öğretme, meditasyon, sağlık.", "Gençlik Danışmanı": "Genç danışmanlık, rehberlik, sosyal."},
    "Z": {"Zooloji Bilimci": "Hayvan çalışma, araştırma, bilim.", "Hayvanat Bahçesi Sorumlusu": "Hayvan bakımı, yönetim, koruma.", "Zoolog": "Hayvanları, davranışlarını ve yaşam alanlarını inceleyen bilim insanı."}
  },

  "birds": {
    "A": {"Akbaba": "Yüksek uçan, temizleme kuşu, koyu kanatlar.", "Alaşama": "Afrika kuşu, uzun bacaklar, çelik renk.", "Antartika Pengueni": "Pinguen, kutup, siyah-beyaz."},
    "B": {"Baykuş": "Gece kuşu, kalkık kulakları, büyük gözler.", "Leylek": "Uzun bacaklı, çıkrıkçı ötüşü, konuşan kuş.", "Berkut": "Kartal, güçlü tırnak, şahan kuşu."},
    "C": {"Horozbaşı": "Kızıl renk, başında tepsi, su kuşu.", "Alaçatı": "Çin'den kuş, pembe-mavi renk.", "Saksağan": "Siyah-beyaz, çalı kuşu, sosyal."},
    "D": {"Ördeği": "Su kuşu, yüzen, yeşil başlı.", "Avcı Kartal": "Avlayan kuş, hızlı dalmış.", "Devekuşu": "Kanatlamayan kuş, Avusturalya, büyük."},
    "E": {"Emu": "Kanatlamayan, Avusturya'nın, hızlı koşu.", "Ak Leylek": "Beyaz renk, uzun bacak, kırışık.", "Kakım": "Papağan türü, Avusturalya, zarif."},
    "F": {"Flamingo": "Pembe renk, uzun bacak, su kuşu.", "Fare Şahini": "Hızlı avcı, Şahin, küçük.", "Çavuş": "Vahşi kuş, kırmızı yüz, bahçe."},
    "G": {"Kaz": "Su kuşu, beyaz-gri renk, sosyal.", "Kumru": "Güvercin türü, yumuşak ses.", "Yeşil Papağan": "Parlak yeşil, zeki, uzun ömürlü."},
    "H": {"Şahin": "Güçlü avcı, keskin gözler, havada.", "Sandalye": "Bahçe kuşu, sarı-siyah renk.", "Avi Ispanak": "Kırmızı gözlü, çiftçi hasatçısı."},
    "I": {"Ibis": "Uzun gaga, su kuşu, beynelmilel.", "İzmarit Cıvıltı": "Küçük, renkli, ormanda yaşayan."},
    "J": {"Kargagiller": "Zeki kuşlar, siyah renk, sosyal."},
    "K": {"Kırlangıç": "Hızlı uçan, çamurdan yuva, yaz.", "Kalabubalık": "Papağan, Avusturya, çalı."},
    "L": {"Loon": "Suya dalış kuşu, Kuzey sesleri.", "Leylek": "Uzun bacaklı, beyaz-siyah, konuşan."},
    "M": {"Ağaç Özütleyici": "Ağaç deliği kazıcı, parlak çizgi.", "Martı": "Deniz kuşu, gri-beyaz renk.", "Kuş Balık": "Balık yiyen, çok dalmış."},
    "N": {"Ağaç Kavakçısı": "Ağaçta yaşayan, çizgili kanat.", "Bülbül": "Güzel sesleri, bahçe kuşu."},
    "O": {"Baykuş": "Gece kuşu, yuvarlak yüz, gözler.", "Oriole": "Turuncu-siyah, kız bahçesi."},
    "P": {"Papağan": "Zeki, renkli, uzun ömürlü.", "Ördek": "Su kuşu, yüzen, ördek.", "Perdes": "Şahin türü, ormanda yaşayan."},
    "Q": {"Bıldırcın": "Küçük kuş, tıklamaya benzer ses."},
    "R": {"Kırmızı Kuş": "Kırmızı renk, erkek, güzel.", "Yılan Kartalı": "Yılan avlayan, hızlı dalış."},
    "S": {"Kırlangıç": "Siyah-beyaz, hızlı uçan, yaz.", "Serçe": "Küçük kahverengi, bahçe kuşu.", "Kuğu": "Beyaz, uzun boyun, zarif."},
    "T": {"Bülbül": "Güzel şarkı, bahçe kuşu, siyah.", "Turaç": "Ormanda yaşayan, hızlı kuş.", "Temmuz Kuşu": "İyi şarkı, turuncu-kırmızı."},
    "U": {"Yapıştırma": "Orman kuşu, vurma sesi."},
    "V": {"Kargagil": "Zeki kuş, siyah, sosyal.", "Uzunhacı": "Kuş, konik gagası.", "Vakvak Kuşu": "Ötüşüyle bilinen, ormanlık alanlarda yaşayan renkli bir kuş."},
    "W": {"Su Şahini": "Su üstündeki balık avlayan.", "Güvercin": "Beyaz renkli barış sembolü."},
    "X": {"X-ray Papağanı": "Parlak renk, nadir papağan.", "Xantus Sinekkuşu": "Meksika kıyılarında yaşayan küçük ve hızlı bir sinek kuşu türü."},
    "Y": {"Sarıştıran": "Sarı renk, küçük kuş."},
    "Z": {"Zü Kuşu": "Turuncu renk, Afrika kuşu."}
  },

  "flowers": {
    "A": {"Açelya": "Pembe çiçek, bahar, bahçe.", "Amarilis": "Kırmızı-beyaz, büyük çiçek.", "Anemon": "Öğle çiçeği, mor-pembe renk."},
    "B": {"Çardak Gülü": "Kırmızı gül, bahçe güzelliği.", "Bergamote": "Turuncu çiçek, hoş koku.", "Bileyi": "Mavi çiçek, bahar çiçeği."},
    "C": {"Kamelya": "Kırmızı-pembe, kışlık çiçek.", "Yüz Çiçeği": "Mor-sarı, renkli çiçek.", "Krizantem": "Sonbahat çiçeği, sarı-kırmızı."},
    "D": {"Narcissus": "Sarı çiçek, ilkbahar, fırfır.", "Dahlia": "Renkli çiçek, büyük yapı.", "Doğum Çiçeği": "Pembe renk, sembolik anlamı."},
    "E": {"Eremurus": "Uzun sap, sarı çiçek.", "Echinacea": "Mor kenar, sarı merkez."},
    "F": {"Forsythia": "Sarı çiçek, ilkbahar habercisi.", "Freesia": "Hoş kokulu, beyaz-pembe."},
    "G": {"Geranyum": "Pembe-kırmızı, bahçe çiçeği.", "Gamodan": "Sarı çiçek, bahçe çiçeği.", "Gül": "Kırmızı-pembe, hoş koku, sembol."},
    "H": {"Hyacinth": "Mor-pembe, hoş koku, ilkbahat.", "Hibiscus": "Turuncu-kırmızı, tropikal."},
    "I": {"İris": "Mor-mavi, kılıç-şekli yaprak."},
    "J": {"Jasminum": "Beyaz çiçek, gece koku.", "Jessamine": "Sarı çiçek, sarı-pembe."},
    "K": {"Kanarya Çiçeği": "Sarı renk, bahar çiçeği.", "Keratin": "Pembe çiçek, bahçe çiçeği."},
    "L": {"Lavanta": "Mor çiçek, hoş koku, tıbbi.", "Çiçek Asaletli": "Pembe renk, bahçe çiçeği.", "Lilyum": "Beyaz-turuncu, büyük çiçek."},
    "M": {"Manolya": "Pembe-mor, ilkbahar, bahçe.", "Kız Çiçeği": "Turuncu çiçek, hoş koku.", "Yay Gülü": "Pembe-kırmızı renk."},
    "N": {"Narcissus": "Sarı çiçek, ilkbahar.", "Nigella": "Mavi çiçek, bahçe çiçeği."},
    "O": {"Orkide": "Exotik çiçek, renkli, nadir.", "Ölümsüz Çiçek": "Kırmızı renk, bahçe çiçeği."},
    "P": {"Peony": "Pembe-kırmızı, çok tabakalı.", "Papanin": "Pembe renk, çiçek.", "Pansy": "Mor-sarı renk, bahçe."},
    "Q": {"Pruvanus": "Beyaz çiçek, ilkbahar."},
    "R": {"Gül": "Kırmızı-pembe, hoş koku, sembol.", "Ranunculus": "Sarı renk, çok tabakalı."},
    "S": {"Ayçiçeği": "Sarı çiçek, büyük, güneş.", "Snapdragon": "Kırmızı-turuncu, çiçek.", "Stor": "Pembe çiçek, bahçe çiçeği."},
    "T": {"Lale": "Kırmızı-turuncu, ilkbahar.", "Tatlı Hazır": "Beyaz-pembe, hoş koku.", "Tigridia": "Kırmızı-turuncu, tropikal."},
    "U": {"Urtica": "Beyaz çiçek, orman çiçeği."},
    "V": {"Verbena": "Pembe-mor, bahçe çiçeği.", "Violet": "Mor çiçek, küçük, sembol."},
    "W": {"Wisteria": "Mor-pembe, sarmaşık, ilkbahar.", "Azalea": "Turuncu çiçek, bahçe çiçeği."},
    "X": {"X Çiçek": "Nadir çiçek, bahçe."},
    "Y": {"Sarı Gül": "Sarı renk, gül türü.", "Yardım Gülü": "Turuncu renk, bahçe çiçeği."},
    "Z": {"Zinnias": "Renkli çiçek, bahçe çiçeği, yazlık."}
  },

  "trees": {
    "A": {"Muğla": "Gömbek yapı, dış ağaç, yeşil.", "Akasya": "Sarı çiçek, dış kılcal yaprak.", "Elma Ağacı": "Meyve ağaç, beyaz çiçek."},
    "B": {"Huş Ağacı": "Beyaz gövde, kuzey ağacı.", "Kayın Ağacı": "Kahverengi yaprak, sert ağaç.", "Çifte Ağacı": "Düğün çiçeği, beyaz çiçek."},
    "C": {"Çinko": "Dış, yeşil yaprak, sert.", "Sedir Ağacı": "Kırmızı ağaç, aromatik, değerli.", "Kiraz Ağacı": "Beyaz çiçek, kiraz meyvesi."},
    "D": {"Ebe Gümrüğü": "Dış, sert ağaç, değerli.", "Çift Ağacı": "Dış, yeşil yaprak, sert.", "İngiltere Ağacı": "Ulmus, dış, değerli ağaç."},
    "E": {"Öğrenci Ağacı": "Dış ağaç, yeşil yaprak."},
    "F": {"İncir Ağacı": "Meyve ağaç, yeşil yaprak, ilk.", "Aleluyah Ağacı": "Dış ağaç, çiçekli.", "Fırın Ağacı": "Kırmızı ağaç, değerli."},
    "G": {"Ginkgo": "Eski ağaç, fan-şekli yaprak.", "Gövde Ağacı": "Dış ağaç, yeşil yaprak.", "Guaiacum": "Dış ağaç, sert ağaç."},
    "H": {"Hazel Ağacı": "Kuruluk ağacı, fındık meyvesi.", "Akça Ağacı": "Dış ağaç, gül yaprak.", "Hemlock": "Kuzey ağacı, yeşil yaprak."},
    "I": {"İron Ağacı": "Sert ağaç, demir-gibi."},
    "J": {"Jujube Ağacı": "Meyve ağaç, asidik.", "Japonya Ağacı": "Asya ağacı, yapı."},
    "K": {"Kestane Ağacı": "Kestane meyvesi, büyük ağaç.", "Kiş": "Kuzey ağacı, dış."},
    "L": {"Çıra Ağacı": "Kuzey ağacı, dış, yeşil.", "Linden Ağacı": "Hoş kokulu çiçek, kalp yaprak.", "Sarıçam": "Sarı ağaç, dış, konifer."},
    "M": {"Akçaağaç": "Kırmızı yaprak, hoş, dış.", "Portakal Ağacı": "Meyve ağaç, sarı çiçek.", "Papaya Ağacı": "Tropikal ağaç, meyve."},
    "N": {"Ceviz Ağacı": "Ceviz meyvesi, sert ağaç.", "Ağaç Defteri": "Bilim ağacı, yapılı."},
    "O": {"Zeytin Ağacı": "Zeytin meyvesi, güney ağacı.", "Oak": "Sert ağaç, yaprak yapı."},
    "P": {"Çam Ağacı": "Konifer, iğne yaprak, reçine.", "Huş": "Beyaz ağaç, uzun, yeşil.", "Pistachio": "Ağaç meyve, Orta Doğu."},
    "Q": {"Quercus": "Oak ailesinden, sert ağaç."},
    "R": {"Kırmızı Akçaağaç": "Kırmızı yaprak, güzel.", "Muğla": "Dış ağaç, kırmızı."},
    "S": {"Çam": "Konifer, sert ağaç, ahşap.", "Huş": "Kuzey ağacı, beyaz.", "Dut": "Meyve ağacı, siyah meyve."},
    "T": {"Terebinth": "Dış ağaç, yeşil.", "Akasya": "Dış çiçek, yapraklı.", "Teak": "Tropikal ağaç, sert, değerli."},
    "U": {"Ülke Ağacı": "Dış ağaç, yapı."},
    "V": {"Elbelik": "Almanya ağacı, yapı."},
    "W": {"Ceviz": "Sert ağaç, ceviz meyvesi.", "Söğüt": "Su yaşayan, uzun budak."},
    "X": {"Xanthoxylum": "Dış ağaç, tıbbi."},
    "Y": {"Sarı Akçaağaç": "Sarı yaprak, güzel.", "Sarı Çam": "Sarı ağaç, reçine."},
    "Z": {"Ayakkabı Ağacı": "Tropikal, meyve."}
  },

  "gemstones": {
    "A": {"Ametist": "Mor kristal, kıymetli, şifalı.", "Akvamarin": "Mavi-yeşil, deniz berillium.", "Amber": "Koyu sarı, resine fosil, antik."},
    "B": {"Berilyum": "Yeşil kristal, kıymetli taş.", "Beyaz Safir": "Renksiz, kıymetli, sertlik."},
    "C": {"Garnet": "Kırmızı kristal, kıymetli taş.", "Silikon": "Renk kristal, değerli."},
    "D": {"Elmas": "Saydam kristal, en sert, kıymetli.", "Tanzanit": "Mavi-mor, nadir, kıymetli."},
    "E": {"Zümrüt": "Yeşil kristal, kıymetli taş."},
    "F": {"Fıruzeler": "Mavi yeşil, kıymetli, antik.", "Feldspat": "Kristal minerali, nadir."},
    "G": {"Granat": "Kırmızı kristal, kıymetli taş.", "Altın Quarz": "Sarı kristal, değerli."},
    "H": {"Akik": "Pembe kristal, kıymetli, yarı.", "Hematit": "Siyah kristal, mineral."},
    "I": {"Iyolit": "Mavi kristal, zafir-benzeri."},
    "J": {"Çöp": "Yeşil kristal, kıymetli taş."},
    "K": {"Kurnakite": "Mavi kristal, nadir.", "Korundüm": "Kırmızı-mavi, zafir, kıymetli."},
    "L": {"Labradorit": "Siyah irissan, nadir.", "Lazulit": "Mavi kristal, kıymetli."},
    "M": {"Magnetit": "Siyah minerali, manyetik.", "Malachit": "Yeşil striped, kıymetli.", "Merkür Kâfi": "Turquoise-green, değerli."},
    "N": {"Nefelit": "Sarı kristal, nadir.", "Safir": "Mavi kristal, kıymetli, sert."},
    "O": {"Onyx": "Siyah-beyaz, kıymetli taş.", "Opal": "Renkli ışık, kıymetli, nadir."},
    "P": {"Mercan": "Kırmızı, deniz, kıymetli.", "Perle": "Beyaz-krem, deniz hayvanı.", "Pirope": "Kırmızı granat, kıymetli."},
    "Q": {"Kuartz": "Saydam kristal, mineral, yaygın."},
    "R": {"Rübin": "Kırmızı kristal, kıymetli, sert.", "Rhodonit": "Pembe kristal, kıymetli taş."},
    "S": {"Safir": "Mavi kristal, kıymetli, sert.", "Sunstone": "Turuncu irissan, kıymetli.", "Serpentin": "Yeşil kristal, yar-değerli."},
    "T": {"Topas": "Sarı-mavi, kıymetli taş.", "Turkoaz": "Mavi-yeşil, kıymetli, antik.", "Tourmaline": "Siyah-yeşil, kıymetli taş."},
    "U": {"Uvarovit": "Yeşil granat, nadir."},
    "V": {"Vesuvan": "Sarı kristal, nadir."},
    "W": {"Willemit": "Yeşil kristal, nadir.", "Witherit": "Beyaz kristal, mineral."},
    "X": {"Xantophanit": "Sarı minerali, nadir."},
    "Y": {"Yeşil Turmalin": "Yeşil kristal, kıymetli.", "Yeşil Zafir": "Yeşil kristal, nadir."},
    "Z": {"Zirkon": "Saydam kristal, kıymetli, nadir."}
  },

  "dinosaurs": {
    "A": {"Ankilosaurus": "Zırh dinozouru, korungan kuyruk.", "Allosaurus": "Thropod, etçil, büyük."},
    "B": {"Brachiosaurus": "Sauropod, uzun boyun, dev.", "Triceratops": "Üç boynuzlu, herbivore, büyük."},
    "C": {"Compsognathus": "Küçük etçil, hızlı koşu.", "Ceratosaurus": "Boynuzlu etçil, güçlü."},
    "D": {"Dilophosaurus": "İki kresti, etçil, orta.", "Deinonychus": "Pençeli, akıllı avcı, hızlı."},
    "E": {"Iguanodon": "Erken herbivore, geniş.", "Euoplocephalus": "Zırhlı, korungan kuyruk."},
    "F": {"Fusuisaurus": "Sauropod, uzun, Asya.", "Fukuiraptor": "Hızlı avcı, pençeli."},
    "G": {"Gallimimus": "Tavuk-benzeri, hızlı, ot yiyen.", "Gigantosaurus": "Dev etçil, Allosaurus büyük."},
    "H": {"Herrerasaurus": "Erken etçil, hızlı avcı.", "Hypsilophodon": "Küçük herbivore, hızlı."},
    "I": {"Iguanodon": "Erken herbivore, geniş.", "Inklings": "Küçük avcı, yüzgeç-benzer."},
    "J": {"Janenschia": "Sauropod, Afrika, uzun."},
    "K": {"Kentrosaurus": "Zırhlı, plaka, Afrika."},
    "L": {"Lambeosaurus": "Başlı, kresti herbivore.", "Lesothosaurus": "Küçük herbivore, hızlı."},
    "M": {"Maiasaura": "Annesiz, bakım davranışı.", "Megalosaurus": "Büyük etçil, hızlı avcı."},
    "N": {"Nodosaurus": "Zırhlı, plaka-benzer.", "Nanotyrannus": "Küçük T-Rex benzeri."},
    "O": {"Ophthalmosaurus": "Ichthyosaur, deniz hayvanı.", "Ornitholestes": "Küçük avcı, ot yiyen."},
    "P": {"Parasaurolophus": "Başlı, sesli kresti.", "Plateosaurus": "Sauropod, erken, herbivore."},
    "Q": {"Qantassaurus": "Küçük herbivore, Avusturya."},
    "R": {"Rhabdodon": "Herbivore, erken, hızlı.", "Rugops": "Etçil, Afrika, kütlü."},
    "S": {"Stegosaurus": "Plaka-zırhlı, kuyruk silahı.", "Spinosaurus": "Üstün etçil, seritli sırt."},
    "T": {"Triceratops": "Üç boynuzlu, korungan, herbivore.", "Tyrannosaurus": "Büyük etçil, kral dinozor."},
    "U": {"Ultrasaurus": "Dev sauropod, uzun boyun."},
    "V": {"Velociraptor": "Hızlı pençeli avcı, zeki.", "Volkheimeria": "Sauropod, Arjantin."},
    "W": {"Wuerhosaurus": "Zırhlı, plaka, Çin."},
    "X": {"Xiaosaurus": "Küçük herbivore, Çin."},
    "Y": {"Yizhousaurus": "Sauropod, Çin, erken."},
    "Z": {"Zuniceratops": "Boynuzlu, erken herbivore, Amerika."}
  },

  "movies": {
    "A": {"Ayla": "Kore Savaşı fonunda geçen, gerçek bir hikayeden uyarlanan duygusal Türk filmi.", "Ahlat Ağacı": "Taşrada yazarlık hayali kuran bir gencin ailesiyle ve hayatla yüzleşmesini anlatır.", "Av Mevsimi": "Cinayet soruşturması etrafında ilerleyen, karanlık atmosferli polisiye dram.", "Aşk Tesadüfleri Sever": "Farklı dönemlerde kesişen hayatlar üzerinden ilerleyen romantik dram."},
    "B": {"Babam ve Oğlum": "12 Eylül sonrası bir ailenin kırgınlıklarını ve bağlarını anlatan güçlü dram.", "Bir Zamanlar Anadolu'da": "Anadolu gecesinde geçen uzun bir soruşturma üzerinden insan doğasını anlatır.", "Beynelmilel": "Sıkıyönetim döneminde bir kasaba bandosunun yaşadıklarını hicivle anlatır.", "Bu Son Olsun": "Mahalle dayanışması ve küçük insanların mücadelesini komedi-dram tonunda işler."},
    "C": {"Cenneti Beklerken": "Osmanlı minyatür sanatını merkeze alan dönem filmi.", "C Blok": "Kentli yalnızlık ve sınıfsal gerilimleri psikolojik bir dille ele alır.", "Cici": "Aile içi travmaların yıllar sonra yeniden yüzeye çıkışını anlatan modern dram."},
    "D": {"Düğün Dernek": "Bir düğün hazırlığının kontrolden çıkmasıyla gelişen popüler komedi.", "Dedemin İnsanları": "Mübadele sonrası kimlik, aidiyet ve aile hafızasını işleyen duygusal film.", "Devrim Arabaları": "Türkiye'nin ilk yerli otomobil girişiminin gerçek hikayesini anlatır.", "Dabbe": "Türkiye'de geçen, doğaüstü korku öğeleriyle tanınan yerli korku serisinin filmi."},
    "E": {"Eşkıya": "Yıllar sonra İstanbul'a dönen bir mahkumun geçmişiyle hesaplaşmasını anlatır.", "Ekşi Elmalar": "Doğu Anadolu'da geçen bir aile hikayesi üzerinden kuşak çatışmalarını işler.", "Eltilerin Savaşı": "Rekabet halindeki iki eltinin gündelik hayatını komedi diliyle anlatır.", "Ev Kira Semt Bizim": "Gençlik, dostluk ve mahalle yaşamı üzerine bağımsız bir şehir hikayesi."},
    "F": {"Fetih 1453": "İstanbul'un fethini büyük prodüksiyonla anlatan tarih temalı yerli film.", "Fakat Müzeyyen Bu Derin Bir Tutku": "Aşk, yalnızlık ve kent yaşamı üzerine kurulu şiirsel bir ilişki hikayesi."},
    "G": {"G.O.R.A": "Uzayda geçen absürt mizahı ve kült replikleriyle bilinen bilimkurgu komedisi.", "Güneşi Gördüm": "Göç, çatışma ve aile parçalanması temasını toplumsal bir dille ele alır.", "Geriye Kalan": "Vicdan, hırs ve sınıf farkları ekseninde ilerleyen psikolojik dram.", "Gemide": "Kapalı mekanda geçen, sert ve gerçekçi anlatımıyla öne çıkan kült film."},
    "H": {"Hababam Sınıfı": "Yaramaz öğrenciler ve okul hayatı üzerinden gelişen klasik Türk komedisi.", "Hokkabaz": "Baba-oğul ilişkisini ve sahne hayatını mizahla harmanlayan yol hikayesi.", "Her Şey Çok Güzel Olacak": "Yanlış anlaşılmalarla büyüyen olaylar zincirini anlatan şehir komedisi.", "Hükümet Kadın": "Anadolu'da geçen, kadın dayanışmasını öne çıkaran sıcak bir komedi."},
    "I": {"Issız Adam": "Modern şehir hayatında yakınlık ve yalnızlık temasını işleyen romantik dram.", "Ispanaktan Nağmeler": "Eski Yeşilçam döneminin müzikal-komedi tonunu taşıyan nostaljik yapım."},
    "J": {"Jilet": "Kayıp, öfke ve hayatta kalma duygularını sert bir gerçekçilikle anlatır.", "Jön Türk": "Siyasal ve kişisel hesaplaşmaları merkezine alan dönemsel bir yerli yapım."},
    "K": {"Kış Uykusu": "Kapadokya'da geçen, ahlak ve sınıf tartışmalarını derin diyaloglarla işleyen dram.", "Kelebeğin Rüyası": "İki genç şairin hastalık ve aşk arasında sıkışan hayatlarını anlatır.", "Karpuz Kabuğundan Gemiler Yapmak": "Sinemaya tutkun iki çocuğun taşrada kurduğu büyük hayalleri anlatır.", "Kurtlar Vadisi Irak": "Ortadoğu'da geçen politik-aksiyon anlatımıyla öne çıkan popüler film."},
    "L": {"Lal Gece": "Küçük bir odada geçen gecede gelenek, yaş farkı ve sessizlik üzerine kurulu dram.", "Labirent": "Terör soruşturması üzerinden ilerleyen yerli aksiyon-gerilim filmi.", "Limonata": "Aile içi sırlar ve kardeşlik duygusunu mizahla birleştiren yol filmi."},
    "M": {"Mucize": "Doğu'da bir köy okulunda geçen, umut ve eğitim temalı duygusal film.", "Müslüm": "Müslüm Gürses'in yaşamını anlatan biyografik müzik-drama yapımı.", "Mandıra Filozofu": "Tüketim karşıtı sade yaşam fikrini komediyle anlatan yerli film.", "Mavi Boncuk": "Yeşilçam döneminin eğlenceli ekip komedilerinden biri."},
    "N": {"Nefes Vatan Sağolsun": "Sınır karakolunda görev yapan askerlerin zorlu mücadelesini anlatır.", "Neşeli Günler": "Turşucu bir ailenin ayrılık ve yeniden birleşme hikayesini anlatan klasik komedi.", "Neredesin Firuze": "Müzik piyasası ve hayal kırıklıkları üzerine kurulu sıcak bir dram-komedi.", "Nuh Tepesi": "Baba-oğul çatışmasını taşra atmosferinde işleyen sakin tempolu dramatik film."},
    "O": {"Organize İşler": "İstanbul yeraltı dünyasında geçen çok karakterli suç-komedisi.", "Oflu Hoca'nın Şifresi": "Karadeniz mizahını taşıyan yerel karakter odaklı komedi filmi.", "Osman Pazarlama": "Küçük esnafın girişimcilik çabasını absürt mizahla anlatır."},
    "P": {"Pek Yakında": "Eski bir figüranın sinema aşkı etrafında gelişen sektör içi komedi.", "Propaganda": "Sınır çizgisiyle bölünen bir kasabada dostluk ve bürokrasi çatışmasını işler.", "Patron Mutlu Son İstiyor": "Senaryo yazarı ile yapımcı baskısı arasındaki yaratıcı çatışmayı anlatır.", "Pardon": "Yanlışlıkla hapse giren üç arkadaşın trajikomik adalet hikayesini anlatır."},
    "R": {"Recep İvedik": "Toplumsal tipler üzerinden ilerleyen, geniş kitlelere ulaşmış popüler komedi.", "Romantik Komedi": "Şehirli ilişkiler ve arkadaşlıklar etrafında kurulan romantik komedi filmi.", "Reis Bey": "Suç, adalet ve vicdan kavramlarını tartışan dramatik bir anlatı.", "Rıza": "Gündelik hayatta sıkışmış bir karakterin iç dünyasına odaklanan bağımsız film."},
    "S": {"Selvi Boylum Al Yazmalım": "Aşk ile emek arasındaki seçimi anlatan unutulmaz Yeşilçam klasiği.", "Süt Kardeşler": "Yanlış kimlikler ve konak karmaşası üzerine kurulu klasik Türk komedisi.", "Sivas": "Taşrada büyüme hikayesini çocuk ve köpek ilişkisi üzerinden anlatır.", "Sonbahar": "Hapisten çıkan bir adamın geçmişiyle hesaplaşmasını şiirsel bir dille işler."},
    "T": {"Tosun Paşa": "Aynı konağa talip ailelerin kimlik oyunlarını anlatan Yeşilçam klasiği.", "Takva": "İnanç, para ve güç ilişkisini bir müezzin karakteri üzerinden sorgular.", "Tamam mıyız?": "Engelli bir genç ile heykeltıraş bir adamın dostluğunu anlatan duygusal dram.", "Tatar Ramazan": "Mahalle adaleti ve güç mücadelesini merkezine alan dönem filmi."},
    "U": {"Uzak": "İstanbul'da aynı evde yaşayan iki akrabanın yabancılaşmasını anlatan ödüllü film.", "Umut": "At arabacısı bir adamın yoksulluk ve çıkış arayışını anlatan sinema klasiği.", "Uzun Hikaye": "Aile, göç ve zaman temalarını sade bir Anadolu hikayesiyle anlatır.", "Uçurtmayı Vurmasınlar": "Çocuk bakışıyla cezaevi hayatını anlatan etkileyici toplumsal dram."},
    "V": {"Vizontele": "Televizyonun bir Anadolu kasabasına gelişiyle değişen hayatları anlatır.", "Vavien": "Kara mizah tonunda, taşra hayatı ve aile gerilimlerini işleyen film.", "Veda": "Mustafa Kemal Atatürk'ün yakın çevresinden anlatılan biyografik dönem filmi.", "Ve Panayır Köyden Gider": "Taşrada değişen değerleri ve yalnızlığı şiirsel bir dille işler."},
    "Y": {"Yol": "12 Eylül sonrası izinli mahkumların yolculuğu üzerinden toplumsal gerçekçilik sunar.", "Yahşi Batı": "Osmanlı elçilerinin Vahşi Batı'ya düşmesini mizahla anlatan macera komedisi.", "Yazı Tura": "Askerlik sonrası travmalarla yaşamaya çalışan iki gencin hikayesini anlatır.", "Yozgat Blues": "Taşrada müzik yapmaya çalışan iki karakterin kırılgan yolculuğunu anlatır."},
    "Z": {"Züğürt Ağa": "Feodal düzenin çöküşüyle şehirde ayakta kalmaya çalışan bir ağayı anlatır.", "Zerre": "Yoksulluk ve kadın emeği üzerine güçlü bir toplumsal gerçekçi dramdır.", "Zübük": "Siyaset ve çıkar ilişkilerini taşlayan, unutulmaz bir hiciv örneğidir."}
  },

  "games": {
    "A": {"Atlaş": "Haritalama, keşif, puzzle.", "Assassin's Creed": "Suikast, tarih, aksiyon.", "Angry Birds": "Kuşlar, platformer, eğlence."},
    "B": {"Baldur's Gate": "Fantezi, RPG, stratejik.", "Bejeweled": "Taş, puzzle, kombinasyon.", "Bioshock": "Dystopya, FPS, hikaye."},
    "C": {"Civilization": "Stratejik, yönetimi, tarih.", "Crash Bandicoot": "Macera, platformer, klasik.", "Candy Crush": "Şeker, puzzle, eğlence."},
    "D": {"Diablo": "Karanlık, RPG, macera.", "Doom": "FPS, aksiyon, klasik.", "Donkey Kong": "Maymun, platformer, klasik."},
    "E": {"Elden Ring": "Fantezi, RPG, zor.", "Emulator": "Oyun, simülasyon, eski.", "Escape": "Kaçış, puzzle, gizem."},
    "F": {"Fortnite": "Battle Royale, aksiyon, popüler.", "Final Fantasy": "Fantezi, RPG, uzun.", "Fallout": "Post-apokaliptik, RPG, açık."},
    "G": {"Genshin Impact": "Fantezi, aksiyon, MMORPG.", "Grand Theft": "Suç, açık dünya, kontrovers.", "Grounded": "Macera, survival, çocuk."},
    "H": {"Hades": "Mitoloji, roguelike, hızlı.", "Half-Life": "Bilim, FPS, hikaye.", "Halo": "Uzay, FPS, aksiyon."},
    "I": {"Ico": "Platformer, atmosferleri, sanat.", "Infamous": "Süper güç, aksiyon, açık.", "Insomniac": "Aracı, oyun şirketi, dev."},
    "J": {"Jedi": "Star Wars, aksiyon, saç.", "Journey": "Sanat, keşif, emosyonel.", "Joust": "Arcade, atılı, klasik."},
    "K": {"Kingdom": "Stratejik, quests, fantezi.", "Kirby": "Pembe, platformer, Nintendo.", "Katakana": "Metin, RPG, Yapan."},
    "L": {"Lara Croft": "Arkeolog, macera, aksiyon.", "Legend": "Açık dünya, RPG, epik.", "Letterboxed": "Sözcük, puzzle, NYT."},
    "M": {"Minecraft": "Yapı, sandbox, yaratıcı.", "Mass Effect": "Scifi, RPG, tercih.", "Mario": "Platformer, Nintendo, klasik."},
    "N": {"No Man's Sky": "Uzay, keşif, sandbox.", "Notch": "Yaratıcı, blok, founder.", "Nier": "Aksiyon, hikaye, ilginç."},
    "O": {"Overwatch": "Şutörgün, takım, esports.", "Outer": "Uzay, RPG, hikaye.", "Origami": "Kağıt, puzzle, sanat."},
    "P": {"Pac-Man": "Arcade, maze, klasik.", "PlayStation": "Konsol, oyunlar, Sony.", "Persona": "RPG, okul, sosyal.", "Portal": "Puzzle, ağırlık, bilim."},
    "Q": {"Quest": "VR, oyunlar, macera.", "Quarry": "Korku, Hollywood, akıllı."},
    "R": {"Resident Evil": "Korku, survival, zombi.", "Red Dead": "Batı, açık dünya, aksiyon.", "Rift": "MMORPG, fantezi, online."},
    "S": {"Skyrim": "Fantezi, RPG, açık dünya.", "Starcraft": "RTS, stratejik, kompetitif.", "Sonic": "Hızlı, platformer, Sega.", "Splatoon": "Mürekkep, takım, Nintendo."},
    "T": {"Tetris": "Blok, puzzle, klasik.", "The Witcher": "Fantezi, RPG, hikaye.", "Team": "Taktik, aksiyon, şutörgün."},
    "U": {"Uncharted": "Macera, aksiyon, PlayStation.", "Unreal": "Motor, grafik, oyun."},
    "V": {"Valorant": "Taktik, şutörgün, esports.", "Vagrant": "RPg, hikaye, retro.", "VR": "Sanal, gerçeklik, teknoloji."},
    "W": {"Warcraft": "Fantezi, RTS, online.", "Wii": "Konsol, hareket, Nintendo.", "Wordle": "Sözcük, puzzle, popüler."},
    "X": {"Xbox": "Konsol, oyunlar, Microsoft.", "X-Men": "Mutant, aksiyon, Marvel."},
    "Y": {"Yoshi": "Dinozor, platformer, Nintendo.", "Yakuza": "Suç, aksiyon, Japonya."},
    "Z": {"Zelda": "Fantezi, macera, Nintendo.", "Zenith": "Tepe, aksiyon, arcade."}
  },

  "tvshows": {
    "A": {"Altın Kız": "Aile, komedi, Türk.", "Ameliyathane": "Tıp, dramatik, sağlık.", "Avengers": "Süper, dramatik, marve."},
    "B": {"Breaking Bad": "Suç, dramaturji, serisi.", "Başkan": "Politik, dramatik, güncel.", "Banshee": "Korku, dramatik, fantezi."},
    "C": {"Crown": "Kraliçe, dramatik, İngiltere.", "Chernobyl": "Nükleer, tarih, dramatik.", "Community": "Komedi, okul, grup."},
    "D": {"Doctor Who": "Scifi, zamana, İngiliz.", "Downton": "Tarihi, dramatik, İngiltere.", "Dark": "Gizem, scifi, zaman."},
    "E": {"Everyone": "Komedi, aile, dinamik.", "Euphoria": "Genç, dramatik, gerçekçi.", "Empire": "Suç, musik, dramatik."},
    "F": {"Friends": "Komedi, arkadaş, klasik.", "Fleabag": "Komedi, kadın, İngiltere.", "Fringe": "Scifi, paranormal, aksiyon."},
    "G": {"Game of Thrones": "Fantezi, epik, dramatik.", "Gangsta": "Suç, dramatik, Tokyo.", "Golden": "Yaşlı, komedi, kadın."},
    "H": {"House": "Tıp, gizem, doktor.", "Homeland": "Casus, gerilim, politik.", "Hannibal": "Gerilim, cinaye, psiko."},
    "I": {"Içinde": "Ruh, dramatik, İtalya.", "Insomnia": "Gerilim, cinaye, İskandinavya."},
    "J": {"Jeopardy": "Yarışma, bilgi, soru.", "Jericho": "Post-apokaliptik, dramatik, scifi.", "Justified": "Batı, suç, drama."},
    "K": {"Killing Eve": "Gerilim, psiko, İngiltere.", "Kardashian": "Reality, aile, sosyal.", "Kingdom": "Korku, zombie, Koreli."},
    "L": {"Lucifer": "Süper, komedi, fantezi.", "Lost": "Scifi, gizem, ada.", "Lovecraft": "Korku, scifi, Kosmik."},
    "M": {"Money Heist": "Suç, heist, İspanya.", "Mindhunter": "Suç, polis, tarih.", "Modern Family": "Komedi, aile, dinamik."},
    "N": {"Narcos": "Suç, uyuşturucu, dramatik.", "Night Gallery": "Korku, müze, klasik.", "Norwegian": "Suç, drama, İskandinavya."},
    "O": {"Orange": "Ceza, dramatik, feminist.", "Ozark": "Suç, para, dramatik.", "Orphan": "Bilim, thriller, nasıl."},
    "P": {"Peaky": "Suç, İngiltere, tarih.", "Prestige": "Sihir, dramatik, ilginç.", "Parks": "Komedi, hükümet, kariyer."},
    "Q": {"Queen's Gambit": "Satranç, dramatik, biyografi.", "Quantum": "Scifi, fizik, belgesel."},
    "R": {"Riverdale": "Gizem, çocuk, dramatik.", "Russian": "Casus, gerilim, tarih.", "Righteous": "Suç, dramatik, Kore."},
    "S": {"Stranger Things": "Scifi, paranormal, genç.", "Succession": "Şirket, dramatik, politik.", "Sherlock": "Gizem, polis, Londra.", "Sopranos": "Suç, dramatik, mafya."},
    "T": {"True": "Suç, gizem, dramatik.", "The Office": "Komedi, iş, dokumenter.", "Twin": "Gizem, korku, garip.", "Tuzak": "Gerilim, hukuk, thriller."},
    "U": {"Umbrella": "Süper, dramatik, fantezi.", "Unbreakable": "Suç, gerilim, korku."},
    "V": {"Vikings": "Savaş, tarih, macera.", "Veep": "Politik, komedi, satirik.", "Vampire": "Korku, paranormal, romantik."},
    "W": {"Westworld": "Scifi, dramatik, İncik.", "West": "Batı, suç, tarih.", "White": "Suç, kemya, uyuşturucu.", "Wiseman": "Coğrafya, şaman, belgesel."},
    "X": {"X-Files": "Scifi, paranormal, FBI."},
    "Y": {"Yellowstone": "Batı, dramatik, aile.", "Young": "Yönetim, dramatik, hukuk.", "You": "Thriller, obsesyon, Netflix."},
    "Z": {"Zodiac": "Gerilim, cinaye, serial.", "Zone": "Scifi, paranormal, gizem."}
  },

  "superheroes": {
    "A": {"Aquaman": "Su, Atlantis, merfolk.", "Ant-Man": "Küçülme, heist, komedi.", "Arrow": "Okçuluk, vigilante, CW."},
    "B": {"Batman": "Maskeleme, Gotham, dışı.", "Black Panther": "Afrika, kraliçe, Wakanda.", "Blade": "Vampir, avcı, aksiyon."},
    "C": {"Captain America": "Asker, serum, lider.", "Captain Marvel": "Uzay, kadın, güç.", "Cyborg": "Robota, teknik, DC."},
    "D": {"Deadpool": "Kurgu, anti-kahraman, komedi.", "Doctor Strange": "Doktor, sihir, multiverse.", "Daredevil": "Kör, çadır, Hell."},
    "E": {"Elektra": "Kadın, ninaja, dövüş.", "Emerald": "Yeşil, enerjilii, DC.", "Eternals": "Kozmik, tanrı, Marvel."},
    "F": {"Flash": "Hız, çiftli, DC.", "Fantastic": "Dörtte, biliim, Marvel.", "Firestar": "Enerji, kadın, Marvel."},
    "G": {"Green Goblin": "Kötü, kurşun, sinema.", "Green Lantern": "Yüzük, yeşil, DC.", "Gambit": "Okçu, karşı, Marvel."},
    "H": {"Hawkeye": "Okçuluk, Avcı, Marvel.", "Hulk": "Yeşil, güç, kahraman.", "Hellblazer": "Büyü, kahraman, DC."},
    "I": {"Ironman": "Zırh, milyarder, Marvel.", "Ink": "Mürekkep, seviye, DC.", "Iceman": "Buz, mutant, Marvel."},
    "J": {"Judge Dredd": "Adalet, düzeni, comic.", "Javelin": "Silah, anti, DC.", "Jean": "Psikik, Cadın, X-Men."},
    "K": {"Kickass": "Sıradan, hero, komedi.", "Kaine": "İnsan, örümcek, kloni."},
    "L": {"Lone Wolf": "Tekli, batı, kahraman.", "Loki": "Trickster, Tanrı, Marvel.", "Luke Cage": "Adamanta, kafes, Marvel."},
    "M": {"Mister Fantastic": "Elastik, bilim, Marvel.", "Moon Knight": "Ay, ruh, Marvel.", "Magneto": "Manyetik, mutant, X-Men.", "Mystique": "Şekil, kamuflaj, X-Men."},
    "N": {"Nightwing": "Çadır, genç, DC.", "Nova": "Uzay, enerji, Marvel."},
    "O": {"Omni-Man": "Uzay, güçlü, İmmortal.", "Ozai": "Kötü, kahraman, üretim."},
    "P": {"Professor X": "Psikik, lider, X-Men.", "Power": "Kimya, güçlü, Marvel.", "Punisher": "Tefek, intikam, Marvel."},
    "Q": {"Quasar": "Uzay, yüzük, Marvel.", "Question": "Gizem, maskeleme, DC."},
    "R": {"Raven": "Emare, korku, DC.", "Red Robin": "İkinci, genç, DC.", "Rocket": "Hayvan, macetim, Marvel.", "Rogue": "Dokunma, kahraman, X-Men."},
    "S": {"Spider-Man": "Örümcek, genç, Marvel.", "Superman": "Kryptonian, güç, DC.", "Storm": "Hava, kadın, X-Men.", "Scarlet": "Kırmızı, psikik, Marvel."},
    "T": {"The Flash": "Hız, çiftlik, DC.", "Thor": "Tanrı, çekiç, Marvel.", "The Hulk": "Yeşil, dönüşüm, Marvel.", "Thanos": "Titan, kötü, Marvel."},
    "U": {"Ultimates": "Takım, Marvel, güç."},
    "V": {"Vision": "Robot, yapılan, Marvel.", "Venom": "Simbiont, örümcek, anti.", "Vulture": "Yaşlı, suç, Spider."},
    "W": {"Wolverine": "Tırnak, pençe, X-Men.", "Wonder Woman": "Kadın, tanrı, DC.", "Wasp": "Arı, küçülme, Marvel.", "Winter Soldier": "Asker, kontrolü, Marvel."},
    "X": {"X-Men": "Mutant, takım, Marvel."},
    "Y": {"Yellow": "Sarı, renk, kahraman.", "Yamcha": "Enerji, savaş, DBZ."},
    "Z": {"Zatanna": "Büyü, kadın, DC.", "Zoom": "Hız, kötü, DC."}
  },

  "mythology": {
    "A": {"Athena": "Bilgi, savaş, Yunan tanrıçası.", "Apollo": "Güneş, müzik, Yunan.", "Ares": "Savaş, kötü, Yunan tanrısı."},
    "B": {"Bakaura": "Ruh, guam, yöresel.", "Bor": "Dev, savaş, Nordik."},
    "C": {"Charon": "Ferryman, Ölüm, Yunan.", "Centaur": "Yarım insan, yarım at.", "Cernunnos": "Boynuz, doğa, Celtic."},
    "D": {"Demeter": "Ürün, mevsim, Yunan.", "Dagon": "Balık, tanrı, Lovecraft.", "Dryad": "Ağaç, ninfa, Yunan."},
    "E": {"Eris": "Ayrılık, savaş, Yunan.", "Eros": "Aşk, okçu, Yunan.", "Erinyes": "İntikam, furia, Yunan."},
    "F": {"Fafnir": "Ejder, altın, Nordik.", "Fenrir": "Kurt, Kıyametgün, Nordik.", "Frost": "Dev, buz, Nordik."},
    "G": {"Gaia": "Yeryüzü, tanrıçası, Yunan.", "Grendel": "Canavar, kötü, İngiliz.", "Gwyn": "Tanrı, Walian, Celtic."},
    "H": {"Hades": "Ölüm, cehennem, Yunan.", "Hecate": "Büyü, üç yol, Yunan.", "Heimdall": "Köprü, bekçi, Nordik.", "Hermes": "Messenger, soyguncu, Yunan."},
    "I": {"Iris": "Gökkuşak, messenger, Yunan.", "Ixion": "Tekerlekli, işkence, Yunan."},
    "J": {"Jormungandr": "Yılan, Kıyametgün, Nordik.", "Jotun": "Dev, Nordik mitolojisi."},
    "K": {"Kronos": "Zaman, titan, Yunan.", "Kali": "Yıkım, tanrıçası, Hindu."},
    "L": {"Loki": "Trickster, tanrı, Nordik.", "Ladon": "Ejder, altın elma, Yunan.", "Lernean": "Hydra, canavar, Yunan."},
    "M": {"Medusa": "Canavar, yılan, Yunan.", "Morrigan": "Ruh, savaş, Celtic.", "Minotaur": "Boğa, canavar, Yunan."},
    "N": {"Nike": "Zafer, tanrıçası, Yunan.", "Nemesis": "İntikam, adalet, Yunan.", "Norns": "Yazı, tanrıçalar, Nordik."},
    "O": {"Odin": "Bilgi, savaş, Nordik.", "Orpheus": "Müzik, aşk, Yunan.", "Oreades": "Dağ, ninfalar, Yunan."},
    "P": {"Poseidon": "Deniz, tanrısı, Yunan.", "Persephone": "Mevsim, kaçırılan, Yunan.", "Phoenix": "Ateş, yeniden doğan, mitoloji.", "Pegasus": "Kanat, at, Yunan."},
    "Q": {"Quetzalcoatl": "Serpent, Aztec, tanrı."},
    "R": {"Ra": "Güneş, tanrısı, Mısır.", "Rhea": "Titan, tanrıçası, Yunan.", "Ragnarok": "Sınıf, kıyamet, Nordik."},
    "S": {"Styx": "Ölüm, nehir, Yunan.", "Siren": "Canavar, ses, Yunan.", "Sphinx": "Canavar, bilmece, Mısır.", "Sleipnir": "At, sekiz bacak, Nordik."},
    "T": {"Thoth": "Bilge, Ibis, Mısır.", "Tartarus": "Cezaevi, cehennem, Yunan.", "Thanatos": "Ölüm, tanrısı, Yunan.", "Thor": "Gök gürültü, çekiç, Nordik."},
    "U": {"Uranus": "Gökyüzü, titan, Yunan."},
    "V": {"Valkyrie": "Savaş, maiden, Nordik.", "Vortumnus": "Dönüştürme, Romen."},
    "W": {"Wyvern": "Ejder, canavar, mitoloji."},
    "X": {"Xipe Totec": "Koruma, Aztec tanrısı."},
    "Y": {"Yama": "Ölüm, tanrısı, Hindu."},
    "Z": {"Zephyrus": "Rüzgar, tanrısı, Yunan.", "Zeus": "Gök, Tanrı, Yunan."}
  },

  "history": {
    "A": {"Abraham Lincoln": "Başkan, emancipation, assassinasyon.", "Alexander the Great": "Conqueror, Macedon, imperium.", "Areheologis": "İnsan, eski, bilimi."},
    "B": {"Benjamin Franklin": "Bilimci, yazarı, Amerikan.", "Bathory Elizabeth": "Güzellik, vampir, legende.", "Bonaparte": "Komutan, imparatorluk, Fransa."},
    "C": {"Cleopatra": "Mısır kraliçesi, Caesar, entrika.", "Christopher Columbus": "Navigator, keşif, Amerika.", "Constantine": "İmparator, hristiyanlık, Roma."},
    "D": {"Thomas Jefferson": "Başkan, Deklarasyon, Amerika.", "Dante": "Şair, Cenneti, İtalya.", "Diogenes": "Felsefeci, sinik, Yunan."},
    "E": {"Elizabeth I": "Kraliçe, İngiltere, gücü.", "Erasmus": "İnsanist, reform, Hollanda.", "Eiffel Gustave": "Mühendis, kuleleri, Fransa."},
    "F": {"Frederick the Great": "Kral, Prusya, Aydınlanma.", "Florence Nightingale": "Hemşire, tıp, reformist.", "Franklin Delano": "Başkan, New Deal, krizleri."},
    "G": {"Genghis Khan": "Conqueror, Moğol, imperium.", "Galileo": "Astronomist, teleskop, bilim.", "Goebbels": "Propagandist, Nazi, suç."},
    "H": {"Hippocrates": "Doktor, antik, yemini.", "Henry VIII": "Kral, evlilik, İngiltere.", "Hitler Adolf": "Diktatör, Nazi, soykırım."},
    "I": {"Joan of Arc": "Kutsal, Maid, Fransa.", "Isaac Newton": "Fizikçi, kanunlar, gravity."},
    "J": {"Julius Caesar": "Komutan, Roma, devlet.", "John Smith": "Erkebei, Virginya, Pocahontas.", "Joan Robinson": "İktisat, kadın, teori."},
    "K": {"Kemal Atatürk": "Kurucular, Türkiye, reformist.", "Karl Marx": "Felsefeci, Komünizm, teorist.", "Kamehameha": "Kral, Hawaiki, birlik."},
    "L": {"Leonardo da Vinci": "Sanatçı, mühendis, ilhamlı.", "Lenin": "Komünist, Rusya, devrim.", "Marie Antoinette": "Kraliçe, Fransa, İdam."},
    "M": {"Martin Luther King": "Pastor, hak, sivil.", "Michelangelo": "Sanatçı, David, Sistine.", "Montezuma": "Kral, Aztec, Cortez."},
    "N": {"Napoleon": "Komutan, Fransa, işgal.", "Neferiti": "Kraliçe, Mısır, güzellik.", "Newton Isaac": "Fizikçi, kanunlar, gravitas."},
    "O": {"Oliver Cromwell": "Diktatör, İngiltere, Puritan.", "Oppenheimer": "Fizikçi, bomba, atom."},
    "P": {"Plato": "Felsefeci, Yunan, ideaları.", "Peter the Great": "Kral, Rusya, reformist.", "Pericles": "Atina, demokrasi, lider."},
    "Q": {"Qin Shi Huang": "İmparator, Çin, ölüm."},
    "R": {"Robespierre": "Diktatör, Fransa, terör.", "Richard the Lionheart": "Kral, İngiltere, crusade.", "Rosa Parks": "Aktivist, hak, sivil."},
    "S": {"Socrates": "Felsefeci, Yunan, yöntemi.", "Sojourner Truth": "Aktivist, kadın, özgürlük.", "Stalin": "Diktatör, Sovyetler, gerilim.", "Shakespeare William": "Şair, oyunlara, edebiyat."},
    "T": {"Thomas Edison": "İcatçı, ışık, elektrik.", "Tolstoy": "Yazar, savaş, barış.", "Tahun Okdak": "Tarih, Tatar, lider."},
    "U": {"Ulysses Grant": "Komutan, Amerika, başkan."},
    "V": {"Vincent van Gogh": "Sanatçı, başak, şalter.", "Vesalius": "Doktor, anatomi, bilim.", "Victoria Kraliçe": "Monark, İngiltere, imparatorluk."},
    "W": {"Winston Churchill": "Başbakan, İngiltere, savaş.", "Wiliam Shakespeare": "Şair, oyunlar, edebiyat.", "Wallenstein": "Komutan, savaş, 30 yıl."},
    "X": {"Xunzi": "Felsefeci, Çin, insan."},
    "Y": {"Yuri Gagarin": "Kozmonot, uzay, ilk."},
    "Z": {"Zeno": "Felsefeci, Yunan, paradoks.", "Zheng He": "Navigator, Çin, çıkış."}
  },

  "dances": {
    "A": {"Aerobics": "Spor, ritim, kardiyak.", "Acro": "Akrobat, hava, dans.", "Angloball": "İngiliz, sosyal, klasik."},
    "B": {"Ballet": "Klasik, tutular, parmak.", "Breakdancing": "Sokak, hip-hop, hızlı.", "Bolero": "İspanyol, sosyal, romantik."},
    "C": {"Capoeira": "Brezilya, savaş, tarih.", "Cha-Cha": "Latin, sosyal, triplet.", "Cheerleading": "Pompon, takım, hızlı."},
    "D": {"Disco": "Gece, müzik, dans.", "Danza": "İspanyol, sosyal, parça.", "Darwali": "Hindistan, sosyal, çift."},
    "E": {"Electro": "Modern, elektronik, hızlı.", "Eğriçeli": "Türk, sosyal, halk.", "Escrima": "Filipin, savaş, kolo."},
    "F": {"Flamenco": "İspanyol, dramatik, hızlı.", "Foxtrot": "Sosyal, standart, hızlı.", "Freestyle": "Modern, yaratıcı, şahsi."},
    "G": {"Gangana": "Hindistan, klasik, mudra.", "Gumboot": "Afrika, perkusyonlu, hızlı.", "Gaita": "Sosyal, İspanya, ritim."},
    "H": {"Hip-Hop": "Sokak, modern, müzik.", "Hora": "Yahudi, sosyal, çember.", "Hula": "Hawaiki, tradisyonelı, sallantı."},
    "I": {"Irish": "İrlanda, sağlam, ayak.", "Interpretive": "Sanat, emosyonel, özgür.", "Icelandic": "İzland, halk, sosyal."},
    "J": {"Jailhouse": "Ceza, müzik, grup.", "Jive": "Latin, hızlı, sosyal.", "Jazz": "Müzik, modern, stil."},
    "K": {"Kathak": "Hindistan, klasik, hikaye.", "Kolo": "Balkan, sosyal, çember.", "Krumping": "Sokak, modern, intens."},
    "L": {"Lindy Hop": "Swing, sosyal, hızlı.", "Latin": "Sosyal, ritim, çift.", "Lezginka": "Kafkasya, geleneksel, hızlı."},
    "M": {"Mambo": "Küba, Latin, ritim.", "Merengue": "Dominikana, Latin, çift.", "Mackrume": "Hindistan, klasik, hareket.", "Moonwalk": "Modern, Michael Jackson, stil."},
    "N": {"Nobility": "Klasik, formal, lider.", "Neck": "Sokak, modern, stil.", "Nigerian": "Afrika, halk, ritim."},
    "O": {"Oryantal": "Ortadoğu, gövde, kadın.", "Odori": "Japon, klasik, takım.", "Orchestral": "Canlı, formal, müzik.", "Oyun Havası": "Türk düğünlerinde çalınan neşeli müzikle oynanan geleneksel dans."},
    "P": {"Paso Doble": "İspanyol, sosyal, savaş.", "Polka": "Orta Avrupa, hızlı, sosyal.", "Punta": "Garifuna, sosyal, hızlı.", "Pelvic": "Modern, sağlık, hareket."},
    "Q": {"Quickstep": "Sosyal, standart, hızlı.", "Qwali": "Sufi, müzik, ritim."},
    "R": {"Rhumba": "Küba, Latin, romantik.", "Rumba": "Sosyal, slow, çift.", "Riverdance": "İrlanda, hızlı, takım."},
    "S": {"Salsa": "Küba, Latin, çift.", "Samba": "Brezilya, Karnaval, ritim.", "Swing": "Çağdaş, sosyal, hızlı.", "Square": "Amerikan, sosyal, caller."},
    "T": {"Tango": "Arjantin, dramatik, çift.", "Tap": "Amerikan, ritim, ayak.", "Tarantella": "İtalyalı, hızlı, sosyal."},
    "U": {"Uptown": "Modern, sokak, stil."},
    "V": {"Valsez": "Sosyal, standart, hızlı.", "Vogue": "Sokak, modern, pose."},
    "W": {"Waltz": "Viyana, sosyal, hızlı.", "Wili": "Bale, romantik, fantezi.", "West": "Amerikan, sosyal, sosyal.", "Waltz Türk": "Batı etkisiyle Türk toplumuna giren üç zamanlı zarif bir dans."},
    "X": {"Xinjiang": "Çin, halk, müzik.", "Xango Dansı": "Afrika kökenli ritüel bir dans, ateş ve ritimle yapılır."},
    "Y": {"Yorkshire": "İngiltere, halk, sosyal."},
    "Z": {"Zumba": "Latin, fitness, hızlı.", "Zambra": "İspanyol, romantik, dans."}
  }
};

