const CATEGORIES_TR = {
  fruits:      'Meyveler',
  animals:     'Hayvanlar',
  cities:      'Dünya Şehirleri',
  foods:       'Yemekler',
  vegetables:  'Sebzeler',
  sports:      'Sporlar',
  instruments: 'Müzik Aletleri',
  occupations: 'Meslekler',
  birds:       'Kuşlar',
  flowers:     'Çiçekler',
  trees:       'Ağaçlar',
  gemstones:   'Değerli Taşlar',
  dinosaurs:   'Dinozorlar',
  movies:      'Turk Filmleri',
  games:       'Video Oyunları',
  tvshows:     'Diziler',
  superheroes: 'Süper Kahramanlar',
  mythology:   'Mitolojik Figürler',
  history:     'Tarihi Kişiler',
  dances:      'Danslar',
};

const WORDS_TR = {
  fruits: {
    A: ['Armut', 'Ananas', 'Avokado', 'Acai', 'Adi Kivi', 'Asya Armudı', 'Atemoya', 'Acerola', 'Ambarella', 'Araza'],
    B: ['Muz', 'Yaban Mersini', 'Böğürtlen', 'Boysenberry Türü', 'Ekmek Meyvesi', 'Kanlı Portakal', 'Bael', 'Bilberry Türü', 'Acı Portakal', 'Barbadine'],
    C: ['Kiraz', 'Hindistan Cevizi', 'Turna Yemişi', 'Karavun', 'Klementini', 'Frenk Üzümü', 'Cherimoya', 'Calamondin', 'Bulut Böğürtleni', 'Capulin'],
    D: ['Ejder Meyvesi', 'Durian', 'Hurma', 'Damson Ericek', 'Dew Berry Türü', 'Çöl Limonu', 'Duku'],
    E: ['Mürver Meyvesi', 'Emblica', 'Etrog', 'Entawak'],
    F: ['İncir', 'Feijoa', 'Parmak Limonu', 'Fuyu Persimonu', 'Yalancı Mastik'],
    G: ['Üzüm', 'Guava', 'Greyfurt', 'Muşmula', 'Greengage Ericek', 'Grumichama', 'Gamboge', 'Gac Meyvesi'],
    H: ['Sarı Kavun', 'Huckleberry Türü', 'Hackberry Meyvesi', 'Boynuzlu Kavun'],
    I: ['Ilama', 'Hint Ericek', 'Imbe', 'Buz Elması', 'Inga Meyvesi'],
    J: ['Jack Meyvesi', 'Jujube', 'Jaboticaba', 'Java Ericek', 'Jocote', 'Jobo'],
    K: ['Kivi', 'Kumkuat', 'Kiwano', 'Kaki', 'Kaffir Limonu', 'Kei Elması'],
    L: ['Limon', 'Yeşil Limon', 'Lychee', 'Longan', 'Loganberry Türü', 'Langsat', 'Lucuma', 'Limequat'],
    M: ['Mango', 'Kavun', 'Dut', 'Mandalina', 'Maracuja', 'Mamey', 'Marula', 'Mucize Meyvesi'],
    N: ['Şeftali', 'Noni', 'Naranjilla', 'Natal Ericek', 'Nance'],
    O: ['Portakal', 'Zeytin', 'Ortanique', 'Osage Portakalı', 'Orangelo'],
    P: ['Şeftali', 'Armut', 'Ananas', 'Eriş', 'Nar', 'Papaya', 'Tutku Meyvesi', 'Persimonu', 'Pawpaw', 'Pitaya'],
    Q: ['Ayva', 'Quenepa', 'Queensland Ericek', 'Quandong'],
    R: ['Ahududu', 'Rambutan', 'Kırmızı Frenk Üzümü', 'Gül Elması', 'Rollinia', 'Riberry'],
    S: ['Çilek', 'Yıldız Meyvesi', 'Sapodilla', 'Asitli Elma', 'Şeker Elması', 'Salak', 'Santol'],
    T: ['Tanerin', 'Tamarind', 'Domates', 'Tamarillo', 'Tangelo', 'Tayberry Türü'],
    U: ['Ugli Meyvesi', 'Ugni', 'Ayı Üzümü'],
    V: ['Valensiya Portakalı', 'Voavanga', 'Vanilya Fasulyesi'],
    W: ['Karpuz', 'Kurt Böğürtleni', 'Wampee', 'Beyaz Frenk Üzümü', 'Vahşi Çilek'],
    X: ['Xigua Kavunu', 'Ximenia', 'Xoconostle'],
    Y: ['Yuzu', 'Sarı Tutku Meyvesi', 'Yangmei', 'Sarı Eriş', 'Yumberry'],
    Z: ['Ziziphus', 'Zhe'],
  },

  animals: {
    A: ['Timsah', 'Antilop', 'Armadillo', 'Karınca Ayısı', 'Alpaka', 'Anakonda', 'Aksolotl', 'Aye-aye', 'Afrika Yaban Köpeği'],
    B: ['Ayı', 'Manda', 'Babun', 'Bizon', 'Yarasa', 'Kunduz', 'Binturong', 'Yaban Domuzu', 'Bongo', 'Mavi Balina'],
    C: ['Çita', 'Timsah', 'Deve', 'Kobra', 'Şempanze', 'Çakal', 'Karakulak', 'Kapibara', 'Çinçilla'],
    D: ['Geyik', 'Yunus', 'Dingo', 'Eşek', 'Dhole', 'Dugong', 'Dik-dik'],
    E: ['Fil', 'Elk', 'Emu', 'Ekidne', 'Kakım'],
    F: ['Tilki', 'Kurbağa', 'Turna', 'Flamingo', 'Şahin', 'Uçan Sincap', 'Balık Kedisi'],
    G: ['Goril', 'Zürafa', 'Kertenkele', 'Ceylan', 'Keçi', 'Gemsbok', 'Dev Karınca Yılanı', 'Gri Kurt'],
    H: ['Su Aygırı', 'At', 'Hiena', 'Hamster', 'Kirpi', 'Hartebeest', 'Tavşan'],
    I: ['Iguana', 'İmpala', 'Ibis', 'Indri'],
    J: ['Jaguar', 'Denizanası', 'Çakal', 'Japon Makakal'],
    K: ['Kanguru', 'Koala', 'Komodo Ejderi', 'Kinkajou', 'Kudu'],
    L: ['Aslan', 'Leopar', 'Lama', 'Vaşak', 'Lemur', 'Liger', 'Loris'],
    M: ['Maymun', 'Geyik', 'Surikat', 'Fare', 'Mangust', 'Manatee', 'Marten', 'Markhor'],
    N: ['Narval', 'Newt', 'Numbat', 'Nil Monitörü'],
    O: ['Orangutan', 'Deve Kuşu', 'Su Samuru', 'Ahtapot', 'Baykuş', 'Ocelot', 'Oryx'],
    P: ['Panda', 'Penguen', 'Puma', 'Pantera', 'Platypus', 'Kirpi', 'Proboscis Makakalı', 'Pangolin'],
    Q: ['Quokka', 'Quoll', 'Kuetzal Kuşu', 'Quahog'],
    R: ['Tavşan', 'Gergedan', 'Rakun', 'Çıngıraklı Yılan', 'Kırmızı Panda', 'Çift Kuyruklu Lemur'],
    S: ['Yılan', 'Köpekbalığı', 'Tembel', 'Fok Balığı', 'Sincap', 'Kar Leoparı', 'Serval', 'Semender'],
    T: ['Kaplan', 'Kaplumbağa', 'Tapir', 'Tukan', 'Tasmanya Canlısı', 'Tarsier', 'Tamarin'],
    U: ['Uakari', 'Urial', 'Deniz Kestanesi'],
    V: ['Akbaba', 'Viper', 'Vicuna', 'Vervet Makakalı'],
    W: ['Kurt', 'Balina', 'Wombat', 'Mors Balığı', 'Gelincik', 'Wolverine', 'Wildebeest'],
    X: ['Xerus', 'Xenops', 'Röntgen Balığı'],
    Y: ['Yak', 'Sarı Mangust', 'Yacare Timsahı', 'Yabby'],
    Z: ['Zebra', 'Zebu', 'Zorilla'],
  },

  cities: {
    A: ['Amsterdam', 'Athens', 'Auckland', 'Ankara', 'Accra', 'Algiers', 'Abu Dhabi', 'Almaty', 'Amman', 'Addis Ababa'],
    B: ['Barcelona', 'Bangkok', 'Buenos Aires', 'Berlin', 'Beijing', 'Brussels', 'Bogota', 'Beirut', 'Bucharest', 'Bangalore'],
    C: ['Cairo', 'Chicago', 'Copenhagen', 'Casablanca', 'Cape Town', 'Colombo', 'Caracas', 'Calgary', 'Chisinau'],
    D: ['Dubai', 'Delhi', 'Dublin', 'Dhaka', 'Detroit', 'Dakar', 'Doha', 'Damascus'],
    E: ['Edinburgh', 'Entebbe', 'El Paso', 'Essen'],
    F: ['Florence', 'Frankfurt', 'Fuzhou', 'Freetown'],
    G: ['Geneva', 'Glasgow', 'Guangzhou', 'Guadalajara', 'Gothenburg', 'Gaza'],
    H: ['Hong Kong', 'Havana', 'Hamburg', 'Helsinki', 'Hanoi', 'Harare', 'Houston'],
    I: ['Istanbul', 'Islamabad', 'Izmir', 'Indianapolis'],
    J: ['Jakarta', 'Jerusalem', 'Johannesburg', 'Jaipur', 'Jeddah'],
    K: ['Karachi', 'Kyoto', 'Kuala Lumpur', 'Kinshasa', 'Kathmandu', 'Kabul', 'Kiev'],
    L: ['London', 'Los Angeles', 'Lima', 'Lisbon', 'Lagos', 'Lyon', 'Lahore', 'Luanda'],
    M: ['Madrid', 'Moscow', 'Mumbai', 'Montreal', 'Melbourne', 'Manila', 'Milan', 'Minsk'],
    N: ['New York', 'Nairobi', 'Naples', 'New Delhi', 'Nagoya', 'Nicosia'],
    O: ['Oslo', 'Ottawa', 'Osaka', 'Odessa', 'Ouagadougou'],
    P: ['Paris', 'Prague', 'Perth', 'Philadelphia', 'Porto', 'Panama City', 'Phnom Penh'],
    Q: ['Quebec City', 'Quito', 'Quezon City'],
    R: ['Rome', 'Rio de Janeiro', 'Rotterdam', 'Riyadh', 'Reykjavik', 'Rabat'],
    S: ['Sydney', 'Seoul', 'Singapore', 'Stockholm', 'Shanghai', 'Santiago', 'San Francisco'],
    T: ['Tokyo', 'Toronto', 'Tehran', 'Tel Aviv', 'Taipei', 'Tashkent', 'Tunis'],
    U: ['Ulaanbaatar', 'Utrecht', 'Ufa', 'Ushuaia'],
    V: ['Vienna', 'Vancouver', 'Venice', 'Vilnius', 'Vladivostok', 'Valletta'],
    W: ['Warsaw', 'Washington DC', 'Wellington', 'Winnipeg', 'Wuhan'],
    X: ["Xi'an"],
    Y: ['Yokohama', 'Yangon', 'Yerevan', 'Yaounde'],
    Z: ['Zurich', 'Zagreb', 'Zanzibar', 'Zhengzhou'],
  },

  foods: {
    A: ['Almira', 'Avokado Tosti', 'Alfredo', 'Kuşkonmaz Çorbası', 'Arancini', 'Adobo', 'Antipasto', 'Ağır Makarnası'],
    B: ['Burger', 'Burrito', 'Baklava', 'Brüşetta', 'Bibimbap', 'Borş', 'Biryani', 'Beef Stew'],
    C: ['Köri', 'Carbonara', 'Kruvasan', 'Chili Con Carne', 'Cheesecake', 'Krep', 'Ceviche', 'Couscous'],
    D: ['Dumpling', 'Dal', 'Donut', 'Ördek Confit', 'Danimarka Pastası', 'Dhokla'],
    E: ['Enchilada', 'Empanada', 'Yumurta Benedict', 'Salyangoz', 'Yılan Balığı Suşi'],
    F: ['Kızartılmış Patates', 'Falafel', 'Balık ve Patates', 'Kızartılmış Pirinç', 'Fondue', 'Fransız Tosti', 'Frittata'],
    G: ['Gyoza', 'Gumbo', 'Guacamole', 'Gazpacho', 'Gelato', 'Gnocchi', 'Galette'],
    H: ['Hummus', 'Hot Dog', 'Patates Hasselback', 'Halloumi', 'Hot Pot', 'Bal Pastası'],
    I: ['Dondurma', 'Idli', 'İrlanda Güveç'],
    J: ['Jambalaya', 'Jerk Tavuk', 'Jollof Pirinç', 'Japon Kare'],
    K: ['Kebap', 'Kimchi', 'Katsu Kare', 'Knish', 'Kulfi'],
    L: ['Lazanya', 'İstakoz', 'Mercimek Çorbası', 'Latke', 'Kuzu Pirzolası', 'Lo Mein'],
    M: ['Musakka', 'Miso Çorbası', 'Makaroni', 'Mole', 'Momos', 'Köfte', 'Makaron'],
    N: ['Nachos', 'Noodles', 'Naan', 'Nougat', 'Nasi Goreng'],
    O: ['Omlet', 'Soğan Halkası', 'Okonomiyaki', 'İstiridye'],
    P: ['Pizza', 'Paella', 'Pad Thai', 'Pankek', 'Pho', 'Pierogi', 'Krakeri', 'Poutine'],
    Q: ['Quiche', 'Quesadilla', 'Quindim'],
    R: ['Ramen', 'Risotto', 'Ravioli', 'Rendang', 'Rotisserie Tavuk'],
    S: ['Sushi', 'Biftek', 'Sandwich', 'Shawarma', 'Samosa', 'Souvlaki', 'Bahar Rulo'],
    T: ['Tacos', 'Tikka Masala', 'Tempura', 'Tiramisu', 'Tom Yum', 'Tagine'],
    U: ['Udon', 'Ugali', 'Ube Pastası'],
    V: ['Vichyssoise', 'Vindaloo', 'Veal Scallopini'],
    W: ['Waffle', 'Wontons', 'Beyaz Pirinç', 'Wiener Schnitzel'],
    X: ['Xiaolongbao', 'Xo Sosu'],
    Y: ['Yakitori', 'Yoğurt', 'Yorkshire Pudding', 'Yakisoba'],
    Z: ['Zabaglione', 'Ziti', 'Zeppole', 'Kabak Kızartması'],
  },

  vegetables: {
    A: ['Kuşkonmaz', 'Enginar', 'Roka', 'Avokado', 'Acorn Balkabağı', 'Amaranth'],
    B: ['Brokoli', 'Brüksel Lahanası', 'Pancar', 'Bok Choy', 'Biber', 'Geniş Fasulye', 'Kış Balkabağı'],
    C: ['Havuç', 'Karnabahar', 'Lahana', 'Kereviz', 'Salatalık', 'Mangold', 'Nohut', 'Kereviz Kökü'],
    D: ['Daikon', 'Karahindiba Yaprağı', 'Delicata Balkabağı'],
    E: ['Patlıcan', 'Edamame', 'Endive', 'Escarole'],
    F: ['Rezene', 'Fiddlehead Eğreltisi', 'Yeşil Fasulye', 'Fasulye'],
    G: ['Sarımsak', 'Zencefil', 'Yeşil Soğan', 'Galangal', 'Gai Lan'],
    H: ['Beyin Otu', 'Palmiye Kalbi', 'Haricot Fasulyesi'],
    I: ['Hint Ispanağı', 'Buz Marulu'],
    J: ['Jicama', 'Kudüs Enginarı', 'Jalapeno'],
    K: ['Kara Lahana', 'Kohlrabi', 'Komatsuna'],
    L: ['Pırasa', 'Marul', 'Mercimek', 'Lima Fasulyesi'],
    M: ['Mantar', 'Sarı Hardal Yaprağı', 'Mangetout', 'Mung Fasulyesi', 'Mizuna'],
    N: ['Napa Lahanası', 'Nori'],
    O: ['Soğan', 'Okra', 'Ismen Mantarı', 'Otlu Peynir Biber'],
    P: ['Patates', 'Bezelye', 'Biber', 'Balkabağı', 'Şalgam', 'Mor Lahana'],
    Q: ['Kinoa'],
    R: ['Turp', 'Şalgam', 'Radicchio', 'Kırmızı Lahana', 'Roka'],
    S: ['Ispanak', 'Tatlı Patates', 'Balkabağı', 'Scallion', 'Şeker Bezelyesi', 'Sunchoke'],
    T: ['Domates', 'Şalgam', 'Taro', 'Tomatillo'],
    U: ['Ulluco', 'Upo'],
    V: ['Asma Domates', 'Kadife Fasulyesi'],
    W: ['Su Teresi', 'Su Kestanesi', 'Wakame', 'Beyaz Turp', 'Wasabi Kökü'],
    X: ['Xigua', 'Xigua Kabuğu'],
    Y: ['Yam', 'Yuka', 'Sarı Balkabağı', 'Yard Fasulyesi'],
    Z: ['Kabak', 'Kabak Çiçeği'],
  },

  sports: {
    A: ['Okçuluk', 'Atletizm', 'Amerikan Futbolu', 'Aikido', 'Alp Kayağı', 'Kol Güreşi', 'Sucu Sporları'],
    B: ['Basketbol', 'Beyzbol', 'Badminton', 'Boks', 'Bowling', 'Biathlon', 'Bobsled'],
    C: ['Kriket', 'Bisikletçilik', 'Curling', 'Kano', 'Tırmanış', 'Çapraz Ülke', 'Cheerleading'],
    D: ['Dalış', 'Disk Atışı', 'Dodgeball', 'Dressage'],
    E: ['Atlı Spor', 'Dayanıklılık Yarışması', 'Ekstrem Sporlar'],
    F: ['Futbol', 'Floret', 'Artistik Patinaj', 'Saha Hokeyi', 'Serbest Dalış'],
    G: ['Golf', 'Jimnastik', 'Go-Kart Yarışması'],
    H: ['Hokey', 'Hentbol', 'Yüksek Atlama', 'Engel Yarışı', 'Çekiç Atışı', 'Yamaç Paraşütü'],
    I: ['Buz Hokeyi', 'Buz Pateni', 'İç Voleybol'],
    J: ['Judo', 'Cirit Atışı', 'Jai Alai', 'Josting', 'Jet Kayağı'],
    K: ['Karate', 'Kayak', 'Kick Boks', 'Kendo'],
    L: ['Lacrosse', 'Luge', 'Uzun Atlama', 'Log Yüzen'],
    M: ['Maraton', 'Dağ Tırmanışı', 'Karışık Dövüş Sporları', 'Motocross'],
    N: ['Netball', 'Nordik Kayağı', 'Nordik Kombinesi'],
    O: ['Olimpik Halter', 'Engel Koşusu'],
    P: ['Polo', 'Ping Pong', 'Parkour', 'Pentathlon', 'Para Atletizm'],
    Q: ['Quoits', 'Dört Sporlu Yarış'],
    R: ['Rugby', 'Kürek', 'Kaya Tırmanışı', 'Racquetball'],
    S: ['Yüzme', 'Futbol', 'Kayak', 'Squash', 'Sörf', 'Skateboard', 'Softball'],
    T: ['Tenis', 'Saha ve Pist', 'Taekwondo', 'Üç Sporlu Yarış', 'Masa Tenisi'],
    U: ['Ultimate Frisbee', 'Ultramaraton', 'Su Altı Hokeyi'],
    V: ['Voleybol', 'Vault'],
    W: ['Güreş', 'Su Polosu', 'Halter', 'Rüzgar Kayağı', 'Wakeboard'],
    X: ['X-Games'],
    Y: ['Yoga', 'Yacht Yarışması'],
    Z: ['Zorbing'],
  },

  instruments: {
    A: ['Akordeon', 'Alto Saksafon', 'Autoharp', 'Akustik Gitar'],
    B: ['Banjo', 'Bas Gitar', 'Keçi Borusu', 'Fagot', 'Balalaika', 'Buzuki'],
    C: ['Klarnet', 'Çello', 'Kornet', 'Kastanyet', 'Kontrbas', 'Crwth'],
    D: ['Davul', 'Dulcimer', 'Didgeridoo', 'Çift Bas'],
    E: ['Elektrik Gitar', 'Elektrik Keman', 'Euphonium'],
    F: ['Flüt', 'Fransız Borusu', 'Keman', 'Flugelhorn'],
    G: ['Gitar', 'Aksan Piyano', 'Gong', 'Cam Harmonikas'],
    H: ['Ağız Harmonikası', 'Arp', 'Klavisembal', 'Borusu'],
    I: ['İrlanda Flütü', 'İrlanda Uilleann Borusu'],
    J: ['Caz Trompeti'],
    K: ['Klavye', 'Koto', 'Kalimba'],
    L: ['Lute', 'Lir'],
    M: ['Mandolin', 'Marimba', 'Melodika'],
    N: ['Burun Flütü'],
    O: ['Obua', 'Organ', 'Ocarina'],
    P: ['Piyano', 'Piccolo', 'Pan Flütü'],
    Q: ['Qin', 'Qanun'],
    R: ['Recorder', 'Rhodes Piyano'],
    S: ['Saksafon', 'Sitar', 'Sousaphone', 'Çelik Davul', 'Enstrüman Davulu', 'Synthesizer'],
    T: ['Trompet', 'Trombon', 'Tuba', 'Def', 'Enstrüman Davulu', 'Theremin'],
    U: ['Ukulele', 'Ud'],
    V: ['Keman', 'Viola', 'Vibrafon'],
    W: ['Washboard', 'Rüzgar Çanları', 'Düdük', 'Wagner Tuba'],
    X: ['Ksilofon'],
    Y: ['Yangqin', 'Yueqin'],
    Z: ['Zither', 'Zurna'],
  },

  occupations: {
    A: ['Oyuncu', 'Mimar', 'Muhasebe Elemanı', 'Astronot', 'Arkeolog', 'Animatör', 'Anestezi Teknisyeni'],
    B: ['Fırıncı', 'İnşaat Ustası', 'Bankacı', 'Biyolog', 'Berber', 'Botanikçi', 'Biyokimyager'],
    C: ['Aşçı', 'Marangoz', 'Kasiyer', 'Kimyager', 'Koç', 'Rehber', 'Chiropraktik', 'Orkestra Şefi'],
    D: ['Doktor', 'Diş Hekimi', 'Dedektif', 'Tasarımcı', 'Sürücü', 'Veri Bilimci', 'Dermatoloji Uzmanı'],
    E: ['Mühendis', 'Elektrikçi', 'Editör', 'Ekonomist', 'Acil Tıp Teknisyeni'],
    F: ['Çiftçi', 'İtfaiyeci', 'Çiçekçi', 'Finansal Analist'],
    G: ['Bahçıvan', 'Jeolog', 'Grafik Tasarımcı', 'Genetikçi'],
    H: ['Tarihçi', 'Avcı', 'Hidroloji Mühendisi', 'Kuaför'],
    I: ['Tercüman', 'Müfettiş', 'İllüstratör', 'Yatırım Bankacısı'],
    J: ['Yargıç', 'Gazeteci', 'Kuyumcu', 'Temizlik Görevlisi'],
    K: ['Kinesiolog'],
    L: ['Avukat', 'Kütüphaneci', 'Kilitsiz Oyuncu', 'Dilbilimci'],
    M: ['Teknisyen', 'Müzisyen', 'Yönetici', 'Matematikçi', 'Deniz Biyologi'],
    N: ['Hemşire', 'Beslenme Uzmanı', 'Navigator', 'Nöroloji Uzmanı'],
    O: ['Optisyen', 'Operatör', 'Obstetrik Uzmanı'],
    P: ['Fotoğrafçı', 'Pilot', 'Tesisatçı', 'Programcı', 'Eczacı', 'Psikiyatrist'],
    Q: ['Yorgan Ustası', 'Taş Ocağı İşçisi'],
    R: ['Muhabir', 'Orman Koruma Memuru', 'Araştırmacı', 'Radyoloji Teknisyeni'],
    S: ['Cerrah', 'Bilim İnsanı', 'Satış Danışmanı', 'Denizci', 'Yazılım Mühendisi', 'Sosyolog'],
    T: ['Öğretmen', 'Teknisyen', 'Terapeut', 'Çevirmen', 'Toksikoloji Uzmanı'],
    U: ['Undertaker', 'Şehir Plancısı', 'UX Tasarımcı'],
    V: ['Veteriner', 'Keman Virtuozu', 'Video Oyunu Tasarımcısı'],
    W: ['Yazar', 'Kaporta Ustası', 'Garson', 'Web Geliştirici'],
    X: ['Xylografi Sanatçısı', 'X-Ray Teknisyeni'],
    Y: ['Yoga Eğitmeni', 'Gençlik Danışmanı'],
    Z: ['Zooloji Bilimci', 'Hayvanat Bahçesi Sorumlusu', 'Zoolog'],
  },

  birds: {
    A: ['Albatros', 'Avocet', 'Amerika Mirası', 'Auklet', 'Anhinga', 'Amazon Papağanı'],
    B: ['Mavi Kuş', 'Mavi Jay', 'Kel Kartal', 'Kalekayası Baykuşu', 'Bulfinch', 'Çinçilla Kuşu'],
    C: ['Kardinal', 'Turna Kuşu', 'Karga', 'Kakadu', 'Kanarya', 'Kondor', 'Orman Tayı'],
    D: ['Ördek', 'Güvercin', 'Dodo', 'Dunlin'],
    E: ['Kartal', 'Balıkçıl', 'Emu', 'Doğu Mavi Kuşu'],
    F: ['Flamingo', 'Gökşin', 'Ispanak Kuşu', 'Harita Kuşu'],
    G: ['Kaz', 'Sarı Kuş', 'Büyük Boynuzlu Baykuş', 'Altın Kartal', 'Orman Tavuğu'],
    H: ['Şahin', 'Balıkçıl', 'Kolibri', 'Hoopoe', 'Harrier'],
    I: ['Ibis', 'İndigo Çinçilla Kuşu'],
    J: ['Jay', 'Junco', 'Java Serçesi'],
    K: ['Balık Avı', 'Kiwi', 'Kookaburra', 'Karatavşan'],
    L: ['Tarlak Kuşu', 'Tayı', 'Enstrüman Kuşu', 'Lapwing'],
    M: ['Macaw', 'Düşek Kuşu', 'Akça Kuş', 'Myna', 'Çayırlı Kuşu'],
    N: ['Bülbül', 'Gece Doğanı', 'Fındık Kıracı'],
    O: ['Baykuş', 'Oriole', 'Balık Kartali', 'Fırın Kuşu'],
    P: ['Papağan', 'Pelikan', 'Penguen', 'Tavus Kuşu', 'Güvercin', 'Puffin'],
    Q: ['Bıldırcın', 'Quetzal Kuşu', 'Quelea'],
    R: ['Mirası', 'Karga', 'Yol Koşucusu', 'Kırmızı Uçurtma', 'Rook'],
    S: ['Serçe', 'Sığırcı Kuşu', 'Kuğu', 'Leylek', 'Kar Baykuşu', 'Kum Kuşu'],
    T: ['Tukan', 'Hindik', 'Derni Kuşu', 'Teal', 'Ağlayan Kuş'],
    U: ['Şemsiye Kuşu', 'Yüksek Çayır Kumsal Kuşu'],
    V: ['Akbaba', 'Verdin', 'Vakvak Kuşu'],
    W: ['Şarkı Söyleyen Kuş', 'Ağaç Oyucu', 'Kuş', 'Beyaz Leylek'],
    X: ['Xenops', 'Xantus Sinekkuşu'],
    Y: ['Sarı Şarkı Söyleyen Kuş', 'Sarı Çekiç Kuşu', 'Sarı Bellied Sapsucker'],
    Z: ['Zebra Finch', 'Bölge Kuyruklu Kartal', 'Zitting Cisticola'],
  },

  flowers: {
    A: ['Amaryllis', 'Azalea', 'Alstroemeria', 'Aster', 'Agapanthus', 'Anemone'],
    B: ['Bluebell', 'Siyah Gözlü Susan', 'Begonia', 'Bebek Nefesi', 'Cennet Kuşu', 'Kanayan Kalp'],
    C: ['Karanfil', 'Krizantem', 'Kozmos', 'Crocus', 'Cyclamen', 'Calla Lis', 'Şeker Çiçeği'],
    D: ['Dahlia', 'Papatya', 'Delphinium', 'Nergis', 'Dianthus'],
    E: ['Edelweiss', 'Echinacea', 'Akşam Çiçeği', 'Eustoma'],
    F: ['Freesia', 'Digitalis', 'Fuchsia', 'Unutma Beni'],
    G: ['Gardenia', 'Gladyolus', 'Geranium', 'Gypsophila', 'Gerbera'],
    H: ['Hyacinth', 'Hibiscus', 'Hollyhock', 'Heather', 'Hellebore'],
    I: ['İris', 'Impatiens', 'Buz Bitkisi'],
    J: ['Yasmin', 'Jonquil', 'Jacob\'s Ladder'],
    K: ['Kangaroo Paw', 'Kniphofia'],
    L: ['Lavanta', 'Lis', 'Lotus', 'Larkspur', 'Lisianthus'],
    M: ['Magnolia', 'Akçiçek', 'Sabah Yüzü', 'Ay Çiçeği', 'Muscari'],
    N: ['Narcissus', 'Nemesia', 'Nigella'],
    O: ['Orkide', 'Göz Papatyası', 'Oriental Haşhaş'],
    P: ['Pansy', 'Peony', 'Haşhaş', 'Primrose', 'Phlox', 'Petunia'],
    Q: ['Kraliçe Anne Dantel', 'Quince Çiçeği'],
    R: ['Gül', 'Ranunculus', 'Kırmızı Yonca', 'Rudbeckia'],
    S: ['Ayçiçeği', 'Tatlı Bezelye', 'Snapdragon', 'Stock', 'Statice'],
    T: ['Lale', 'Kaplan Lily', 'Thistle', 'Tuberose'],
    U: ['Ursinia'],
    V: ['Menekşe', 'Verbena', 'Veronica', 'Viburnum'],
    W: ['Wisteria', 'Su Lis', 'Duvar Çiçeği', 'Vahşi Gül'],
    X: ['Xeranthemum', 'Xiphium İrisi'],
    Y: ['Yarrow', 'Sarı Gül', 'Yucca Çiçeği'],
    Z: ['Zinnia', 'Zebra Bitki Çiçeği', 'Zephyranthes'],
  },

  trees: {
    A: ['Kül Ağacı', 'Elma Ağacı', 'Akasya', 'Alnus', 'Titrek Ağacı', 'Avokado Ağacı'],
    B: ['Huş', 'Fagus', 'Baobab', 'Bonsai', 'Balsa', 'Siyah Ceviz', 'Barbados Kiraz', 'Barbados Çit'],
    C: ['Sedir', 'Kiraz Ağacı', 'Cypress', 'Kestane', 'Catalpa', 'Kahve Ağacı'],
    D: ['Douglas Çamı', 'Tarih Palmiyesi', 'Şafak Sekoyası'],
    E: ['Kaynın', 'Okaliptus', 'Elder', 'İngiliz Meşesi'],
    F: ['İncir Ağacı', 'Çam', 'Alev Ağacı'],
    G: ['Ginkgo', 'Sakız Ağacı', 'Altın Yağmuru'],
    H: ['At Kestanesi', 'Fındık', 'Alıç', 'Hemlock'],
    I: ['İrlanda İhlamuru', 'Hint Gül Ağacı', 'Demir Ağacı'],
    J: ['Ardıç', 'Jacaranda', 'Japon Akça Ağaç'],
    K: ['Kapok', 'Kentucky Kahvesi Ağacı', 'Kauri'],
    L: ['Larch', 'Limon Ağacı', 'Kireç Ağacı', 'Laurel'],
    M: ['Akça Ağaç', 'Magnolia', 'Dut', 'Maymun Bulmacası', 'Moreton Bay İnciri'],
    N: ['Norveç Ladin', 'Neem', 'Kuzey Kırmızı Meşesi'],
    O: ['Meşe', 'Zeytin Ağacı', 'Oregon Çamı'],
    P: ['Çam', 'Palmiye', 'Kavak', 'Eriş Ağacı', 'Papaya Ağacı'],
    Q: ['Titrek Huş', 'Ayva Ağacı', 'Queensland Akça Ağaç'],
    R: ['Sequoia', 'Rowan', 'Kırmızı Akça Ağaç', 'Nehir Huşu'],
    S: ['Ladin', 'Çınar', 'Sekoya', 'Gümüş Huş', 'Tatlı Gum'],
    T: ['Teak', 'Tulip Ağacı', 'Tamarind', 'Tamarack'],
    U: ['Şemsiye Ağacı'],
    V: ['Vadisi Meşesi', 'Viburnum Ağacı'],
    W: ['Ceviz', 'Söğüt', 'Beyaz Meşe', 'Wych Kaynın'],
    X: ['Xylosma', 'Xanthoceras'],
    Y: ['İhlamur', 'Sarı Huş', 'Sarı Ağaç'],
    Z: ['Zelkova', 'Zebra Ağacı'],
  },

  gemstones: {
    A: ['Ametist', 'Akvamarin', 'Kehribar', 'Aleksandrit', 'Akik', 'Amazonit'],
    B: ['Beryl', 'Kan Taşı', 'Mavi Topaz', 'Benitoite'],
    C: ['Sitrin', 'Mercan', 'Karneol', 'Kedi Gözü', 'Chrysoberyl', 'Krom Diopside'],
    D: ['Elmas', 'Danburite', 'Diopside'],
    E: ['Zümrüt', 'Epidote', 'Enstatite'],
    F: ['Ateş Opali', 'Flüorit', 'Feldispat'],
    G: ['Granit', 'Goshenite', 'Grossular', 'Altın Taşı'],
    H: ['Heliodor', 'Howlite', 'Hematite', 'Hessonite'],
    I: ['Iolite', 'Indicolite'],
    J: ['Jade', 'Jasper', 'Jet', 'Jadeite'],
    K: ['Kunzite', 'Kyanite'],
    L: ['Lapis Lazuli', 'Labradorite', 'Larimar', 'Lepidolite'],
    M: ['Ay Taşı', 'Malahit', 'Morganite', 'Moldavite'],
    N: ['Nephrite', 'Nuummite'],
    O: ['Oniks', 'Opal', 'Obsidyen'],
    P: ['Peridot', 'İnci', 'Pirit', 'Pembe Safir'],
    Q: ['Kuvars', 'Kuvarsit'],
    R: ['Yakut', 'Gül Kuvars', 'Rodonit', 'Rodokrozit'],
    S: ['Safir', 'Spinel', 'Güneş Taşı', 'Sodalite', 'Smithsonite'],
    T: ['Topaz', 'Turquoise', 'Turmalin', 'Kaplan Gözü'],
    U: ['Unakite', 'Ulexite'],
    V: ['Variscite', 'Verdite'],
    W: ['Karpuz Turmalini', 'Beyaz Opal', 'Beyaz Jade'],
    X: ['Xanthite', 'Xenotime'],
    Y: ['Sarı Safir', 'Sarı Elmas'],
    Z: ['Zirkon', 'Zoisite'],
  },

  dinosaurs: {
    A: ['Allosaurus', 'Ankylosaurus', 'Apatosaurus', 'Argentinosaurus', 'Abelisaurus', 'Altirhinus'],
    B: ['Brachiosaurus', 'Brontosaurus', 'Baryonyx', 'Barosaurus', 'Beipiaosaurus'],
    C: ['Carnotaurus', 'Compsognathus', 'Carcharodontosaurus', 'Ceratosaurus', 'Camarasaurus'],
    D: ['Diplodocus', 'Deinonychus', 'Dilophosaurus', 'Dromaeosaurus'],
    E: ['Edmontosaurus', 'Euoplocephalus', 'Einiosaurus', 'Edmontonia'],
    F: ['Fukuiraptor', 'Futabasaurus'],
    G: ['Giganotosaurus', 'Gallimimus', 'Gasosaurus', 'Gorgosaurus'],
    H: ['Hadrosaurus', 'Hypsilophodon'],
    I: ['Iguanodon', 'Irritator'],
    J: ['Jeholornis', 'Janenschia', 'Jobaria'],
    K: ['Kentrosaurus', 'Kronosaurus', 'Kosmoceratops'],
    L: ['Lambeosaurus', 'Lesothosaurus', 'Leaellynasaura'],
    M: ['Megalosaurus', 'Maiasaura', 'Muttaburrasaurus', 'Mapusaurus'],
    N: ['Neovenator', 'Nigersaurus'],
    O: ['Oviraptor', 'Ornithomimus', 'Ouranosaurus'],
    P: ['Parasaurolophus', 'Pachycephalosaurus', 'Pteranodon', 'Plateosaurus', 'Protoceratops'],
    Q: ['Qantassaurus', 'Quaesitosaurus', 'Quilmesaurus'],
    R: ['Raptor', 'Rugops', 'Rebbachisaurus'],
    S: ['Stegosaurus', 'Spinosaurus', 'Sauroposeidon', 'Saurolophus', 'Saltasaurus'],
    T: ['Triceratops', 'Tyrannosaurus', 'Therizinosaurus', 'Troodon', 'Torosaurus'],
    U: ['Utahraptor', 'Ugrosaurus', 'Unenlagia'],
    V: ['Velociraptor', 'Vulcanodon'],
    W: ['Wuerhosaurus', 'Wannanosaurus'],
    X: ['Xenotarsosaurus', 'Xiaosaurus', 'Xuanhanosaurus'],
    Y: ['Yangchuanosaurus', 'Yandusaurus'],
    Z: ['Zuniceratops', 'Zhuchengtyrannus'],
  },

  movies: {
    A: ['Ayla', 'Ahlat Ağacı', 'Av Mevsimi', 'Aşk Tesadüfleri Sever'],
    B: ['Babam ve Oğlum', 'Bir Zamanlar Anadolu\'da', 'Beynelmilel', 'Bu Son Olsun'],
    C: ['Cenneti Beklerken', 'C Blok', 'Cici'],
    D: ['Düğün Dernek', 'Dedemin İnsanları', 'Devrim Arabaları', 'Dabbe'],
    E: ['Eşkıya', 'Ekşi Elmalar', 'Eltilerin Savaşı', 'Ev Kira Semt Bizim'],
    F: ['Fetih 1453', 'Fakat Müzeyyen Bu Derin Bir Tutku'],
    G: ['G.O.R.A', 'Güneşi Gördüm', 'Geriye Kalan', 'Gemide'],
    H: ['Hababam Sınıfı', 'Hokkabaz', 'Her Şey Çok Güzel Olacak', 'Hükümet Kadın'],
    I: ['Issız Adam', 'Ispanaktan Nağmeler'],
    J: ['Jilet', 'Jön Türk'],
    K: ['Kış Uykusu', 'Kelebeğin Rüyası', 'Karpuz Kabuğundan Gemiler Yapmak', 'Kurtlar Vadisi Irak'],
    L: ['Lal Gece', 'Labirent', 'Limonata'],
    M: ['Mucize', 'Müslüm', 'Mandıra Filozofu', 'Mavi Boncuk'],
    N: ['Nefes Vatan Sağolsun', 'Neşeli Günler', 'Neredesin Firuze', 'Nuh Tepesi'],
    O: ['Organize İşler', 'Oflu Hoca\'nın Şifresi', 'Osman Pazarlama'],
    P: ['Pek Yakında', 'Propaganda', 'Patron Mutlu Son İstiyor', 'Pardon'],
    R: ['Recep İvedik', 'Romantik Komedi', 'Reis Bey', 'Rıza'],
    S: ['Selvi Boylum Al Yazmalım', 'Süt Kardeşler', 'Sivas', 'Sonbahar'],
    T: ['Tosun Paşa', 'Takva', 'Tamam mıyız?', 'Tatar Ramazan'],
    U: ['Uzak', 'Umut', 'Uzun Hikaye', 'Uçurtmayı Vurmasınlar'],
    V: ['Vizontele', 'Vavien', 'Veda', 'Ve Panayır Köyden Gider'],
    Y: ['Yol', 'Yahşi Batı', 'Yazı Tura', 'Yozgat Blues'],
    Z: ['Züğürt Ağa', 'Zerre', 'Zübük'],
  },

  games: {
    A: ['Suikastçı İnancı', 'Hayvan Geçiş', 'Bizim Arasında', 'Apex Efsaneleri'],
    B: ['Batman Arkham', 'Sınır Topraklari', 'Bioshock', 'Baldur\'s Kapısı', 'Savaş Alanı'],
    C: ['Medeniyeti', 'Görevin Çağrısı', 'Kaza Bandicoot', 'Cuphead', 'Kontrol'],
    D: ['Doom', 'Koyu Ruhlar', 'Donkey Kong', 'Ejder Yaşı', 'Ölü Alan'],
    E: ['Yaşlı Kaydırma', 'Toprağın Kısrağı', 'Elden Yüzük', 'Ebedi Sorgu'],
    F: ['Son Fantezi', 'Fortnite', 'Düşüş', 'Fez', 'Uzak Ağlama'],
    G: ['Savaş Tanrısı', 'Büyük Hırsızlık Otomobil', 'Dişli Savaş', 'Tsushima Hayaleti'],
    H: ['Halo', 'Yarım Yaşam', 'Oyuk Şövalye', 'Hogwarts Miraçlar', 'Ufuk'],
    I: ['Ico', 'Bölümdeki İçeri', 'Adaletsizlik', 'İçeri'],
    J: ['Yolculuk', 'Sadece Dansetle', 'Jet Seti Radyo'],
    K: ['Kirby', 'Krallık Kalpleri', 'Katamari Damacy'],
    L: ['Zelda Efsanesi', 'Sol 4 Ölü', 'Küçük Büyük Gezegen', 'Luigi Villası'],
    M: ['Minecraft', 'Mario', 'Metal Dişli Solid', 'Kütledeki Etki', 'Canavar Avcısı'],
    N: ['Hız İhtiyacı', 'Ninja Gaiden', 'NieR Otomat'],
    O: ['Overwatch', 'Ori Kör Orman', 'Dış Vahşi', 'Octopath Yolcusu'],
    P: ['Pokémon', 'Portal', 'Pac-Man', 'Kişilik', 'Persia Princi'],
    Q: ['Q*bert', 'Başarının Yolu', 'Quake'],
    R: ['Kırmızı Ölü İtfaiye', 'Ratchet Clank', 'İkamet Kötü'],
    S: ['Starcraft', 'Skyrim', 'Sonic', 'Spyro', 'Splatoon', 'Sekiro'],
    T: ['Tetris', 'Bizim Son', 'Türbe Soygunu', 'Terraria'],
    U: ['Undertale', 'Uncharted', 'Unreali Turnuva'],
    V: ['Valorant', 'Valheim', 'Vampir Hayatta Kalanlar'],
    W: ['Dünya Savaş', 'Cadı', 'Wolfenstein', 'Gözlemci Köpek'],
    X: ['XCOM', 'Xenogears', 'Xenoblade Müzikleri'],
    Y: ['Yoshi Adası', 'Yakuza', 'Yoku Ada Hızlı'],
    Z: ['Zelda', 'Zork', 'Sıfır Kaçış'],
  },

  tvshows: {
    A: ['Avatar', 'Ok', 'Tutuklu Kalkışma', 'Takma Ad', 'Andor'],
    B: ['Breaking Bad', 'Daha İyi Call Saul', 'Siyah Ayna', 'Kardeş Bandosu', 'Kan Hattı'],
    C: ['Kale', 'Arkadaşlar', 'Topluluk', 'Suç Zihinleri', 'Chernobyl'],
    D: ['Dexter', 'Downton Abbey', 'Koyu', 'Doktor Kim', 'Daredevil'],
    E: ['İlköğretim', 'Öfke', 'Acil Yardım', 'Turist'],
    F: ['Arkadaşlar', 'Fargo', 'Firefly', 'Aile Çocuk', 'Fleabag'],
    G: ['Tahtın Oyunu', 'Grey Anatomi', 'Glee', 'Yer Çekimi Şallı'],
    H: ['Ev', 'Anavatantanı', 'Kahramanlar', 'Durdur Yakalamak', 'Ev Kartları'],
    I: ['Daima Güneşli', 'Yetkisiz'],
    J: ['Gerekçelendirme', 'Jane Bakire'],
    K: ['Eve Alma', 'Krallık'],
    L: ['Kayıp', 'Loki', 'Görev Değeri', 'Lucifer'],
    M: ['Deli Erkekler', 'Aklını Avucunda', 'Modern Aile', 'Mandalorian'],
    N: ['Narcos', 'NCIS', 'Yeni Kız'],
    O: ['Turuncu Yeni Siyah', 'Dış Bankası', 'Bir Ağaç Tepesi', 'Bizim Gezegen'],
    P: ['Parklar Rekreasyon', 'Hapis Kırılması', 'Peaky Blinders', 'Pose'],
    Q: ['Kuantum Sıçrama', 'Kraliçe Oyunu'],
    R: ['Rick Morty', 'Gücü Yüzükler', 'Yükseltilmiş Kurtlarından'],
    S: ['Sıra', 'Yabancı Şeyler', 'Seinfeld', 'Kalamar Oyunu', 'Sherlock'],
    T: ['Tel Tel', 'Sopranos', 'Ted Lasso', 'İkiz Tepeler'],
    U: ['Şemsiye Akademi', 'Çözülmemiş Gizemleri', 'Çirkin Betty'],
    V: ['Vikingeler', 'Veep', 'Vampir Hatıraları'],
    W: ['Yürüyüş Ölü', 'Westworld', 'Batı Kanat', 'Beyaz Lotus', 'Wentworth'],
    X: ['X-Dosyaları', 'Xena Savaş Prenses'],
    Y: ['Genç Sheldon', 'Siz', 'Yellowstone'],
    Z: ['Hayvanat Bahçesi', 'Zombiler'],
  },

  superheroes: {
    A: ['Su Adamı', 'Karınca Adam', 'Atom', 'Ok Kız', 'Atom Havası'],
    B: ['Batman', 'Siyah Pantera', 'Siyah Dul', 'Batgirl', 'Booster Altın'],
    C: ['Kaptan Amerika', 'Cyclops', 'Kaptan Harika', 'Kedi Kadın'],
    D: ['Ölü Havuz', 'Daredevil', 'Doktor Garip', 'Domino'],
    E: ['Elastigirl', 'Elektra'],
    F: ['Flash', 'Şahin', 'Ateş Yıldız'],
    G: ['Yeşil Fenerci', 'Yeşil Ok', 'Groot', 'Hayalet Binici', 'Gambit'],
    H: ['Hulk', 'Hawkeye', 'Hawkman', 'Vuruş Kız'],
    I: ['Demir Adam', 'Görünmez Kadın', 'Buz Adam'],
    J: ['Jessica Jones', 'Jubilee'],
    K: ['Tekme Kahraman', 'Kilowog'],
    L: ['Luke Kafes', 'Lightning Lad'],
    M: ['Bayan Harika', 'Martian Manhunter', 'Ay Şövalyesi', 'Mystiği'],
    N: ['Nightwing', 'Namor', 'Nick Fury', 'Nova'],
    O: ['Oracle'],
    P: ['Profesör X', 'Güç Kız', 'Photon', 'Psylocke'],
    Q: ['Hızlı Gümüş', 'Soru'],
    R: ['Robin', 'Roket Rakun', 'Kırmızı Başlık', 'Rogue'],
    S: ['Süper Adam', 'Örümcek Adam', 'Fırtına', 'O Hulk', 'Shazam'],
    T: ['Thor', 'Tik', 'Toksin'],
    U: ['Ultra Boy', 'Union Jack'],
    V: ['Vizyon', 'Zehir', 'Valkyrie'],
    W: ['Harika Kadın', 'Wolverine', 'Ari', 'Savaş Makinesi'],
    X: ['X-23', 'Xavier'],
    Y: ['Sarı Ceket'],
    Z: ['Zatanna', 'Zorro', 'Zoom'],
  },

  mythology: {
    A: ['Apollon', 'Afrodit', 'Athena', 'Ares', 'Anubis', 'Atlas', 'Aurora'],
    B: ['Bacchus', 'Bes', 'Brahma', 'Brigid', 'Baldr'],
    C: ['Kronos', 'Kupid', 'Cernunnos', 'Circe'],
    D: ['Dionysus', 'Demeter', 'Danu'],
    E: ['Eros', 'Eris', 'Epona'],
    F: ['Freya', 'Frigg', 'Forseti'],
    G: ['Gaia', 'Ganesh'],
    H: ['Hades', 'Hermes', 'Hera', 'Horus', 'Hecate'],
    I: ['İris', 'İsis', 'İndra'],
    J: ['Jüpiter', 'Janus', 'Juno'],
    K: ['Khepri', 'Krishna', 'Kali', 'Kanaloa'],
    L: ['Loki', 'Luna'],
    M: ['Mars', 'Merkür', 'Minerva', 'Morpheus', 'Morrigan'],
    N: ['Neptün', 'Nike', 'Nephthys', 'Nut'],
    O: ['Odin', 'Osiris'],
    P: ['Poseidon', 'Persephone', 'Pan', 'Prometheus'],
    Q: ['Quetzalcoatl'],
    R: ['Ra', 'Rhea', 'Radha'],
    S: ['Satürn', 'Shiva', 'Selene', 'Sobek', 'Set'],
    T: ['Thor', 'Triton', 'Tyr', 'Thoth'],
    U: ['Uranus', 'Ukko'],
    V: ['Vishnu', 'Venüs', 'Vulcan'],
    W: ['Wadjet', 'Wepwawet', 'Wotan'],
    X: ['Xipe Totec', 'Xochiquetzal'],
    Y: ['Ymir', 'Yama'],
    Z: ['Zeus', 'Zephyrus', 'Zhong Kui'],
  },

  history: {
    A: ['İskender Büyük', 'Aristoteles', 'Amelia Earhart', 'Arşimet'],
    B: ['Boudicca', 'Beethoven', 'Bolivar'],
    C: ['Kleopatra', 'Churchill', 'Konfüçyüs', 'Kolomb', 'Kopernik'],
    D: ['Darwin', 'Descartes', 'Diocletian'],
    E: ['Einstein', 'Elizabeth I', 'Euclid'],
    F: ['Franklin', 'Frederick Büyük', 'Florence Nightingale'],
    G: ['Galileo', 'Gandhi', 'Cengiz Han', 'Gutenberg'],
    H: ['Hannibal', 'Harriet Tubman', 'Hippocrates', 'Hadrian'],
    I: ['Ivan Korkunç', 'Isabella Kastilya'],
    J: ['Joan of Arc', 'Julius Caesar', 'Jefferson'],
    K: ['Kepler', 'Kublai Han', 'Kamehameha'],
    L: ['Lincoln', 'Leonardo da Vinci', 'Louis XIV', 'Lenin'],
    M: ['Marie Curie', 'Magellan', 'Marco Polo', 'Michelangelo', 'Mozart'],
    N: ['Newton', 'Napolyon', 'Nelson', 'Nero'],
    O: ['Obama', 'Oliver Cromwell', 'Octavian'],
    P: ['Plato', 'Pocahontas', 'Pythagoras', 'Pericles'],
    Q: ['Qin Shi Huang'],
    R: ['Roosevelt', 'Rembrandt', 'Aslan Kral Richard', 'Rasputin'],
    S: ['Shakespeare', 'Sokrates', 'Sun Tzu', 'Süleyman'],
    T: ['Tesla', 'Tutankhamun', 'Thomas Edison'],
    U: ['Ulysses S. Grant'],
    V: ['Voltaire', 'Victoria'],
    W: ['Washington', 'Wellington', 'Fetihçi William'],
    X: ['Xerxes'],
    Y: ['Yuri Gagarin'],
    Z: ['Zheng He', 'Zhukov'],
  },

  dances: {
    A: ['Arjantin Tango', 'Afrobeat', 'Aerobics Dans', 'Apsara Dans'],
    B: ['Bale', 'Bachata', 'Bhangra', 'Balo', 'Breakdance', 'B-boying'],
    C: ['Cha-Cha', 'Charleston', 'Ülke Hattı Dans', 'Capoeira'],
    D: ['Disko', 'Danzon'],
    E: ['Elektrik Kaydırma', 'İngiliz Ülke Dans'],
    F: ['Foxtrot', 'Flamenco'],
    G: ['Garba', 'Gumboot Dans'],
    H: ['Hip Hop', 'Kayıt Uçuş', 'Haka', 'Hora'],
    I: ['İrlanda Adımları Dansı'],
    J: ['Jive', 'Jazz Dans', 'Jig'],
    K: ['Kathak', 'Krump', 'Kizomba'],
    L: ['Lindy Hop', 'Latin Dans', 'Lambada'],
    M: ['Mambo', 'Merengue', 'Moonwalk', 'Macarena'],
    N: ['Kuzey Ruh', 'Noh Dans'],
    O: ['One-Step', 'Oyun Havası'],
    P: ['Polka', 'Paso Doble', 'Popping'],
    Q: ['Quickstep', 'Quadrille'],
    R: ['Rumba', 'Robot Dans', 'Reggaeton'],
    S: ['Salsa', 'Samba', 'Swing', 'Shuffle'],
    T: ['Tango', 'Twist', 'Tap Dans', 'Tinikling'],
    U: ['Kentsel Dans'],
    V: ['Viyana Valsi', 'Voguing'],
    W: ['Valsi', 'Waacking', 'Waltz Türk'],
    X: ['Xaxado', 'Xango Dansı'],
    Y: ['Yangko', 'Yosakoi'],
    Z: ['Zapateado', 'Zydeco'],
  },
};
