const CATEGORIES = {
  fruits:      'Fruits',
  animals:     'Animals',
  cities:      'World Cities',
  foods:       'Foods & Dishes',
  vegetables:  'Vegetables',
  sports:      'Sports',
  instruments: 'Musical Instruments',
  occupations: 'Occupations',
  birds:       'Birds',
  flowers:     'Flowers',
  trees:       'Trees',
  gemstones:   'Gemstones',
  dinosaurs:   'Dinosaurs',
  movies:      'Movies',
  games:       'Video Games',
  tvshows:     'TV Shows',
  superheroes: 'Superheroes',
  mythology:   'Mythological Deities',
  history:     'Historical Figures',
  dances:      'Dances',
};

const WORDS = {
  fruits: {
    A: ['Apple', 'Apricot', 'Avocado', 'Acai', 'Ackee', 'Asian Pear'],
    B: ['Banana', 'Blueberry', 'Blackberry', 'Boysenberry', 'Breadfruit', 'Blood Orange'],
    C: ['Cherry', 'Coconut', 'Cranberry', 'Cantaloupe', 'Clementine', 'Currant'],
    D: ['Dragonfruit', 'Durian', 'Date', 'Damson', 'Dewberry'],
    E: ['Elderberry', 'Emblica', 'Etrog'],
    F: ['Fig', 'Feijoa', 'Finger Lime'],
    G: ['Grape', 'Guava', 'Grapefruit', 'Gooseberry', 'Greengage'],
    H: ['Honeydew', 'Huckleberry', 'Hackberry'],
    I: ['Ilama', 'Indian Plum', 'Imbe'],
    J: ['Jackfruit', 'Jujube', 'Jaboticaba', 'Java Plum'],
    K: ['Kiwi', 'Kumquat', 'Kiwano', 'Kaki'],
    L: ['Lemon', 'Lime', 'Lychee', 'Longan', 'Loganberry'],
    M: ['Mango', 'Melon', 'Mulberry', 'Mandarin', 'Maracuja'],
    N: ['Nectarine', 'Noni', 'Naranjilla'],
    O: ['Orange', 'Olive', 'Ortanique'],
    P: ['Peach', 'Pear', 'Pineapple', 'Plum', 'Pomegranate', 'Papaya', 'Passion Fruit'],
    Q: ['Quince', 'Quenepa'],
    R: ['Raspberry', 'Rambutan', 'Redcurrant', 'Rose Apple'],
    S: ['Strawberry', 'Star Fruit', 'Sapodilla', 'Soursop'],
    T: ['Tangerine', 'Tamarind', 'Tomato', 'Tamarillo'],
    U: ['Ugli Fruit', 'Ugni'],
    V: ['Valencia Orange', 'Voavanga'],
    W: ['Watermelon', 'Wolfberry', 'Wampee'],
    X: ['Xigua', 'Ximenia'],
    Y: ['Yuzu', 'Yellow Passion Fruit', 'Yangmei'],
    Z: ['Ziziphus'],
  },

  animals: {
    A: ['Alligator', 'Antelope', 'Armadillo', 'Aardvark', 'Alpaca', 'Anaconda'],
    B: ['Bear', 'Buffalo', 'Baboon', 'Bison', 'Bat', 'Beaver'],
    C: ['Cheetah', 'Crocodile', 'Camel', 'Cobra', 'Chimpanzee', 'Coyote'],
    D: ['Deer', 'Dolphin', 'Dingo', 'Donkey', 'Dhole'],
    E: ['Elephant', 'Elk', 'Emu', 'Echidna'],
    F: ['Fox', 'Frog', 'Ferret', 'Flamingo', 'Falcon'],
    G: ['Gorilla', 'Giraffe', 'Gecko', 'Gazelle', 'Goat'],
    H: ['Hippo', 'Horse', 'Hyena', 'Hamster', 'Hedgehog'],
    I: ['Iguana', 'Impala', 'Ibis'],
    J: ['Jaguar', 'Jellyfish', 'Jackal', 'Jaguar'],
    K: ['Kangaroo', 'Koala', 'Komodo Dragon', 'Kinkajou'],
    L: ['Lion', 'Leopard', 'Llama', 'Lynx', 'Lemur'],
    M: ['Monkey', 'Moose', 'Meerkat', 'Mouse', 'Mongoose', 'Manatee'],
    N: ['Narwhal', 'Newt', 'Numbat'],
    O: ['Orangutan', 'Ostrich', 'Otter', 'Octopus', 'Owl'],
    P: ['Panda', 'Penguin', 'Puma', 'Panther', 'Platypus', 'Porcupine'],
    Q: ['Quokka', 'Quoll', 'Quetzal'],
    R: ['Rabbit', 'Rhinoceros', 'Raccoon', 'Rattlesnake', 'Red Panda'],
    S: ['Snake', 'Shark', 'Sloth', 'Seal', 'Squirrel', 'Snow Leopard'],
    T: ['Tiger', 'Turtle', 'Tapir', 'Toucan', 'Tasmanian Devil'],
    U: ['Uakari', 'Urial'],
    V: ['Vulture', 'Viper', 'Vicuna'],
    W: ['Wolf', 'Whale', 'Wombat', 'Walrus', 'Weasel', 'Wolverine'],
    X: ['Xerus', 'Xenops'],
    Y: ['Yak', 'Yellow Mongoose', 'Yacare Caiman'],
    Z: ['Zebra', 'Zebu'],
  },

  cities: {
    A: ['Amsterdam', 'Athens', 'Auckland', 'Ankara', 'Accra', 'Algiers'],
    B: ['Barcelona', 'Bangkok', 'Buenos Aires', 'Berlin', 'Beijing', 'Brussels'],
    C: ['Cairo', 'Chicago', 'Copenhagen', 'Casablanca', 'Cape Town', 'Colombo'],
    D: ['Dubai', 'Delhi', 'Dublin', 'Dhaka', 'Detroit', 'Dakar'],
    E: ['Edinburgh', 'Entebbe', 'El Paso'],
    F: ['Florence', 'Frankfurt', 'Fuzhou'],
    G: ['Geneva', 'Glasgow', 'Guangzhou', 'Guadalajara'],
    H: ['Hong Kong', 'Havana', 'Hamburg', 'Helsinki', 'Hanoi'],
    I: ['Istanbul', 'Islamabad', 'Izmir'],
    J: ['Jakarta', 'Jerusalem', 'Johannesburg', 'Jaipur'],
    K: ['Karachi', 'Kyoto', 'Kuala Lumpur', 'Kinshasa', 'Kathmandu'],
    L: ['London', 'Los Angeles', 'Lima', 'Lisbon', 'Lagos', 'Lyon'],
    M: ['Madrid', 'Moscow', 'Mumbai', 'Montreal', 'Melbourne', 'Manila'],
    N: ['New York', 'Nairobi', 'Naples', 'New Delhi', 'Nagoya'],
    O: ['Oslo', 'Ottawa', 'Osaka', 'Odessa'],
    P: ['Paris', 'Prague', 'Perth', 'Philadelphia', 'Porto'],
    Q: ['Quebec City', 'Quito', 'Quezon City'],
    R: ['Rome', 'Rio de Janeiro', 'Rotterdam', 'Riyadh', 'Reykjavik'],
    S: ['Sydney', 'Seoul', 'Singapore', 'Stockholm', 'Shanghai'],
    T: ['Tokyo', 'Toronto', 'Tehran', 'Tel Aviv', 'Taipei'],
    U: ['Ulaanbaatar', 'Utrecht', 'Ufa'],
    V: ['Vienna', 'Vancouver', 'Venice', 'Vilnius', 'Vladivostok'],
    W: ['Warsaw', 'Washington DC', 'Wellington', 'Winnipeg'],
    X: ["Xi'an"],
    Y: ['Yokohama', 'Yangon', 'Yerevan'],
    Z: ['Zurich', 'Zagreb', 'Zanzibar'],
  },

  foods: {
    A: ['Apple Pie', 'Avocado Toast', 'Alfredo Pasta', 'Asparagus Soup'],
    B: ['Burger', 'Burrito', 'Baklava', 'Bruschetta', 'Bibimbap'],
    C: ['Curry', 'Carbonara', 'Croissant', 'Chili', 'Cheesecake'],
    D: ['Dumpling', 'Dal', 'Donut', 'Duck Confit'],
    E: ['Enchilada', 'Empanada', 'Eggs Benedict'],
    F: ['French Fries', 'Falafel', 'Fish and Chips', 'Fried Rice'],
    G: ['Gyoza', 'Gumbo', 'Guacamole', 'Gazpacho', 'Gelato'],
    H: ['Hummus', 'Hot Dog', 'Hash Browns', 'Halloumi'],
    I: ['Ice Cream', 'Idli'],
    J: ['Jambalaya', 'Jerk Chicken', 'Jollof Rice'],
    K: ['Kebab', 'Kimchi', 'Katsu Curry', 'Knish'],
    L: ['Lasagna', 'Lobster', 'Lentil Soup', 'Latke'],
    M: ['Moussaka', 'Miso Soup', 'Macaroni', 'Mole', 'Momos'],
    N: ['Nachos', 'Noodles', 'Naan', 'Nougat'],
    O: ['Omelette', 'Onion Rings', 'Okonomiyaki'],
    P: ['Pizza', 'Paella', 'Pad Thai', 'Pancakes', 'Pho'],
    Q: ['Quiche', 'Quesadilla', 'Quindim'],
    R: ['Ramen', 'Risotto', 'Ravioli', 'Rendang'],
    S: ['Sushi', 'Steak', 'Sandwich', 'Shawarma', 'Samosa'],
    T: ['Tacos', 'Tikka Masala', 'Tempura', 'Tiramisu'],
    U: ['Udon', 'Ugali'],
    V: ['Vichyssoise', 'Vindaloo'],
    W: ['Waffle', 'Wontons', 'Beef Wellington'],
    X: ['Xiaolongbao', 'Xo Sauce'],
    Y: ['Yakitori', 'Yogurt', 'Yorkshire Pudding'],
    Z: ['Zabaglione', 'Ziti', 'Zeppole'],
  },

  vegetables: {
    A: ['Asparagus', 'Artichoke', 'Arugula', 'Avocado'],
    B: ['Broccoli', 'Brussels Sprouts', 'Beetroot', 'Bok Choy', 'Bell Pepper'],
    C: ['Carrot', 'Cauliflower', 'Cabbage', 'Celery', 'Cucumber'],
    D: ['Daikon', 'Dandelion Greens'],
    E: ['Eggplant', 'Edamame', 'Endive'],
    F: ['Fennel', 'Fiddlehead Fern'],
    G: ['Garlic', 'Ginger', 'Green Onion'],
    H: ['Horseradish', 'Heart of Palm'],
    I: ['Indian Spinach'],
    J: ['Jicama', 'Jerusalem Artichoke'],
    K: ['Kale', 'Kohlrabi'],
    L: ['Leek', 'Lettuce'],
    M: ['Mushroom', 'Mustard Greens', 'Mangetout'],
    N: ['Napa Cabbage'],
    O: ['Onion', 'Okra'],
    P: ['Potato', 'Pea', 'Pepper', 'Pumpkin', 'Parsnip'],
    Q: ['Quinoa'],
    R: ['Radish', 'Rutabaga', 'Radicchio'],
    S: ['Spinach', 'Sweet Potato', 'Squash', 'Scallion'],
    T: ['Tomato', 'Turnip', 'Taro'],
    U: ['Ulluco'],
    V: ['Vine Tomato'],
    W: ['Watercress', 'Water Chestnut', 'Wakame'],
    X: ['Xigua'],
    Y: ['Yam', 'Yuca', 'Yellow Squash'],
    Z: ['Zucchini'],
  },

  sports: {
    A: ['Archery', 'Athletics', 'American Football', 'Aikido', 'Alpine Skiing'],
    B: ['Basketball', 'Baseball', 'Badminton', 'Boxing', 'Bowling'],
    C: ['Cricket', 'Cycling', 'Curling', 'Canoeing', 'Climbing'],
    D: ['Diving', 'Discus Throw', 'Dodgeball'],
    E: ['Equestrian', 'Endurance Racing'],
    F: ['Football', 'Fencing', 'Figure Skating'],
    G: ['Golf', 'Gymnastics'],
    H: ['Hockey', 'Handball', 'High Jump', 'Hurdles'],
    I: ['Ice Hockey', 'Ice Skating'],
    J: ['Judo', 'Javelin', 'Jai Alai', 'Jousting'],
    K: ['Karate', 'Kayaking', 'Kickboxing'],
    L: ['Lacrosse', 'Luge', 'Long Jump'],
    M: ['Marathon', 'Mountaineering', 'Mixed Martial Arts'],
    N: ['Netball', 'Nordic Skiing'],
    O: ['Olympic Weightlifting'],
    P: ['Polo', 'Ping Pong', 'Parkour', 'Pentathlon'],
    Q: ['Quoits', 'Quadrathlon'],
    R: ['Rugby', 'Rowing', 'Rock Climbing'],
    S: ['Swimming', 'Soccer', 'Skiing', 'Squash', 'Surfing'],
    T: ['Tennis', 'Track and Field', 'Taekwondo', 'Triathlon'],
    U: ['Ultimate Frisbee', 'Ultramarathon'],
    V: ['Volleyball', 'Vaulting'],
    W: ['Wrestling', 'Water Polo', 'Weightlifting', 'Windsurfing'],
    X: ['X-Games'],
    Y: ['Yoga'],
    Z: ['Zorbing'],
  },

  instruments: {
    A: ['Accordion', 'Alto Saxophone', 'Autoharp'],
    B: ['Banjo', 'Bass Guitar', 'Bagpipes', 'Bassoon'],
    C: ['Clarinet', 'Cello', 'Cornet', 'Castanets'],
    D: ['Drums', 'Dulcimer', 'Didgeridoo'],
    E: ['Electric Guitar', 'Electric Violin'],
    F: ['Flute', 'French Horn', 'Fiddle'],
    G: ['Guitar', 'Grand Piano', 'Gong'],
    H: ['Harmonica', 'Harp', 'Harpsichord'],
    I: ['Irish Flute'],
    J: ['Jazz Trumpet'],
    K: ['Keyboard', 'Koto'],
    L: ['Lute', 'Lyre'],
    M: ['Mandolin', 'Marimba'],
    N: ['Nose Flute'],
    O: ['Oboe', 'Organ'],
    P: ['Piano', 'Piccolo'],
    Q: ['Qin', 'Qanun'],
    R: ['Recorder'],
    S: ['Saxophone', 'Sitar', 'Sousaphone', 'Steel Drum'],
    T: ['Trumpet', 'Trombone', 'Tuba', 'Tambourine'],
    U: ['Ukulele'],
    V: ['Violin', 'Viola'],
    W: ['Washboard', 'Wind Chimes'],
    X: ['Xylophone'],
    Y: ['Yangqin', 'Yueqin'],
    Z: ['Zither', 'Zurna'],
  },

  occupations: {
    A: ['Actor', 'Architect', 'Accountant', 'Astronaut', 'Archaeologist'],
    B: ['Baker', 'Builder', 'Banker', 'Biologist', 'Barber'],
    C: ['Chef', 'Carpenter', 'Cashier', 'Chemist', 'Coach'],
    D: ['Doctor', 'Dentist', 'Detective', 'Designer', 'Driver'],
    E: ['Engineer', 'Electrician', 'Editor', 'Economist'],
    F: ['Farmer', 'Firefighter', 'Florist'],
    G: ['Gardener', 'Geologist'],
    H: ['Historian', 'Hunter'],
    I: ['Interpreter', 'Inspector'],
    J: ['Judge', 'Journalist', 'Jeweler'],
    K: ['Knitter'],
    L: ['Lawyer', 'Librarian', 'Locksmith'],
    M: ['Mechanic', 'Musician', 'Manager', 'Mathematician'],
    N: ['Nurse', 'Nutritionist', 'Navigator'],
    O: ['Optician', 'Operator'],
    P: ['Photographer', 'Pilot', 'Plumber', 'Programmer'],
    Q: ['Quilter', 'Quarryman'],
    R: ['Reporter', 'Ranger', 'Researcher'],
    S: ['Surgeon', 'Scientist', 'Salesperson', 'Sailor'],
    T: ['Teacher', 'Technician', 'Therapist'],
    U: ['Undertaker', 'Urban Planner'],
    V: ['Veterinarian', 'Violinist'],
    W: ['Writer', 'Welder', 'Waiter'],
    X: ['Xylographer'],
    Y: ['Yoga Instructor'],
    Z: ['Zoologist', 'Zookeeper'],
  },

  birds: {
    A: ['Albatross', 'Avocet', 'American Robin', 'Auklet'],
    B: ['Bluebird', 'Blue Jay', 'Bald Eagle', 'Barn Owl'],
    C: ['Cardinal', 'Crane', 'Crow', 'Cockatoo', 'Canary'],
    D: ['Duck', 'Dove', 'Dodo'],
    E: ['Eagle', 'Egret', 'Emu'],
    F: ['Flamingo', 'Falcon', 'Finch'],
    G: ['Goose', 'Goldfinch', 'Great Horned Owl'],
    H: ['Hawk', 'Heron', 'Hummingbird', 'Hoopoe'],
    I: ['Ibis'],
    J: ['Jay', 'Junco'],
    K: ['Kingfisher', 'Kiwi', 'Kookaburra'],
    L: ['Lark', 'Loon', 'Lyrebird'],
    M: ['Macaw', 'Mockingbird', 'Magpie'],
    N: ['Nightingale', 'Nighthawk'],
    O: ['Owl', 'Oriole', 'Osprey'],
    P: ['Parrot', 'Pelican', 'Penguin', 'Peacock'],
    Q: ['Quail', 'Quetzal', 'Quelea'],
    R: ['Robin', 'Raven', 'Roadrunner'],
    S: ['Sparrow', 'Starling', 'Swan', 'Stork'],
    T: ['Toucan', 'Turkey', 'Tern'],
    U: ['Umbrellabird'],
    V: ['Vulture'],
    W: ['Warbler', 'Woodpecker', 'Wren'],
    X: ['Xenops'],
    Y: ['Yellow Warbler', 'Yellowhammer'],
    Z: ['Zebra Finch', 'Zone-tailed Hawk'],
  },

  flowers: {
    A: ['Amaryllis', 'Azalea', 'Alstroemeria', 'Aster'],
    B: ['Bluebell', 'Black-Eyed Susan', 'Begonia', "Baby's Breath"],
    C: ['Carnation', 'Chrysanthemum', 'Cosmos', 'Crocus'],
    D: ['Dahlia', 'Daisy', 'Delphinium', 'Daffodil'],
    E: ['Edelweiss', 'Echinacea'],
    F: ['Freesia', 'Foxglove', 'Fuchsia'],
    G: ['Gardenia', 'Gladiolus', 'Geranium'],
    H: ['Hyacinth', 'Hibiscus', 'Hollyhock'],
    I: ['Iris', 'Impatiens'],
    J: ['Jasmine', 'Jonquil'],
    K: ['Kangaroo Paw'],
    L: ['Lavender', 'Lily', 'Lotus', 'Larkspur'],
    M: ['Magnolia', 'Marigold', 'Morning Glory'],
    N: ['Narcissus', 'Nemesia'],
    O: ['Orchid', 'Oxeye Daisy'],
    P: ['Pansy', 'Peony', 'Poppy', 'Primrose'],
    Q: ["Queen Anne's Lace", 'Quince Blossom'],
    R: ['Rose', 'Ranunculus', 'Red Clover'],
    S: ['Sunflower', 'Sweet Pea', 'Snapdragon'],
    T: ['Tulip', 'Tiger Lily', 'Thistle'],
    U: ['Ursinia'],
    V: ['Violet', 'Verbena', 'Veronica'],
    W: ['Wisteria', 'Water Lily', 'Wallflower'],
    X: ['Xeranthemum', 'Xiphium Iris'],
    Y: ['Yarrow', 'Yellow Rose'],
    Z: ['Zinnia', 'Zebra Plant Flower'],
  },

  trees: {
    A: ['Ash', 'Apple Tree', 'Acacia', 'Alder'],
    B: ['Birch', 'Beech', 'Baobab', 'Bonsai'],
    C: ['Cedar', 'Cherry Tree', 'Cypress', 'Chestnut'],
    D: ['Douglas Fir', 'Date Palm'],
    E: ['Elm', 'Eucalyptus', 'Elder'],
    F: ['Fig Tree', 'Fir'],
    G: ['Ginkgo', 'Gum Tree'],
    H: ['Horse Chestnut', 'Hazel', 'Hawthorn', 'Hemlock'],
    I: ['Irish Yew'],
    J: ['Juniper', 'Jacaranda'],
    K: ['Kapok'],
    L: ['Larch', 'Lemon Tree', 'Lime Tree'],
    M: ['Maple', 'Magnolia', 'Mulberry'],
    N: ['Norway Spruce', 'Neem'],
    O: ['Oak', 'Olive Tree'],
    P: ['Pine', 'Palm', 'Poplar', 'Plum Tree'],
    Q: ['Quaking Aspen', 'Quince Tree'],
    R: ['Redwood', 'Rowan', 'Red Maple'],
    S: ['Spruce', 'Sycamore', 'Sequoia', 'Silver Birch'],
    T: ['Teak', 'Tulip Tree', 'Tamarind'],
    U: ['Umbrella Tree'],
    V: ['Valley Oak'],
    W: ['Walnut', 'Willow', 'White Oak'],
    X: ['Xylosma'],
    Y: ['Yew', 'Yellow Birch'],
    Z: ['Zelkova', 'Zebrawood'],
  },

  gemstones: {
    A: ['Amethyst', 'Aquamarine', 'Amber', 'Alexandrite'],
    B: ['Beryl', 'Bloodstone', 'Blue Topaz'],
    C: ['Citrine', 'Coral', 'Carnelian'],
    D: ['Diamond'],
    E: ['Emerald', 'Epidote'],
    F: ['Fire Opal', 'Fluorite'],
    G: ['Garnet', 'Goshenite'],
    H: ['Heliodor', 'Howlite', 'Hematite'],
    I: ['Iolite'],
    J: ['Jade', 'Jasper', 'Jet'],
    K: ['Kunzite', 'Kyanite'],
    L: ['Lapis Lazuli', 'Labradorite'],
    M: ['Moonstone', 'Malachite', 'Morganite'],
    N: ['Nephrite'],
    O: ['Onyx', 'Opal'],
    P: ['Peridot', 'Pearl', 'Pyrite'],
    Q: ['Quartz', 'Quartzite'],
    R: ['Ruby', 'Rose Quartz', 'Rhodonite'],
    S: ['Sapphire', 'Spinel', 'Sunstone'],
    T: ['Topaz', 'Turquoise', 'Tourmaline'],
    U: ['Unakite', 'Ulexite'],
    V: ['Variscite', 'Verdite'],
    W: ['Watermelon Tourmaline', 'White Opal'],
    X: ['Xanthite'],
    Y: ['Yellow Sapphire', 'Yellow Diamond'],
    Z: ['Zircon', 'Zoisite'],
  },

  dinosaurs: {
    A: ['Allosaurus', 'Ankylosaurus', 'Apatosaurus', 'Argentinosaurus'],
    B: ['Brachiosaurus', 'Brontosaurus', 'Baryonyx'],
    C: ['Carnotaurus', 'Compsognathus', 'Carcharodontosaurus'],
    D: ['Diplodocus', 'Deinonychus', 'Dilophosaurus'],
    E: ['Edmontosaurus', 'Euoplocephalus'],
    F: ['Fukuiraptor'],
    G: ['Giganotosaurus', 'Gallimimus'],
    H: ['Hadrosaurus'],
    I: ['Iguanodon'],
    J: ['Jeholornis', 'Janenschia'],
    K: ['Kentrosaurus', 'Kronosaurus'],
    L: ['Lambeosaurus', 'Lesothosaurus'],
    M: ['Megalosaurus', 'Maiasaura'],
    N: ['Neovenator'],
    O: ['Oviraptor', 'Ornithomimus'],
    P: ['Parasaurolophus', 'Pachycephalosaurus', 'Pteranodon'],
    Q: ['Qantassaurus', 'Quaesitosaurus', 'Quilmesaurus'],
    R: ['Raptor', 'Rugops'],
    S: ['Stegosaurus', 'Spinosaurus', 'Sauroposeidon', 'Saurolophus'],
    T: ['Triceratops', 'Tyrannosaurus', 'Therizinosaurus'],
    U: ['Utahraptor', 'Ugrosaurus'],
    V: ['Velociraptor'],
    W: ['Wuerhosaurus', 'Wannanosaurus'],
    X: ['Xenotarsosaurus', 'Xiaosaurus', 'Xuanhanosaurus'],
    Y: ['Yangchuanosaurus'],
    Z: ['Zuniceratops', 'Zhuchengtyrannus'],
  },

  movies: {
    A: ['Avatar', 'Aliens', 'Aladdin', 'Arrival'],
    B: ['Batman', 'Braveheart', 'Blade Runner', 'Black Panther'],
    C: ['Casablanca', 'Clueless', 'Captain America'],
    D: ['Die Hard', 'Dune', 'Dunkirk', 'Dark Knight'],
    E: ['Elf', 'ET', 'Everything Everywhere All At Once'],
    F: ['Forrest Gump', 'Frozen', 'Fight Club', 'Finding Nemo'],
    G: ['Gladiator', 'Goodfellas', 'Grease', 'Get Out'],
    H: ['Harry Potter', 'Home Alone', 'Her', 'Heat'],
    I: ['Inception', 'Iron Man', 'Interstellar'],
    J: ['Jaws', 'Joker', 'Jurassic Park', 'Jumanji'],
    K: ['Killers of the Flower Moon', 'King Kong'],
    L: ['Lion King', 'La La Land', 'Lego Movie'],
    M: ['Matrix', 'Mad Max', 'Moana', 'Mulan'],
    N: ['No Country for Old Men', 'Nope'],
    O: ['Oppenheimer', "Ocean's Eleven"],
    P: ['Pulp Fiction', 'Pirates of the Caribbean', 'Parasite'],
    Q: ['Quiz Show', 'Quantum of Solace'],
    R: ['Rocky', 'Ratatouille', 'Rear Window'],
    S: ['Star Wars', 'Shrek', 'Spider-Man', 'Saving Private Ryan'],
    T: ['Titanic', 'Top Gun', 'Toy Story', 'The Godfather'],
    U: ['Up', 'Uncut Gems'],
    V: ['V for Vendetta', 'Vertigo'],
    W: ['Wall-E', 'Wonder Woman', 'Wizard of Oz', 'Whiplash'],
    X: ['X-Men', 'XXX'],
    Y: ['Yesterday', 'Young Frankenstein'],
    Z: ['Zootopia', 'Zodiac', 'Zorro'],
  },

  games: {
    A: ["Assassin's Creed", 'Animal Crossing', 'Among Us'],
    B: ['Batman Arkham', 'Borderlands', 'Bioshock'],
    C: ['Civilization', 'Call of Duty', 'Crash Bandicoot'],
    D: ['Doom', 'Dark Souls', 'Donkey Kong'],
    E: ['Elder Scrolls', 'Earthworm Jim'],
    F: ['Final Fantasy', 'Fortnite', 'Fallout'],
    G: ['God of War', 'Grand Theft Auto', 'Gears of War'],
    H: ['Halo', 'Half-Life', 'Hollow Knight'],
    I: ['Ico', 'Into the Breach', 'Injustice'],
    J: ['Journey', 'Just Dance'],
    K: ['Kirby', 'Kingdom Hearts'],
    L: ['Legend of Zelda', 'Left 4 Dead', 'Little Big Planet'],
    M: ['Minecraft', 'Mario', 'Metal Gear Solid'],
    N: ['Need for Speed', 'Ninja Gaiden'],
    O: ['Overwatch', 'Ori and the Blind Forest'],
    P: ['Pokemon', 'Portal', 'Pac-Man'],
    Q: ['Q*bert', 'Quest for Glory', 'Quake'],
    R: ['Red Dead Redemption', 'Ratchet and Clank'],
    S: ['Starcraft', 'Skyrim', 'Sonic', 'Spyro'],
    T: ['Tetris', 'The Last of Us', 'Tomb Raider'],
    U: ['Undertale', 'Uncharted'],
    V: ['Valorant', 'Valheim'],
    W: ['World of Warcraft', 'Witcher', 'Wolfenstein'],
    X: ['XCOM', 'Xenogears', 'Xenoblade Chronicles'],
    Y: ["Yoshi's Island", 'Yakuza'],
    Z: ['Zelda', 'Zork'],
  },

  tvshows: {
    A: ['Avatar', 'Arrow', 'Arrested Development'],
    B: ['Breaking Bad', 'Better Call Saul', 'Black Mirror'],
    C: ['Castle', 'Cheers', 'Community', 'Criminal Minds'],
    D: ['Dexter', 'Downton Abbey', 'Dark', 'Doctor Who'],
    E: ['Elementary', 'Euphoria', 'ER'],
    F: ['Friends', 'Fargo', 'Firefly', 'Family Guy'],
    G: ['Game of Thrones', "Grey's Anatomy", 'Glee'],
    H: ['House', 'Homeland', 'Heroes', 'Halt and Catch Fire'],
    I: ["It's Always Sunny", 'Invincible'],
    J: ['Justified', 'Jane the Virgin'],
    K: ['Killing Eve', 'Kingdom'],
    L: ['Lost', 'Loki', 'Line of Duty'],
    M: ['Mad Men', 'Mindhunter', 'Modern Family'],
    N: ['Narcos', 'NCIS'],
    O: ['Orange is the New Black', 'Outer Banks', 'One Tree Hill'],
    P: ['Parks and Recreation', 'Prison Break', 'Peaky Blinders'],
    Q: ['Quantum Leap', "Queen's Gambit"],
    R: ['Rick and Morty', 'Rings of Power'],
    S: ['Succession', 'Stranger Things', 'Seinfeld', 'Squid Game'],
    T: ['The Wire', 'The Sopranos', 'Ted Lasso'],
    U: ['Umbrella Academy', 'Unsolved Mysteries'],
    V: ['Vikings', 'Veep'],
    W: ['Walking Dead', 'Westworld', 'West Wing', 'White Lotus'],
    X: ['X-Files', 'Xena Warrior Princess'],
    Y: ['Young Sheldon', 'You'],
    Z: ['Zoo', 'Zombies'],
  },

  superheroes: {
    A: ['Aquaman', 'Ant-Man', 'Atom', 'Arrowette'],
    B: ['Batman', 'Black Panther', 'Black Widow', 'Batgirl'],
    C: ['Captain America', 'Cyclops', 'Captain Marvel'],
    D: ['Deadpool', 'Daredevil', 'Doctor Strange'],
    E: ['Elastigirl'],
    F: ['Flash', 'Falcon'],
    G: ['Green Lantern', 'Green Arrow', 'Groot', 'Ghost Rider'],
    H: ['Hulk', 'Hawkeye', 'Hawkman'],
    I: ['Iron Man', 'Invisible Woman', 'Iceman'],
    J: ['Jessica Jones'],
    K: ['Kick-Ass'],
    L: ['Luke Cage', 'Lightning Lad'],
    M: ['Ms. Marvel', 'Martian Manhunter', 'Moon Knight'],
    N: ['Nightwing', 'Namor', 'Nick Fury'],
    O: ['Oracle'],
    P: ['Professor X', 'Power Girl', 'Photon'],
    Q: ['Quicksilver'],
    R: ['Robin', 'Rocket Raccoon', 'Red Hood'],
    S: ['Superman', 'Spider-Man', 'Storm', 'She-Hulk'],
    T: ['Thor', 'The Tick'],
    U: ['Ultra Boy', 'Union Jack'],
    V: ['Vision', 'Venom'],
    W: ['Wonder Woman', 'Wolverine', 'Wasp'],
    X: ['X-23', 'Xavier'],
    Y: ['Yellowjacket'],
    Z: ['Zatanna', 'Zorro'],
  },

  mythology: {
    A: ['Apollo', 'Aphrodite', 'Athena', 'Ares', 'Anubis'],
    B: ['Bacchus', 'Bes', 'Brahma'],
    C: ['Cronus', 'Cupid'],
    D: ['Dionysus', 'Demeter'],
    E: ['Eros', 'Eris'],
    F: ['Freya', 'Frigg'],
    G: ['Gaia'],
    H: ['Hades', 'Hermes', 'Hera', 'Horus'],
    I: ['Iris', 'Isis'],
    J: ['Jupiter', 'Janus', 'Juno'],
    K: ['Khepri', 'Krishna', 'Kali'],
    L: ['Loki'],
    M: ['Mars', 'Mercury', 'Minerva', 'Morpheus'],
    N: ['Neptune', 'Nike', 'Nephthys'],
    O: ['Odin', 'Osiris'],
    P: ['Poseidon', 'Persephone', 'Pan'],
    Q: ['Quetzalcoatl'],
    R: ['Ra', 'Rhea'],
    S: ['Saturn', 'Shiva', 'Selene'],
    T: ['Thor', 'Triton', 'Tyr'],
    U: ['Uranus'],
    V: ['Vishnu', 'Venus', 'Vulcan'],
    W: ['Wadjet', 'Wepwawet', 'Wotan'],
    X: ['Xipe Totec', 'Xochiquetzal'],
    Y: ['Ymir'],
    Z: ['Zeus', 'Zephyrus'],
  },

  history: {
    A: ['Alexander the Great', 'Abraham Lincoln', 'Aristotle', 'Amelia Earhart'],
    B: ['Napoleon Bonaparte', 'Ludwig van Beethoven', 'Boudicca'],
    C: ['Cleopatra', 'Winston Churchill', 'Confucius', 'Christopher Columbus'],
    D: ['Charles Darwin', 'Leonardo da Vinci'],
    E: ['Albert Einstein', 'Queen Elizabeth I'],
    F: ['Benjamin Franklin', 'Anne Frank'],
    G: ['Galileo Galilei', 'Mahatma Gandhi', 'Genghis Khan'],
    H: ['Hannibal', 'Harriet Tubman', 'Hippocrates'],
    I: ['Ivan the Terrible'],
    J: ['Joan of Arc', 'Julius Caesar', 'Thomas Jefferson'],
    K: ['Martin Luther King', 'Johannes Kepler'],
    L: ['Abraham Lincoln', 'Leonardo da Vinci'],
    M: ['Marie Curie', 'Ferdinand Magellan', 'Marco Polo', 'Michelangelo'],
    N: ['Isaac Newton', 'Napoleon Bonaparte', 'Horatio Nelson'],
    O: ['Barack Obama', 'Oliver Cromwell'],
    P: ['Plato', 'Pocahontas', 'Pythagoras'],
    Q: ['Qin Shi Huang'],
    R: ['Theodore Roosevelt', 'Rembrandt', 'Richard the Lionheart'],
    S: ['William Shakespeare', 'Socrates', 'Sun Tzu'],
    T: ['Nikola Tesla', 'Tutankhamun', 'Thomas Edison'],
    U: ['Ulysses S. Grant'],
    V: ['Voltaire'],
    W: ['George Washington', 'Duke of Wellington'],
    X: ['Xerxes'],
    Y: ['Yuri Gagarin'],
    Z: ['Georgy Zhukov', 'Zheng He'],
  },

  dances: {
    A: ['Argentine Tango', 'Afrobeat', 'Aerobics Dance'],
    B: ['Ballet', 'Bachata', 'Bhangra', 'Ballroom', 'Breakdance'],
    C: ['Cha-Cha', 'Charleston', 'Country Line Dance'],
    D: ['Disco'],
    E: ['Electric Slide'],
    F: ['Foxtrot', 'Flamenco'],
    G: ['Garba'],
    H: ['Hip Hop', 'Highland Fling', 'Haka'],
    I: ['Irish Step Dancing'],
    J: ['Jive', 'Jazz Dance'],
    K: ['Kathak', 'Krump'],
    L: ['Lindy Hop', 'Latin Dance'],
    M: ['Mambo', 'Merengue', 'Moonwalk'],
    N: ['Northern Soul'],
    O: ['One-Step'],
    P: ['Polka', 'Paso Doble'],
    Q: ['Quickstep', 'Quadrille'],
    R: ['Rumba', 'Robot Dance'],
    S: ['Salsa', 'Samba', 'Swing'],
    T: ['Tango', 'Twist', 'Tap Dance'],
    U: ['Urban Dance'],
    V: ['Viennese Waltz', 'Voguing'],
    W: ['Waltz', 'Waacking'],
    X: ['Xaxado'],
    Y: ['Yangko'],
    Z: ['Zapateado', 'Zydeco'],
  },
};
