const CATEGORIES = {
  fruits:      'Fruits',
  animals:     'Animals',
  cities:      'World Cities',
  foods:       'Foods & Dishes',
  vegetables:  'Vegetables',
  sports:      'Sports',
  instruments: 'Musical Instruments',
  occupations: 'Occupations',
  birds:       'Birds',
  flowers:     'Flowers',
  trees:       'Trees',
  gemstones:   'Gemstones',
  dinosaurs:   'Dinosaurs',
  movies:      'Movies',
  games:       'Video Games',
  tvshows:     'TV Shows',
  superheroes: 'Superheroes',
  mythology:   'Mythological Deities',
  history:     'Historical Figures',
  dances:      'Dances',
};

const WORDS = {
  fruits: {
    A: ['Apple', 'Apricot', 'Avocado', 'Acai', 'Ackee', 'Asian Pear', 'Atemoya', 'Acerola', 'Ambarella', 'Araza'],
    B: ['Banana', 'Blueberry', 'Blackberry', 'Boysenberry', 'Breadfruit', 'Blood Orange', 'Bael', 'Bilberry', 'Bitter Orange', 'Barbadine'],
    C: ['Cherry', 'Coconut', 'Cranberry', 'Cantaloupe', 'Clementine', 'Currant', 'Cherimoya', 'Calamondin', 'Cloudberry', 'Capulin'],
    D: ['Dragonfruit', 'Durian', 'Date', 'Damson', 'Dewberry', 'Desert Lime', 'Duku'],
    E: ['Elderberry', 'Emblica', 'Etrog', 'Entawak'],
    F: ['Fig', 'Feijoa', 'Finger Lime', 'Fuyu Persimmon', 'False Mastic'],
    G: ['Grape', 'Guava', 'Grapefruit', 'Gooseberry', 'Greengage', 'Grumichama', 'Gamboge', 'Gac'],
    H: ['Honeydew', 'Huckleberry', 'Hackberry', 'Horned Melon'],
    I: ['Ilama', 'Indian Plum', 'Imbe', 'Ice Apple', 'Inga Berry'],
    J: ['Jackfruit', 'Jujube', 'Jaboticaba', 'Java Plum', 'Jocote', 'Jobo'],
    K: ['Kiwi', 'Kumquat', 'Kiwano', 'Kaki', 'Kaffir Lime', 'Kei Apple'],
    L: ['Lemon', 'Lime', 'Lychee', 'Longan', 'Loganberry', 'Langsat', 'Lucuma', 'Limequat'],
    M: ['Mango', 'Melon', 'Mulberry', 'Mandarin', 'Maracuja', 'Mamey', 'Marula', 'Miracle Fruit'],
    N: ['Nectarine', 'Noni', 'Naranjilla', 'Natal Plum', 'Nance'],
    O: ['Orange', 'Olive', 'Ortanique', 'Osage Orange', 'Orangelo'],
    P: ['Peach', 'Pear', 'Pineapple', 'Plum', 'Pomegranate', 'Papaya', 'Passion Fruit', 'Persimmon', 'Pawpaw', 'Pitaya'],
    Q: ['Quince', 'Quenepa', 'Queensland Plum', 'Quandong'],
    R: ['Raspberry', 'Rambutan', 'Redcurrant', 'Rose Apple', 'Rollinia', 'Riberry'],
    S: ['Strawberry', 'Star Fruit', 'Sapodilla', 'Soursop', 'Sugar Apple', 'Salak', 'Santol'],
    T: ['Tangerine', 'Tamarind', 'Tomato', 'Tamarillo', 'Tangelo', 'Tayberry'],
    U: ['Ugli Fruit', 'Ugni', 'Uva Ursi'],
    V: ['Valencia Orange', 'Voavanga', 'Vanilla Bean'],
    W: ['Watermelon', 'Wolfberry', 'Wampee', 'White Currant', 'Wild Strawberry'],
    X: ['Xigua', 'Ximenia', 'Xoconostle'],
    Y: ['Yuzu', 'Yellow Passion Fruit', 'Yangmei', 'Yellow Plum', 'Yumberry'],
    Z: ['Ziziphus', 'Zhe'],
  },

  animals: {
    A: ['Alligator', 'Antelope', 'Armadillo', 'Aardvark', 'Alpaca', 'Anaconda', 'Axolotl', 'Aye-aye', 'African Wild Dog'],
    B: ['Bear', 'Buffalo', 'Baboon', 'Bison', 'Bat', 'Beaver', 'Binturong', 'Boar', 'Bongo', 'Blue Whale'],
    C: ['Cheetah', 'Crocodile', 'Camel', 'Cobra', 'Chimpanzee', 'Coyote', 'Caracal', 'Capybara', 'Chinchilla'],
    D: ['Deer', 'Dolphin', 'Dingo', 'Donkey', 'Dhole', 'Dugong', 'Dik-dik'],
    E: ['Elephant', 'Elk', 'Emu', 'Echidna', 'Ermine'],
    F: ['Fox', 'Frog', 'Ferret', 'Flamingo', 'Falcon', 'Flying Squirrel', 'Fishing Cat'],
    G: ['Gorilla', 'Giraffe', 'Gecko', 'Gazelle', 'Goat', 'Gemsbok', 'Giant Anteater', 'Gray Wolf'],
    H: ['Hippo', 'Horse', 'Hyena', 'Hamster', 'Hedgehog', 'Hartebeest', 'Hare'],
    I: ['Iguana', 'Impala', 'Ibis', 'Indri'],
    J: ['Jaguar', 'Jellyfish', 'Jackal', 'Japanese Macaque'],
    K: ['Kangaroo', 'Koala', 'Komodo Dragon', 'Kinkajou', 'Kudu'],
    L: ['Lion', 'Leopard', 'Llama', 'Lynx', 'Lemur', 'Liger', 'Loris'],
    M: ['Monkey', 'Moose', 'Meerkat', 'Mouse', 'Mongoose', 'Manatee', 'Marten', 'Markhor'],
    N: ['Narwhal', 'Newt', 'Numbat', 'Nile Monitor'],
    O: ['Orangutan', 'Ostrich', 'Otter', 'Octopus', 'Owl', 'Ocelot', 'Oryx'],
    P: ['Panda', 'Penguin', 'Puma', 'Panther', 'Platypus', 'Porcupine', 'Proboscis Monkey', 'Pangolin'],
    Q: ['Quokka', 'Quoll', 'Quetzal', 'Quahog'],
    R: ['Rabbit', 'Rhinoceros', 'Raccoon', 'Rattlesnake', 'Red Panda', 'Ring-tailed Lemur'],
    S: ['Snake', 'Shark', 'Sloth', 'Seal', 'Squirrel', 'Snow Leopard', 'Serval', 'Salamander'],
    T: ['Tiger', 'Turtle', 'Tapir', 'Toucan', 'Tasmanian Devil', 'Tarsier', 'Tamarin'],
    U: ['Uakari', 'Urial', 'Urchin'],
    V: ['Vulture', 'Viper', 'Vicuna', 'Vervet Monkey'],
    W: ['Wolf', 'Whale', 'Wombat', 'Walrus', 'Weasel', 'Wolverine', 'Wildebeest'],
    X: ['Xerus', 'Xenops', 'X-ray Tetra'],
    Y: ['Yak', 'Yellow Mongoose', 'Yacare Caiman', 'Yabby'],
    Z: ['Zebra', 'Zebu', 'Zorilla'],
  },

  cities: {
    A: ['Amsterdam', 'Athens', 'Auckland', 'Ankara', 'Accra', 'Algiers', 'Abu Dhabi', 'Almaty', 'Amman', 'Addis Ababa'],
    B: ['Barcelona', 'Bangkok', 'Buenos Aires', 'Berlin', 'Beijing', 'Brussels', 'Bogota', 'Beirut', 'Bucharest', 'Bangalore'],
    C: ['Cairo', 'Chicago', 'Copenhagen', 'Casablanca', 'Cape Town', 'Colombo', 'Caracas', 'Calgary', 'Chisinau'],
    D: ['Dubai', 'Delhi', 'Dublin', 'Dhaka', 'Detroit', 'Dakar', 'Doha', 'Damascus'],
    E: ['Edinburgh', 'Entebbe', 'El Paso', 'Essen'],
    F: ['Florence', 'Frankfurt', 'Fuzhou', 'Freetown'],
    G: ['Geneva', 'Glasgow', 'Guangzhou', 'Guadalajara', 'Gothenburg', 'Gaza'],
    H: ['Hong Kong', 'Havana', 'Hamburg', 'Helsinki', 'Hanoi', 'Harare', 'Houston'],
    I: ['Istanbul', 'Islamabad', 'Izmir', 'Indianapolis'],
    J: ['Jakarta', 'Jerusalem', 'Johannesburg', 'Jaipur', 'Jeddah'],
    K: ['Karachi', 'Kyoto', 'Kuala Lumpur', 'Kinshasa', 'Kathmandu', 'Kabul', 'Kiev'],
    L: ['London', 'Los Angeles', 'Lima', 'Lisbon', 'Lagos', 'Lyon', 'Lahore', 'Luanda'],
    M: ['Madrid', 'Moscow', 'Mumbai', 'Montreal', 'Melbourne', 'Manila', 'Milan', 'Minsk'],
    N: ['New York', 'Nairobi', 'Naples', 'New Delhi', 'Nagoya', 'Nicosia'],
    O: ['Oslo', 'Ottawa', 'Osaka', 'Odessa', 'Ouagadougou'],
    P: ['Paris', 'Prague', 'Perth', 'Philadelphia', 'Porto', 'Panama City', 'Phnom Penh'],
    Q: ['Quebec City', 'Quito', 'Quezon City'],
    R: ['Rome', 'Rio de Janeiro', 'Rotterdam', 'Riyadh', 'Reykjavik', 'Rabat'],
    S: ['Sydney', 'Seoul', 'Singapore', 'Stockholm', 'Shanghai', 'Santiago', 'San Francisco'],
    T: ['Tokyo', 'Toronto', 'Tehran', 'Tel Aviv', 'Taipei', 'Tashkent', 'Tunis'],
    U: ['Ulaanbaatar', 'Utrecht', 'Ufa', 'Ushuaia'],
    V: ['Vienna', 'Vancouver', 'Venice', 'Vilnius', 'Vladivostok', 'Valletta'],
    W: ['Warsaw', 'Washington DC', 'Wellington', 'Winnipeg', 'Wuhan'],
    X: ["Xi'an"],
    Y: ['Yokohama', 'Yangon', 'Yerevan', 'Yaounde'],
    Z: ['Zurich', 'Zagreb', 'Zanzibar', 'Zhengzhou'],
  },

  foods: {
    A: ['Apple Pie', 'Avocado Toast', 'Alfredo Pasta', 'Asparagus Soup', 'Arancini', 'Adobo', 'Antipasto', 'Aglio e Olio'],
    B: ['Burger', 'Burrito', 'Baklava', 'Bruschetta', 'Bibimbap', 'Borscht', 'Biryani', 'Beef Stew'],
    C: ['Curry', 'Carbonara', 'Croissant', 'Chili', 'Cheesecake', 'Crepe', 'Ceviche', 'Couscous'],
    D: ['Dumpling', 'Dal', 'Donut', 'Duck Confit', 'Danish Pastry', 'Dhokla'],
    E: ['Enchilada', 'Empanada', 'Eggs Benedict', 'Escargot', 'Eel Sushi'],
    F: ['French Fries', 'Falafel', 'Fish and Chips', 'Fried Rice', 'Fondue', 'French Toast', 'Frittata'],
    G: ['Gyoza', 'Gumbo', 'Guacamole', 'Gazpacho', 'Gelato', 'Gnocchi', 'Galette'],
    H: ['Hummus', 'Hot Dog', 'Hash Browns', 'Halloumi', 'Hot Pot', 'Honey Cake'],
    I: ['Ice Cream', 'Idli', 'Irish Stew'],
    J: ['Jambalaya', 'Jerk Chicken', 'Jollof Rice', 'Japanese Curry'],
    K: ['Kebab', 'Kimchi', 'Katsu Curry', 'Knish', 'Kulfi'],
    L: ['Lasagna', 'Lobster', 'Lentil Soup', 'Latke', 'Lamb Chops', 'Lo Mein'],
    M: ['Moussaka', 'Miso Soup', 'Macaroni', 'Mole', 'Momos', 'Meatballs', 'Macaron'],
    N: ['Nachos', 'Noodles', 'Naan', 'Nougat', 'Nasi Goreng'],
    O: ['Omelette', 'Onion Rings', 'Okonomiyaki', 'Oysters'],
    P: ['Pizza', 'Paella', 'Pad Thai', 'Pancakes', 'Pho', 'Pierogi', 'Pretzels', 'Poutine'],
    Q: ['Quiche', 'Quesadilla', 'Quindim'],
    R: ['Ramen', 'Risotto', 'Ravioli', 'Rendang', 'Rotisserie Chicken'],
    S: ['Sushi', 'Steak', 'Sandwich', 'Shawarma', 'Samosa', 'Souvlaki', 'Spring Roll'],
    T: ['Tacos', 'Tikka Masala', 'Tempura', 'Tiramisu', 'Tom Yum', 'Tagine'],
    U: ['Udon', 'Ugali', 'Ube Cake'],
    V: ['Vichyssoise', 'Vindaloo', 'Veal Scallopini'],
    W: ['Waffle', 'Wontons', 'White Rice', 'Wiener Schnitzel'],
    X: ['Xiaolongbao', 'Xo Sauce'],
    Y: ['Yakitori', 'Yogurt', 'Yorkshire Pudding', 'Yakisoba'],
    Z: ['Zabaglione', 'Ziti', 'Zeppole', 'Zucchini Fritters'],
  },

  vegetables: {
    A: ['Asparagus', 'Artichoke', 'Arugula', 'Avocado', 'Acorn Squash', 'Amaranth'],
    B: ['Broccoli', 'Brussels Sprouts', 'Beetroot', 'Bok Choy', 'Bell Pepper', 'Broad Bean', 'Butternut Squash'],
    C: ['Carrot', 'Cauliflower', 'Cabbage', 'Celery', 'Cucumber', 'Chard', 'Chickpea', 'Celeriac'],
    D: ['Daikon', 'Dandelion Greens', 'Delicata Squash'],
    E: ['Eggplant', 'Edamame', 'Endive', 'Escarole'],
    F: ['Fennel', 'Fiddlehead Fern', 'French Bean'],
    G: ['Garlic', 'Ginger', 'Green Onion', 'Galangal', 'Gai Lan'],
    H: ['Horseradish', 'Heart of Palm', 'Haricot Bean'],
    I: ['Indian Spinach', 'Iceberg Lettuce'],
    J: ['Jicama', 'Jerusalem Artichoke', 'Jalapeno'],
    K: ['Kale', 'Kohlrabi', 'Komatsuna'],
    L: ['Leek', 'Lettuce', 'Lentil', 'Lima Bean'],
    M: ['Mushroom', 'Mustard Greens', 'Mangetout', 'Mung Bean', 'Mizuna'],
    N: ['Napa Cabbage', 'Nori'],
    O: ['Onion', 'Okra', 'Oyster Mushroom'],
    P: ['Potato', 'Pea', 'Pepper', 'Pumpkin', 'Parsnip', 'Purple Cabbage'],
    Q: ['Quinoa'],
    R: ['Radish', 'Rutabaga', 'Radicchio', 'Red Cabbage', 'Rocket'],
    S: ['Spinach', 'Sweet Potato', 'Squash', 'Scallion', 'Snap Pea', 'Sunchoke'],
    T: ['Tomato', 'Turnip', 'Taro', 'Tomatillo'],
    U: ['Ulluco', 'Upo'],
    V: ['Vine Tomato', 'Velvet Bean'],
    W: ['Watercress', 'Water Chestnut', 'Wakame', 'White Radish'],
    X: ['Xigua'],
    Y: ['Yam', 'Yuca', 'Yellow Squash', 'Yardlong Bean'],
    Z: ['Zucchini', 'Zucchini Flower'],
  },

  sports: {
    A: ['Archery', 'Athletics', 'American Football', 'Aikido', 'Alpine Skiing', 'Arm Wrestling', 'Aquatics'],
    B: ['Basketball', 'Baseball', 'Badminton', 'Boxing', 'Bowling', 'Biathlon', 'Bobsled'],
    C: ['Cricket', 'Cycling', 'Curling', 'Canoeing', 'Climbing', 'Cross Country', 'Cheerleading'],
    D: ['Diving', 'Discus Throw', 'Dodgeball', 'Dressage'],
    E: ['Equestrian', 'Endurance Racing', 'Extreme Sports'],
    F: ['Football', 'Fencing', 'Figure Skating', 'Field Hockey', 'Free Diving'],
    G: ['Golf', 'Gymnastics', 'Go-Karting'],
    H: ['Hockey', 'Handball', 'High Jump', 'Hurdles', 'Hammer Throw', 'Hang Gliding'],
    I: ['Ice Hockey', 'Ice Skating', 'Indoor Volleyball'],
    J: ['Judo', 'Javelin', 'Jai Alai', 'Jousting', 'Jet Skiing'],
    K: ['Karate', 'Kayaking', 'Kickboxing', 'Kendo'],
    L: ['Lacrosse', 'Luge', 'Long Jump', 'Log Rolling'],
    M: ['Marathon', 'Mountaineering', 'Mixed Martial Arts', 'Motocross'],
    N: ['Netball', 'Nordic Skiing', 'Nordic Combined'],
    O: ['Olympic Weightlifting', 'Obstacle Course Racing'],
    P: ['Polo', 'Ping Pong', 'Parkour', 'Pentathlon', 'Para Athletics'],
    Q: ['Quoits', 'Quadrathlon'],
    R: ['Rugby', 'Rowing', 'Rock Climbing', 'Racquetball'],
    S: ['Swimming', 'Soccer', 'Skiing', 'Squash', 'Surfing', 'Skateboarding', 'Softball'],
    T: ['Tennis', 'Track and Field', 'Taekwondo', 'Triathlon', 'Table Tennis'],
    U: ['Ultimate Frisbee', 'Ultramarathon', 'Underwater Hockey'],
    V: ['Volleyball', 'Vaulting'],
    W: ['Wrestling', 'Water Polo', 'Weightlifting', 'Windsurfing', 'Wakeboarding'],
    X: ['X-Games'],
    Y: ['Yoga', 'Yachting'],
    Z: ['Zorbing'],
  },

  instruments: {
    A: ['Accordion', 'Alto Saxophone', 'Autoharp', 'Acoustic Guitar'],
    B: ['Banjo', 'Bass Guitar', 'Bagpipes', 'Bassoon', 'Balalaika', 'Bouzouki'],
    C: ['Clarinet', 'Cello', 'Cornet', 'Castanets', 'Contrabass', 'Crwth'],
    D: ['Drums', 'Dulcimer', 'Didgeridoo', 'Double Bass'],
    E: ['Electric Guitar', 'Electric Violin', 'Euphonium'],
    F: ['Flute', 'French Horn', 'Fiddle', 'Flugelhorn'],
    G: ['Guitar', 'Grand Piano', 'Gong', 'Glass Harmonica'],
    H: ['Harmonica', 'Harp', 'Harpsichord', 'Horn'],
    I: ['Irish Flute', 'Irish Uilleann Pipes'],
    J: ['Jazz Trumpet'],
    K: ['Keyboard', 'Koto', 'Kalimba'],
    L: ['Lute', 'Lyre'],
    M: ['Mandolin', 'Marimba', 'Melodica'],
    N: ['Nose Flute'],
    O: ['Oboe', 'Organ', 'Ocarina'],
    P: ['Piano', 'Piccolo', 'Pan Flute'],
    Q: ['Qin', 'Qanun'],
    R: ['Recorder', 'Rhodes Piano'],
    S: ['Saxophone', 'Sitar', 'Sousaphone', 'Steel Drum', 'Snare Drum', 'Synthesizer'],
    T: ['Trumpet', 'Trombone', 'Tuba', 'Tambourine', 'Theremin'],
    U: ['Ukulele'],
    V: ['Violin', 'Viola', 'Vibraphone'],
    W: ['Washboard', 'Wind Chimes', 'Whistle'],
    X: ['Xylophone'],
    Y: ['Yangqin', 'Yueqin'],
    Z: ['Zither', 'Zurna'],
  },

  occupations: {
    A: ['Actor', 'Architect', 'Accountant', 'Astronaut', 'Archaeologist', 'Animator', 'Anesthesiologist'],
    B: ['Baker', 'Builder', 'Banker', 'Biologist', 'Barber', 'Botanist', 'Biochemist'],
    C: ['Chef', 'Carpenter', 'Cashier', 'Chemist', 'Coach', 'Counselor', 'Chiropractor', 'Conductor'],
    D: ['Doctor', 'Dentist', 'Detective', 'Designer', 'Driver', 'Data Scientist', 'Dermatologist'],
    E: ['Engineer', 'Electrician', 'Editor', 'Economist', 'EMT'],
    F: ['Farmer', 'Firefighter', 'Florist', 'Financial Analyst'],
    G: ['Gardener', 'Geologist', 'Graphic Designer', 'Geneticist'],
    H: ['Historian', 'Hunter', 'Hydrologist', 'Hairdresser'],
    I: ['Interpreter', 'Inspector', 'Illustrator', 'Investment Banker'],
    J: ['Judge', 'Journalist', 'Jeweler', 'Janitor'],
    K: ['Kinesiologist'],
    L: ['Lawyer', 'Librarian', 'Locksmith', 'Linguist'],
    M: ['Mechanic', 'Musician', 'Manager', 'Mathematician', 'Marine Biologist'],
    N: ['Nurse', 'Nutritionist', 'Navigator', 'Neurologist'],
    O: ['Optician', 'Operator', 'Obstetrician'],
    P: ['Photographer', 'Pilot', 'Plumber', 'Programmer', 'Pharmacist', 'Psychiatrist'],
    Q: ['Quilter', 'Quarryman'],
    R: ['Reporter', 'Ranger', 'Researcher', 'Radiologist'],
    S: ['Surgeon', 'Scientist', 'Salesperson', 'Sailor', 'Software Engineer', 'Sociologist'],
    T: ['Teacher', 'Technician', 'Therapist', 'Translator', 'Toxicologist'],
    U: ['Undertaker', 'Urban Planner', 'UX Designer'],
    V: ['Veterinarian', 'Violinist', 'Video Game Designer'],
    W: ['Writer', 'Welder', 'Waiter', 'Web Developer'],
    X: ['Xylographer'],
    Y: ['Yoga Instructor', 'Youth Counselor'],
    Z: ['Zoologist', 'Zookeeper'],
  },

  birds: {
    A: ['Albatross', 'Avocet', 'American Robin', 'Auklet', 'Anhinga', 'Amazon Parrot'],
    B: ['Bluebird', 'Blue Jay', 'Bald Eagle', 'Barn Owl', 'Bulfinch', 'Bunting'],
    C: ['Cardinal', 'Crane', 'Crow', 'Cockatoo', 'Canary', 'Condor', 'Common Loon'],
    D: ['Duck', 'Dove', 'Dodo', 'Dunlin'],
    E: ['Eagle', 'Egret', 'Emu', 'Eastern Bluebird'],
    F: ['Flamingo', 'Falcon', 'Finch', 'Frigate Bird'],
    G: ['Goose', 'Goldfinch', 'Great Horned Owl', 'Golden Eagle', 'Grouse'],
    H: ['Hawk', 'Heron', 'Hummingbird', 'Hoopoe', 'Harrier'],
    I: ['Ibis', 'Indigo Bunting'],
    J: ['Jay', 'Junco', 'Java Sparrow'],
    K: ['Kingfisher', 'Kiwi', 'Kookaburra', 'Kestrel'],
    L: ['Lark', 'Loon', 'Lyrebird', 'Lapwing'],
    M: ['Macaw', 'Mockingbird', 'Magpie', 'Myna', 'Meadowlark'],
    N: ['Nightingale', 'Nighthawk', 'Nutcracker'],
    O: ['Owl', 'Oriole', 'Osprey', 'Ovenbird'],
    P: ['Parrot', 'Pelican', 'Penguin', 'Peacock', 'Pigeon', 'Puffin'],
    Q: ['Quail', 'Quetzal', 'Quelea'],
    R: ['Robin', 'Raven', 'Roadrunner', 'Red Kite', 'Rook'],
    S: ['Sparrow', 'Starling', 'Swan', 'Stork', 'Snowy Owl', 'Sandpiper'],
    T: ['Toucan', 'Turkey', 'Tern', 'Teal', 'Thrush'],
    U: ['Umbrellabird', 'Upland Sandpiper'],
    V: ['Vulture', 'Verdin'],
    W: ['Warbler', 'Woodpecker', 'Wren', 'White Stork'],
    X: ['Xenops'],
    Y: ['Yellow Warbler', 'Yellowhammer', 'Yellow-bellied Sapsucker'],
    Z: ['Zebra Finch', 'Zone-tailed Hawk', 'Zitting Cisticola'],
  },

  flowers: {
    A: ['Amaryllis', 'Azalea', 'Alstroemeria', 'Aster', 'Agapanthus', 'Anemone'],
    B: ['Bluebell', 'Black-Eyed Susan', 'Begonia', "Baby's Breath", 'Bird of Paradise', 'Bleeding Heart'],
    C: ['Carnation', 'Chrysanthemum', 'Cosmos', 'Crocus', 'Cyclamen', 'Calla Lily', 'Candytuft'],
    D: ['Dahlia', 'Daisy', 'Delphinium', 'Daffodil', 'Dianthus'],
    E: ['Edelweiss', 'Echinacea', 'Evening Primrose', 'Eustoma'],
    F: ['Freesia', 'Foxglove', 'Fuchsia', 'Forget-Me-Not'],
    G: ['Gardenia', 'Gladiolus', 'Geranium', 'Gypsophila', 'Gerbera'],
    H: ['Hyacinth', 'Hibiscus', 'Hollyhock', 'Heather', 'Hellebore'],
    I: ['Iris', 'Impatiens', 'Ice Plant'],
    J: ['Jasmine', 'Jonquil', "Jacob's Ladder"],
    K: ['Kangaroo Paw', 'Kniphofia'],
    L: ['Lavender', 'Lily', 'Lotus', 'Larkspur', 'Lisianthus'],
    M: ['Magnolia', 'Marigold', 'Morning Glory', 'Moonflower', 'Muscari'],
    N: ['Narcissus', 'Nemesia', 'Nigella'],
    O: ['Orchid', 'Oxeye Daisy', 'Oriental Poppy'],
    P: ['Pansy', 'Peony', 'Poppy', 'Primrose', 'Phlox', 'Petunia'],
    Q: ["Queen Anne's Lace", 'Quince Blossom'],
    R: ['Rose', 'Ranunculus', 'Red Clover', 'Rudbeckia'],
    S: ['Sunflower', 'Sweet Pea', 'Snapdragon', 'Stock', 'Statice'],
    T: ['Tulip', 'Tiger Lily', 'Thistle', 'Tuberose'],
    U: ['Ursinia'],
    V: ['Violet', 'Verbena', 'Veronica', 'Viburnum'],
    W: ['Wisteria', 'Water Lily', 'Wallflower', 'Wild Rose'],
    X: ['Xeranthemum', 'Xiphium Iris'],
    Y: ['Yarrow', 'Yellow Rose', 'Yucca Flower'],
    Z: ['Zinnia', 'Zebra Plant Flower', 'Zephyranthes'],
  },

  trees: {
    A: ['Ash', 'Apple Tree', 'Acacia', 'Alder', 'Aspen', 'Avocado Tree'],
    B: ['Birch', 'Beech', 'Baobab', 'Bonsai', 'Balsa', 'Black Walnut', 'Barbados Cherry'],
    C: ['Cedar', 'Cherry Tree', 'Cypress', 'Chestnut', 'Catalpa', 'Coffee Tree'],
    D: ['Douglas Fir', 'Date Palm', 'Dawn Redwood'],
    E: ['Elm', 'Eucalyptus', 'Elder', 'English Oak'],
    F: ['Fig Tree', 'Fir', 'Flame Tree'],
    G: ['Ginkgo', 'Gum Tree', 'Goldenrain Tree'],
    H: ['Horse Chestnut', 'Hazel', 'Hawthorn', 'Hemlock'],
    I: ['Irish Yew', 'Indian Rosewood', 'Ironwood'],
    J: ['Juniper', 'Jacaranda', 'Japanese Maple'],
    K: ['Kapok', 'Kentucky Coffee Tree', 'Kauri'],
    L: ['Larch', 'Lemon Tree', 'Lime Tree', 'Laurel'],
    M: ['Maple', 'Magnolia', 'Mulberry', 'Monkey Puzzle', 'Moreton Bay Fig'],
    N: ['Norway Spruce', 'Neem', 'Northern Red Oak'],
    O: ['Oak', 'Olive Tree', 'Oregon Pine'],
    P: ['Pine', 'Palm', 'Poplar', 'Plum Tree', 'Pawpaw Tree'],
    Q: ['Quaking Aspen', 'Quince Tree', 'Queensland Maple'],
    R: ['Redwood', 'Rowan', 'Red Maple', 'River Birch'],
    S: ['Spruce', 'Sycamore', 'Sequoia', 'Silver Birch', 'Sweet Gum'],
    T: ['Teak', 'Tulip Tree', 'Tamarind', 'Tamarack'],
    U: ['Umbrella Tree'],
    V: ['Valley Oak', 'Viburnum Tree'],
    W: ['Walnut', 'Willow', 'White Oak', 'Wych Elm'],
    X: ['Xylosma', 'Xanthoceras'],
    Y: ['Yew', 'Yellow Birch', 'Yellowwood'],
    Z: ['Zelkova', 'Zebrawood'],
  },

  gemstones: {
    A: ['Amethyst', 'Aquamarine', 'Amber', 'Alexandrite', 'Agate', 'Amazonite'],
    B: ['Beryl', 'Bloodstone', 'Blue Topaz', 'Benitoite'],
    C: ['Citrine', 'Coral', 'Carnelian', 'Cat\'s Eye', 'Chrysoberyl', 'Chrome Diopside'],
    D: ['Diamond', 'Danburite', 'Diopside'],
    E: ['Emerald', 'Epidote', 'Enstatite'],
    F: ['Fire Opal', 'Fluorite', 'Feldspar'],
    G: ['Garnet', 'Goshenite', 'Grossular', 'Goldstone'],
    H: ['Heliodor', 'Howlite', 'Hematite', 'Hessonite'],
    I: ['Iolite', 'Indicolite'],
    J: ['Jade', 'Jasper', 'Jet', 'Jadeite'],
    K: ['Kunzite', 'Kyanite'],
    L: ['Lapis Lazuli', 'Labradorite', 'Larimar', 'Lepidolite'],
    M: ['Moonstone', 'Malachite', 'Morganite', 'Moldavite'],
    N: ['Nephrite', 'Nuummite'],
    O: ['Onyx', 'Opal', 'Obsidian'],
    P: ['Peridot', 'Pearl', 'Pyrite', 'Pink Sapphire'],
    Q: ['Quartz', 'Quartzite'],
    R: ['Ruby', 'Rose Quartz', 'Rhodonite', 'Rhodochrosite'],
    S: ['Sapphire', 'Spinel', 'Sunstone', 'Sodalite', 'Smithsonite'],
    T: ['Topaz', 'Turquoise', 'Tourmaline', "Tiger's Eye"],
    U: ['Unakite', 'Ulexite'],
    V: ['Variscite', 'Verdite'],
    W: ['Watermelon Tourmaline', 'White Opal', 'White Jade'],
    X: ['Xanthite', 'Xenotime'],
    Y: ['Yellow Sapphire', 'Yellow Diamond'],
    Z: ['Zircon', 'Zoisite'],
  },

  dinosaurs: {
    A: ['Allosaurus', 'Ankylosaurus', 'Apatosaurus', 'Argentinosaurus', 'Abelisaurus', 'Altirhinus'],
    B: ['Brachiosaurus', 'Brontosaurus', 'Baryonyx', 'Barosaurus', 'Beipiaosaurus'],
    C: ['Carnotaurus', 'Compsognathus', 'Carcharodontosaurus', 'Ceratosaurus', 'Camarasaurus'],
    D: ['Diplodocus', 'Deinonychus', 'Dilophosaurus', 'Dromaeosaurus'],
    E: ['Edmontosaurus', 'Euoplocephalus', 'Einiosaurus', 'Edmontonia'],
    F: ['Fukuiraptor', 'Futabasaurus'],
    G: ['Giganotosaurus', 'Gallimimus', 'Gasosaurus', 'Gorgosaurus'],
    H: ['Hadrosaurus', 'Hypsilophodon'],
    I: ['Iguanodon', 'Irritator'],
    J: ['Jeholornis', 'Janenschia', 'Jobaria'],
    K: ['Kentrosaurus', 'Kronosaurus', 'Kosmoceratops'],
    L: ['Lambeosaurus', 'Lesothosaurus', 'Leaellynasaura'],
    M: ['Megalosaurus', 'Maiasaura', 'Muttaburrasaurus', 'Mapusaurus'],
    N: ['Neovenator', 'Nigersaurus'],
    O: ['Oviraptor', 'Ornithomimus', 'Ouranosaurus'],
    P: ['Parasaurolophus', 'Pachycephalosaurus', 'Pteranodon', 'Plateosaurus', 'Protoceratops'],
    Q: ['Qantassaurus', 'Quaesitosaurus', 'Quilmesaurus'],
    R: ['Raptor', 'Rugops', 'Rebbachisaurus'],
    S: ['Stegosaurus', 'Spinosaurus', 'Sauroposeidon', 'Saurolophus', 'Saltasaurus'],
    T: ['Triceratops', 'Tyrannosaurus', 'Therizinosaurus', 'Troodon', 'Torosaurus'],
    U: ['Utahraptor', 'Ugrosaurus', 'Unenlagia'],
    V: ['Velociraptor', 'Vulcanodon'],
    W: ['Wuerhosaurus', 'Wannanosaurus'],
    X: ['Xenotarsosaurus', 'Xiaosaurus', 'Xuanhanosaurus'],
    Y: ['Yangchuanosaurus', 'Yandusaurus'],
    Z: ['Zuniceratops', 'Zhuchengtyrannus'],
  },

  movies: {
    A: ['Avatar', 'Aliens', 'Aladdin', 'Arrival', 'Amadeus', 'American Beauty'],
    B: ['Batman', 'Braveheart', 'Blade Runner', 'Black Panther', 'Back to the Future', 'Beauty and the Beast'],
    C: ['Casablanca', 'Clueless', 'Captain America', 'Cinderella', 'Cast Away'],
    D: ['Die Hard', 'Dune', 'Dunkirk', 'Dark Knight', 'District 9', 'Deadpool'],
    E: ['Elf', 'ET', 'Everything Everywhere All At Once', 'Eternal Sunshine', 'Encanto'],
    F: ['Forrest Gump', 'Frozen', 'Fight Club', 'Finding Nemo', 'Full Metal Jacket', 'Ferris Bueller'],
    G: ['Gladiator', 'Goodfellas', 'Grease', 'Get Out', 'Ghostbusters', 'Gran Torino'],
    H: ['Harry Potter', 'Home Alone', 'Her', 'Heat', 'Halloween', 'Hunt for the Wilderpeople'],
    I: ['Inception', 'Iron Man', 'Interstellar', 'Into the Wild'],
    J: ['Jaws', 'Joker', 'Jurassic Park', 'Jumanji', 'John Wick'],
    K: ['Killers of the Flower Moon', 'King Kong', 'Knives Out'],
    L: ['Lion King', 'La La Land', 'Lego Movie', 'Lawrence of Arabia', 'Luca'],
    M: ['Matrix', 'Mad Max', 'Moana', 'Mulan', 'Moonlight', 'Midsommar'],
    N: ['No Country for Old Men', 'Nope', 'Nomadland'],
    O: ['Oppenheimer', "Ocean's Eleven", 'Oldboy'],
    P: ['Pulp Fiction', 'Pirates of the Caribbean', 'Parasite', "Pan's Labyrinth"],
    Q: ['Quiz Show', 'Quantum of Solace', 'Queen'],
    R: ['Rocky', 'Ratatouille', 'Raiders of the Lost Ark', 'Rear Window'],
    S: ['Star Wars', 'Shrek', 'Spider-Man', 'Saving Private Ryan', "Schindler's List"],
    T: ['Titanic', 'Top Gun', 'Toy Story', 'The Godfather', 'The Shining'],
    U: ['Up', 'Uncut Gems', 'Unbreakable'],
    V: ['V for Vendetta', 'Vertigo', 'Volver'],
    W: ['Wall-E', 'Wonder Woman', 'Wizard of Oz', 'Whiplash'],
    X: ['X-Men', 'XXX'],
    Y: ['Yesterday', 'Young Frankenstein', 'Your Name'],
    Z: ['Zootopia', 'Zodiac', 'Zorro', 'Zero Dark Thirty'],
  },

  games: {
    A: ["Assassin's Creed", 'Animal Crossing', 'Among Us', 'Apex Legends'],
    B: ['Batman Arkham', 'Borderlands', 'Bioshock', "Baldur's Gate", 'Battlefield'],
    C: ['Civilization', 'Call of Duty', 'Crash Bandicoot', 'Cuphead', 'Control'],
    D: ['Doom', 'Dark Souls', 'Donkey Kong', 'Dragon Age', 'Dead Space'],
    E: ['Elder Scrolls', 'Earthworm Jim', 'Elden Ring', 'Everquest'],
    F: ['Final Fantasy', 'Fortnite', 'Fallout', 'Fez', 'Far Cry'],
    G: ['God of War', 'Grand Theft Auto', 'Gears of War', 'Ghost of Tsushima'],
    H: ['Halo', 'Half-Life', 'Hollow Knight', 'Hogwarts Legacy', 'Horizon'],
    I: ['Ico', 'Into the Breach', 'Injustice', 'Inside'],
    J: ['Journey', 'Just Dance', 'Jet Set Radio'],
    K: ['Kirby', 'Kingdom Hearts', 'Katamari Damacy'],
    L: ['Legend of Zelda', 'Left 4 Dead', 'Little Big Planet', "Luigi's Mansion"],
    M: ['Minecraft', 'Mario', 'Metal Gear Solid', 'Mass Effect', 'Monster Hunter'],
    N: ['Need for Speed', 'Ninja Gaiden', 'NieR Automata'],
    O: ['Overwatch', 'Ori and the Blind Forest', 'Outer Wilds', 'Octopath Traveler'],
    P: ['Pokemon', 'Portal', 'Pac-Man', 'Persona', 'Prince of Persia'],
    Q: ['Q*bert', 'Quest for Glory', 'Quake'],
    R: ['Red Dead Redemption', 'Ratchet and Clank', 'Resident Evil'],
    S: ['Starcraft', 'Skyrim', 'Sonic', 'Spyro', 'Splatoon', 'Sekiro'],
    T: ['Tetris', 'The Last of Us', 'Tomb Raider', 'Terraria'],
    U: ['Undertale', 'Uncharted', 'Unreal Tournament'],
    V: ['Valorant', 'Valheim', 'Vampire Survivors'],
    W: ['World of Warcraft', 'Witcher', 'Wolfenstein', 'Watch Dogs'],
    X: ['XCOM', 'Xenogears', 'Xenoblade Chronicles'],
    Y: ["Yoshi's Island", 'Yakuza', "Yoku's Island Express"],
    Z: ['Zelda', 'Zork', 'Zero Escape'],
  },

  tvshows: {
    A: ['Avatar', 'Arrow', 'Arrested Development', 'Alias', 'Andor'],
    B: ['Breaking Bad', 'Better Call Saul', 'Black Mirror', 'Band of Brothers', 'Bloodline'],
    C: ['Castle', 'Cheers', 'Community', 'Criminal Minds', 'Chernobyl'],
    D: ['Dexter', 'Downton Abbey', 'Dark', 'Doctor Who', 'Daredevil'],
    E: ['Elementary', 'Euphoria', 'ER', 'Entourage'],
    F: ['Friends', 'Fargo', 'Firefly', 'Family Guy', 'Fleabag'],
    G: ['Game of Thrones', "Grey's Anatomy", 'Glee', 'Gravity Falls'],
    H: ['House', 'Homeland', 'Heroes', 'Halt and Catch Fire', 'House of Cards'],
    I: ["It's Always Sunny", 'Invincible'],
    J: ['Justified', 'Jane the Virgin'],
    K: ['Killing Eve', 'Kingdom'],
    L: ['Lost', 'Loki', 'Line of Duty', 'Lucifer'],
    M: ['Mad Men', 'Mindhunter', 'Modern Family', 'Mandalorian'],
    N: ['Narcos', 'NCIS', 'New Girl'],
    O: ['Orange is the New Black', 'Outer Banks', 'One Tree Hill', 'Our Planet'],
    P: ['Parks and Recreation', 'Prison Break', 'Peaky Blinders', 'Pose'],
    Q: ['Quantum Leap', "Queen's Gambit"],
    R: ['Rick and Morty', 'Rings of Power', 'Raised by Wolves'],
    S: ['Succession', 'Stranger Things', 'Seinfeld', 'Squid Game', 'Sherlock'],
    T: ['The Wire', 'The Sopranos', 'Ted Lasso', 'Twin Peaks'],
    U: ['Umbrella Academy', 'Unsolved Mysteries', 'Ugly Betty'],
    V: ['Vikings', 'Veep', 'Vampire Diaries'],
    W: ['Walking Dead', 'Westworld', 'West Wing', 'White Lotus', 'Wentworth'],
    X: ['X-Files', 'Xena Warrior Princess'],
    Y: ['Young Sheldon', 'You', 'Yellowstone'],
    Z: ['Zoo', 'Zombies'],
  },

  superheroes: {
    A: ['Aquaman', 'Ant-Man', 'Atom', 'Arrowette', 'Atom Eve'],
    B: ['Batman', 'Black Panther', 'Black Widow', 'Batgirl', 'Booster Gold'],
    C: ['Captain America', 'Cyclops', 'Captain Marvel', 'Catwoman'],
    D: ['Deadpool', 'Daredevil', 'Doctor Strange', 'Domino'],
    E: ['Elastigirl', 'Elektra'],
    F: ['Flash', 'Falcon', 'Firestar'],
    G: ['Green Lantern', 'Green Arrow', 'Groot', 'Ghost Rider', 'Gambit'],
    H: ['Hulk', 'Hawkeye', 'Hawkman', 'Hit-Girl'],
    I: ['Iron Man', 'Invisible Woman', 'Iceman'],
    J: ['Jessica Jones', 'Jubilee'],
    K: ['Kick-Ass', 'Kilowog'],
    L: ['Luke Cage', 'Lightning Lad'],
    M: ['Ms. Marvel', 'Martian Manhunter', 'Moon Knight', 'Mystique'],
    N: ['Nightwing', 'Namor', 'Nick Fury', 'Nova'],
    O: ['Oracle'],
    P: ['Professor X', 'Power Girl', 'Photon', 'Psylocke'],
    Q: ['Quicksilver', 'Question'],
    R: ['Robin', 'Rocket Raccoon', 'Red Hood', 'Rogue'],
    S: ['Superman', 'Spider-Man', 'Storm', 'She-Hulk', 'Shazam'],
    T: ['Thor', 'The Tick', 'Toxin'],
    U: ['Ultra Boy', 'Union Jack'],
    V: ['Vision', 'Venom', 'Valkyrie'],
    W: ['Wonder Woman', 'Wolverine', 'Wasp', 'War Machine'],
    X: ['X-23', 'Xavier'],
    Y: ['Yellowjacket'],
    Z: ['Zatanna', 'Zorro', 'Zoom'],
  },

  mythology: {
    A: ['Apollo', 'Aphrodite', 'Athena', 'Ares', 'Anubis', 'Atlas', 'Aurora'],
    B: ['Bacchus', 'Bes', 'Brahma', 'Brigid', 'Baldr'],
    C: ['Cronus', 'Cupid', 'Cernunnos', 'Circe'],
    D: ['Dionysus', 'Demeter', 'Danu'],
    E: ['Eros', 'Eris', 'Epona'],
    F: ['Freya', 'Frigg', 'Forseti'],
    G: ['Gaia', 'Ganesh'],
    H: ['Hades', 'Hermes', 'Hera', 'Horus', 'Hecate'],
    I: ['Iris', 'Isis', 'Indra'],
    J: ['Jupiter', 'Janus', 'Juno'],
    K: ['Khepri', 'Krishna', 'Kali', 'Kanaloa'],
    L: ['Loki', 'Luna'],
    M: ['Mars', 'Mercury', 'Minerva', 'Morpheus', 'Morrigan'],
    N: ['Neptune', 'Nike', 'Nephthys', 'Nut'],
    O: ['Odin', 'Osiris'],
    P: ['Poseidon', 'Persephone', 'Pan', 'Prometheus'],
    Q: ['Quetzalcoatl'],
    R: ['Ra', 'Rhea', 'Radha'],
    S: ['Saturn', 'Shiva', 'Selene', 'Sobek', 'Set'],
    T: ['Thor', 'Triton', 'Tyr', 'Thoth'],
    U: ['Uranus', 'Ukko'],
    V: ['Vishnu', 'Venus', 'Vulcan'],
    W: ['Wadjet', 'Wepwawet', 'Wotan'],
    X: ['Xipe Totec', 'Xochiquetzal'],
    Y: ['Ymir', 'Yama'],
    Z: ['Zeus', 'Zephyrus', 'Zhong Kui'],
  },

  history: {
    A: ['Alexander the Great', 'Aristotle', 'Amelia Earhart', 'Archimedes'],
    B: ['Boudicca', 'Beethoven', 'Bolivar'],
    C: ['Cleopatra', 'Churchill', 'Confucius', 'Columbus', 'Copernicus'],
    D: ['Darwin', 'Descartes', 'Diocletian'],
    E: ['Einstein', 'Elizabeth I', 'Euclid'],
    F: ['Franklin', 'Frederick the Great', 'Florence Nightingale'],
    G: ['Galileo', 'Gandhi', 'Genghis Khan', 'Gutenberg'],
    H: ['Hannibal', 'Harriet Tubman', 'Hippocrates', 'Hadrian'],
    I: ['Ivan the Terrible', 'Isabella of Castile'],
    J: ['Joan of Arc', 'Julius Caesar', 'Jefferson'],
    K: ['Kepler', 'Kublai Khan', 'Kamehameha'],
    L: ['Lincoln', 'Leonardo da Vinci', 'Louis XIV', 'Lenin'],
    M: ['Marie Curie', 'Magellan', 'Marco Polo', 'Michelangelo', 'Mozart'],
    N: ['Newton', 'Napoleon', 'Nelson', 'Nero'],
    O: ['Obama', 'Oliver Cromwell', 'Octavian'],
    P: ['Plato', 'Pocahontas', 'Pythagoras', 'Pericles'],
    Q: ['Qin Shi Huang'],
    R: ['Roosevelt', 'Rembrandt', 'Richard the Lionheart', 'Rasputin'],
    S: ['Shakespeare', 'Socrates', 'Sun Tzu', 'Suleiman'],
    T: ['Tesla', 'Tutankhamun', 'Thomas Edison'],
    U: ['Ulysses S. Grant'],
    V: ['Voltaire', 'Victoria'],
    W: ['Washington', 'Wellington', 'William the Conqueror'],
    X: ['Xerxes'],
    Y: ['Yuri Gagarin'],
    Z: ['Zheng He', 'Zhukov'],
  },

  dances: {
    A: ['Argentine Tango', 'Afrobeat', 'Aerobics Dance', 'Apsara Dance'],
    B: ['Ballet', 'Bachata', 'Bhangra', 'Ballroom', 'Breakdance', 'B-boying'],
    C: ['Cha-Cha', 'Charleston', 'Country Line Dance', 'Capoeira'],
    D: ['Disco', 'Danzon'],
    E: ['Electric Slide', 'English Country Dance'],
    F: ['Foxtrot', 'Flamenco'],
    G: ['Garba', 'Gumboot Dance'],
    H: ['Hip Hop', 'Highland Fling', 'Haka', 'Hora'],
    I: ['Irish Step Dancing'],
    J: ['Jive', 'Jazz Dance', 'Jig'],
    K: ['Kathak', 'Krump', 'Kizomba'],
    L: ['Lindy Hop', 'Latin Dance', 'Lambada'],
    M: ['Mambo', 'Merengue', 'Moonwalk', 'Macarena'],
    N: ['Northern Soul', 'Noh Dance'],
    O: ['One-Step'],
    P: ['Polka', 'Paso Doble', 'Popping'],
    Q: ['Quickstep', 'Quadrille'],
    R: ['Rumba', 'Robot Dance', 'Reggaeton'],
    S: ['Salsa', 'Samba', 'Swing', 'Shuffle'],
    T: ['Tango', 'Twist', 'Tap Dance', 'Tinikling'],
    U: ['Urban Dance'],
    V: ['Viennese Waltz', 'Voguing'],
    W: ['Waltz', 'Waacking'],
    X: ['Xaxado'],
    Y: ['Yangko', 'Yosakoi'],
    Z: ['Zapateado', 'Zydeco'],
  },
};
