const CATEGORIES = {
  fruits:      'Fruits',
  animals:     'Animals',
  cities:      'World Cities',
  foods:       'Foods & Dishes',
  vegetables:  'Vegetables',
  sports:      'Sports',
  instruments: 'Musical Instruments',
  occupations: 'Occupations',
  birds:       'Birds',
  flowers:     'Flowers',
  trees:       'Trees',
  gemstones:   'Gemstones',
  dinosaurs:   'Dinosaurs',
  movies:      'Movies',
  games:       'Video Games',
  tvshows:     'TV Shows',
  superheroes: 'Superheroes',
  mythology:   'Mythological Deities',
  history:     'Historical Figures',
  dances:      'Dances',
  countries:   'Countries',
  baseball:    'Famous Baseball Players',
  football:    'Famous Football Players',
  basketball:  'Famous Basketball Players',
};

const WORDS = {
  fruits: {
    A: ['Apple', 'Apricot', 'Avocado', 'Acai', 'Ackee', 'Asian Pear', 'Atemoya', 'Acerola', 'Ambarella', 'Araza'],
    B: ['Banana', 'Blueberry', 'Blackberry', 'Boysenberry', 'Breadfruit', 'Blood Orange', 'Bael', 'Bilberry', 'Bitter Orange', 'Barbadine'],
    C: ['Cherry', 'Coconut', 'Cranberry', 'Cantaloupe', 'Clementine', 'Currant', 'Cherimoya', 'Calamondin', 'Cloudberry', 'Capulin'],
    D: ['Dragonfruit', 'Durian', 'Date', 'Damson', 'Dewberry', 'Desert Lime', 'Duku', 'doom doom'],
    E: ['Elderberry', 'Emblica', 'Etrog', 'Entawak'],
    F: ['Fig', 'Feijoa', 'Finger Lime', 'Fuyu Persimmon', 'False Mastic'],
    G: ['Grape', 'Guava', 'Grapefruit', 'Gooseberry', 'Greengage', 'Grumichama', 'Gamboge', 'Gac'],
    H: ['Honeydew', 'Huckleberry', 'Hackberry', 'Horned Melon'],
    I: ['Ilama', 'Indian Plum', 'Imbe', 'Ice Apple', 'Inga Berry'],
    J: ['Jackfruit', 'Jujube', 'Jaboticaba', 'Java Plum', 'Jocote', 'Jobo'],
    K: ['Kiwi', 'Kumquat', 'Kiwano', 'Kaki', 'Kaffir Lime', 'Kei Apple'],
    L: ['Lemon', 'Lime', 'Lychee', 'Longan', 'Loganberry', 'Langsat', 'Lucuma', 'Limequat'],
    M: ['Mango', 'Melon', 'Mulberry', 'Mandarin', 'Maracuja', 'Mamey', 'Marula', 'Miracle Fruit'],
    N: ['Nectarine', 'Noni', 'Naranjilla', 'Natal Plum', 'Nance'],
    O: ['Orange', 'Olive', 'Ortanique', 'Osage Orange', 'Orangelo'],
    P: ['Peach', 'Pear', 'Pineapple', 'Plum', 'Pomegranate', 'Papaya', 'Passion Fruit', 'Persimmon', 'Pawpaw', 'Pitaya'],
    Q: ['Quince', 'Quenepa', 'Queensland Plum', 'Quandong'],
    R: ['Raspberry', 'Rambutan', 'Redcurrant', 'Rose Apple', 'Rollinia', 'Riberry'],
    S: ['Strawberry', 'Star Fruit', 'Sapodilla', 'Soursop', 'Sugar Apple', 'Salak', 'Santol'],
    T: ['Tangerine', 'Tamarind', 'Tomato', 'Tamarillo', 'Tangelo', 'Tayberry'],
    U: ['Ugli Fruit', 'Ugni', 'Uva Ursi'],
    V: ['Valencia Orange', 'Voavanga', 'Vanilla Bean'],
    W: ['Watermelon', 'Wolfberry', 'Wampee', 'White Currant', 'Wild Strawberry'],
    X: ['Xigua', 'Ximenia', 'Xoconostle'],
    Y: ['Yuzu', 'Yellow Passion Fruit', 'Yangmei', 'Yellow Plum', 'Yumberry'],
    Z: ['Ziziphus', 'Zhe'],
  },

  animals: {
    A: ['Alligator', 'Antelope', 'Armadillo', 'Aardvark', 'Alpaca', 'Anaconda', 'Axolotl', 'Aye-aye', 'African Wild Dog'],
    B: ['Bear', 'Buffalo', 'Baboon', 'Bison', 'Bat', 'Beaver', 'Binturong', 'Boar', 'Bongo', 'Blue Whale', 'baracuda'],
    C: ['Cheetah', 'Crocodile', 'Camel', 'Cobra', 'Chimpanzee', 'Coyote', 'Caracal', 'Capybara', 'Chinchilla'],
    D: ['Deer', 'Dolphin', 'Dingo', 'Donkey', 'Dhole', 'Dugong', 'Dik-dik'],
    E: ['Elephant', 'Elk', 'Emu', 'Echidna', 'Ermine'],
    F: ['Fox', 'Frog', 'Ferret', 'Flamingo', 'Falcon', 'Flying Squirrel', 'Fishing Cat'],
    G: ['Gorilla', 'Giraffe', 'Gecko', 'Gazelle', 'Goat', 'Gemsbok', 'Giant Anteater', 'Gray Wolf'],
    H: ['Hippo', 'Horse', 'Hyena', 'Hamster', 'Hedgehog', 'Hartebeest', 'Hare'],
    I: ['Iguana', 'Impala', 'Ibis', 'Indri'],
    J: ['Jaguar', 'Jellyfish', 'Jackal', 'Japanese Macaque'],
    K: ['Kangaroo', 'Koala', 'Komodo Dragon', 'Kinkajou', 'Kudu'],
    L: ['Lion', 'Leopard', 'Llama', 'Lynx', 'Lemur', 'Liger', 'Loris'],
    M: ['Monkey', 'Moose', 'Meerkat', 'Mouse', 'Mongoose', 'Manatee', 'Marten', 'Markhor'],
    N: ['Narwhal', 'Newt', 'Numbat', 'Nile Monitor'],
    O: ['Orangutan', 'Ostrich', 'Otter', 'Octopus', 'Owl', 'Ocelot', 'Oryx'],
    P: ['Panda', 'Penguin', 'Puma', 'Panther', 'Platypus', 'Porcupine', 'Proboscis Monkey', 'Pangolin'],
    Q: ['Quokka', 'Quoll', 'Quetzal', 'Quahog'],
    R: ['Rabbit', 'Rhinoceros', 'Raccoon', 'Rattlesnake', 'Red Panda', 'Ring-tailed Lemur'],
    S: ['Snake', 'Shark', 'Sloth', 'Seal', 'Squirrel', 'Snow Leopard', 'Serval', 'Salamander'],
    T: ['Tiger', 'Turtle', 'Tapir', 'Toucan', 'Tasmanian Devil', 'Tarsier', 'Tamarin'],
    U: ['Uakari', 'Urial', 'Urchin'],
    V: ['Vulture', 'Viper', 'Vicuna', 'Vervet Monkey'],
    W: ['Wolf', 'Whale', 'Wombat', 'Walrus', 'Weasel', 'Wolverine', 'Wildebeest'],
    X: ['Xerus', 'Xenops', 'X-ray Tetra'],
    Y: ['Yak', 'Yellow Mongoose', 'Yacare Caiman', 'Yabby'],
    Z: ['Zebra', 'Zebu', 'Zorilla'],
  },

  cities: {
    A: ['Amsterdam', 'Athens', 'Auckland', 'Ankara', 'Accra', 'Algiers', 'Abu Dhabi', 'Almaty', 'Amman', 'Addis Ababa'],
    B: ['Barcelona', 'Bangkok', 'Buenos Aires', 'Berlin', 'Beijing', 'Brussels', 'Bogota', 'Beirut', 'Bucharest', 'Bangalore'],
    C: ['Cairo', 'Chicago', 'Copenhagen', 'Casablanca', 'Cape Town', 'Colombo', 'Caracas', 'Calgary', 'Chisinau'],
    D: ['Dubai', 'Delhi', 'Dublin', 'Dhaka', 'Detroit', 'Dakar', 'Doha', 'Damascus'],
    E: ['Edinburgh', 'Entebbe', 'El Paso', 'Essen'],
    F: ['Florence', 'Frankfurt', 'Fuzhou', 'Freetown'],
    G: ['Geneva', 'Glasgow', 'Guangzhou', 'Guadalajara', 'Gothenburg', 'Gaza'],
    H: ['Hong Kong', 'Havana', 'Hamburg', 'Helsinki', 'Hanoi', 'Harare', 'Houston'],
    I: ['Istanbul', 'Islamabad', 'Izmir', 'Indianapolis'],
    J: ['Jakarta', 'Jerusalem', 'Johannesburg', 'Jaipur', 'Jeddah'],
    K: ['Karachi', 'Kyoto', 'Kuala Lumpur', 'Kinshasa', 'Kathmandu', 'Kabul', 'Kiev'],
    L: ['London', 'Los Angeles', 'Lima', 'Lisbon', 'Lagos', 'Lyon', 'Lahore', 'Luanda'],
    M: ['Madrid', 'Moscow', 'Mumbai', 'Montreal', 'Melbourne', 'Manila', 'Milan', 'Minsk'],
    N: ['New York', 'Nairobi', 'Naples', 'New Delhi', 'Nagoya', 'Nicosia'],
    O: ['Oslo', 'Ottawa', 'Osaka', 'Odessa', 'Ouagadougou'],
    P: ['Paris', 'Prague', 'Perth', 'Philadelphia', 'Porto', 'Panama City', 'Phnom Penh'],
    Q: ['Quebec City', 'Quito', 'Quezon City'],
    R: ['Rome', 'Rio de Janeiro', 'Rotterdam', 'Riyadh', 'Reykjavik', 'Rabat'],
    S: ['Sydney', 'Seoul', 'Singapore', 'Stockholm', 'Shanghai', 'Santiago', 'San Francisco'],
    T: ['Tokyo', 'Toronto', 'Tehran', 'Tel Aviv', 'Taipei', 'Tashkent', 'Tunis'],
    U: ['Ulaanbaatar', 'Utrecht', 'Ufa', 'Ushuaia'],
    V: ['Vienna', 'Vancouver', 'Venice', 'Vilnius', 'Vladivostok', 'Valletta'],
    W: ['Warsaw', 'Washington DC', 'Wellington', 'Winnipeg', 'Wuhan'],
    X: ["Xi'an"],
    Y: ['Yokohama', 'Yangon', 'Yerevan', 'Yaounde'],
    Z: ['Zurich', 'Zagreb', 'Zanzibar', 'Zhengzhou'],
  },

  foods: {
    A: ['Apple Pie', 'Avocado Toast', 'Alfredo Pasta', 'Asparagus Soup', 'Arancini', 'Adobo', 'Antipasto', 'Aglio e Olio'],
    B: ['Burger', 'Burrito', 'Baklava', 'Bruschetta', 'Bibimbap', 'Borscht', 'Biryani', 'Beef Stew'],
    C: ['Curry', 'Carbonara', 'Croissant', 'Chili', 'Cheesecake', 'Crepe', 'Ceviche', 'Couscous'],
    D: ['Dumpling', 'Dal', 'Donut', 'Duck Confit', 'Danish Pastry', 'Dhokla', 'Dolmas', 'Dolma'],
    E: ['Enchilada', 'Empanada', 'Eggs Benedict', 'Escargot', 'Eel Sushi'],
    F: ['French Fries', 'Falafel', 'Fish and Chips', 'Fried Rice', 'Fondue', 'French Toast', 'Frittata'],
    G: ['Gyoza', 'Gumbo', 'Guacamole', 'Gazpacho', 'Gelato', 'Gnocchi', 'Galette'],
    H: ['Hummus', 'Hot Dog', 'Hash Browns', 'Halloumi', 'Hot Pot', 'Honey Cake'],
    I: ['Ice Cream', 'Idli', 'Irish Stew'],
    J: ['Jambalaya', 'Jerk Chicken', 'Jollof Rice', 'Japanese Curry'],
    K: ['Kebab', 'Kimchi', 'Katsu Curry', 'Knish', 'Kulfi'],
    L: ['Lasagna', 'Lobster', 'Lentil Soup', 'Latke', 'Lamb Chops', 'Lo Mein'],
    M: ['Moussaka', 'Miso Soup', 'Macaroni', 'Mole', 'Momos', 'Meatballs', 'Macaron'],
    N: ['Nachos', 'Noodles', 'Naan', 'Nougat', 'Nasi Goreng'],
    O: ['Omelette', 'Onion Rings', 'Okonomiyaki', 'Oysters'],
    P: ['Pizza', 'Paella', 'Pad Thai', 'Pancakes', 'Pho', 'Pierogi', 'Pretzels', 'Poutine'],
    Q: ['Quiche', 'Quesadilla', 'Quindim'],
    R: ['Ramen', 'Risotto', 'Ravioli', 'Rendang', 'Rotisserie Chicken'],
    S: ['Sushi', 'Steak', 'Sandwich', 'Shawarma', 'Samosa', 'Souvlaki', 'Spring Roll'],
    T: ['Tacos', 'Tikka Masala', 'Tempura', 'Tiramisu', 'Tom Yum', 'Tagine'],
    U: ['Udon', 'Ugali', 'Ube Cake'],
    V: ['Vichyssoise', 'Vindaloo', 'Veal Scallopini'],
    W: ['Waffle', 'Wontons', 'White Rice', 'Wiener Schnitzel'],
    X: ['Xiaolongbao', 'Xo Sauce'],
    Y: ['Yakitori', 'Yogurt', 'Yorkshire Pudding', 'Yakisoba'],
    Z: ['Zabaglione', 'Ziti', 'Zeppole', 'Zucchini Fritters'],
  },

  vegetables: {
    A: ['Asparagus', 'Artichoke', 'Arugula', 'Avocado', 'Acorn Squash', 'Amaranth'],
    B: ['Broccoli', 'Brussels Sprouts', 'Beetroot', 'Bok Choy', 'Bell Pepper', 'Broad Bean', 'Butternut Squash'],
    C: ['Carrot', 'Cauliflower', 'Cabbage', 'Celery', 'Cucumber', 'Chard', 'Chickpea', 'Celeriac'],
    D: ['Daikon', 'Dandelion Greens', 'Delicata Squash'],
    E: ['Eggplant', 'Edamame', 'Endive', 'Escarole'],
    F: ['Fennel', 'Fiddlehead Fern', 'French Bean'],
    G: ['Garlic', 'Ginger', 'Green Onion', 'Galangal', 'Gai Lan'],
    H: ['Horseradish', 'Heart of Palm', 'Haricot Bean'],
    I: ['Indian Spinach', 'Iceberg Lettuce'],
    J: ['Jicama', 'Jerusalem Artichoke', 'Jalapeno'],
    K: ['Kale', 'Kohlrabi', 'Komatsuna'],
    L: ['Leek', 'Lettuce', 'Lentil', 'Lima Bean'],
    M: ['Mushroom', 'Mustard Greens', 'Mangetout', 'Mung Bean', 'Mizuna'],
    N: ['Napa Cabbage', 'Nori'],
    O: ['Onion', 'Okra', 'Oyster Mushroom'],
    P: ['Potato', 'Pea', 'Pepper', 'Pumpkin', 'Parsnip', 'Purple Cabbage'],
    Q: ['Quinoa'],
    R: ['Radish', 'Rutabaga', 'Radicchio', 'Red Cabbage', 'Rocket'],
    S: ['Spinach', 'Sweet Potato', 'Squash', 'Scallion', 'Snap Pea', 'Sunchoke'],
    T: ['Tomato', 'Turnip', 'Taro', 'Tomatillo'],
    U: ['Ulluco', 'Upo'],
    V: ['Vine Tomato', 'Velvet Bean'],
    W: ['Watercress', 'Water Chestnut', 'Wakame', 'White Radish'],
    X: ['Xigua'],
    Y: ['Yam', 'Yuca', 'Yellow Squash', 'Yardlong Bean'],
    Z: ['Zucchini', 'Zucchini Flower'],
  },

  sports: {
    A: ['Archery', 'Athletics', 'American Football', 'Aikido', 'Alpine Skiing', 'Arm Wrestling', 'Aquatics'],
    B: ['Basketball', 'Baseball', 'Badminton', 'Boxing', 'Bowling', 'Biathlon', 'Bobsled'],
    C: ['Cricket', 'Cycling', 'Curling', 'Canoeing', 'Climbing', 'Cross Country', 'Cheerleading'],
    D: ['Diving', 'Discus Throw', 'Dodgeball', 'Dressage'],
    E: ['Equestrian', 'Endurance Racing', 'Extreme Sports'],
    F: ['Football', 'Fencing', 'Figure Skating', 'Field Hockey', 'Free Diving'],
    G: ['Golf', 'Gymnastics', 'Go-Karting'],
    H: ['Hockey', 'Handball', 'High Jump', 'Hurdles', 'Hammer Throw', 'Hang Gliding'],
    I: ['Ice Hockey', 'Ice Skating', 'Indoor Volleyball'],
    J: ['Judo', 'Javelin', 'Jai Alai', 'Jousting', 'Jet Skiing'],
    K: ['Karate', 'Kayaking', 'Kickboxing', 'Kendo'],
    L: ['Lacrosse', 'Luge', 'Long Jump', 'Log Rolling'],
    M: ['Marathon', 'Mountaineering', 'Mixed Martial Arts', 'Motocross'],
    N: ['Netball', 'Nordic Skiing', 'Nordic Combined'],
    O: ['Olympic Weightlifting', 'Obstacle Course Racing'],
    P: ['Polo', 'Ping Pong', 'Parkour', 'Pentathlon', 'Para Athletics'],
    Q: ['Quoits', 'Quadrathlon'],
    R: ['Rugby', 'Rowing', 'Rock Climbing', 'Racquetball'],
    S: ['Swimming', 'Soccer', 'Skiing', 'Squash', 'Surfing', 'Skateboarding', 'Softball'],
    T: ['Tennis', 'Track and Field', 'Taekwondo', 'Triathlon', 'Table Tennis'],
    U: ['Ultimate Frisbee', 'Ultramarathon', 'Underwater Hockey'],
    V: ['Volleyball', 'Vaulting'],
    W: ['Wrestling', 'Water Polo', 'Weightlifting', 'Windsurfing', 'Wakeboarding'],
    X: ['X-Games'],
    Y: ['Yoga', 'Yachting'],
    Z: ['Zorbing'],
  },

  instruments: {
    A: ['Accordion', 'Alto Saxophone', 'Autoharp', 'Acoustic Guitar'],
    B: ['Banjo', 'Bass Guitar', 'Bagpipes', 'Bassoon', 'Balalaika', 'Bouzouki'],
    C: ['Clarinet', 'Cello', 'Cornet', 'Castanets', 'Contrabass', 'Crwth'],
    D: ['Drums', 'Dulcimer', 'Didgeridoo', 'Double Bass'],
    E: ['Electric Guitar', 'Electric Violin', 'Euphonium'],
    F: ['Flute', 'French Horn', 'Fiddle', 'Flugelhorn'],
    G: ['Guitar', 'Grand Piano', 'Gong', 'Glass Harmonica'],
    H: ['Harmonica', 'Harp', 'Harpsichord', 'Horn'],
    I: ['Irish Flute', 'Irish Uilleann Pipes'],
    J: ['Jazz Trumpet'],
    K: ['Keyboard', 'Koto', 'Kalimba'],
    L: ['Lute', 'Lyre'],
    M: ['Mandolin', 'Marimba', 'Melodica'],
    N: ['Nose Flute'],
    O: ['Oboe', 'Organ', 'Ocarina'],
    P: ['Piano', 'Piccolo', 'Pan Flute'],
    Q: ['Qin', 'Qanun'],
    R: ['Recorder', 'Rhodes Piano'],
    S: ['Saxophone', 'Sitar', 'Sousaphone', 'Steel Drum', 'Snare Drum', 'Synthesizer'],
    T: ['Trumpet', 'Trombone', 'Tuba', 'Tambourine', 'Theremin'],
    U: ['Ukulele'],
    V: ['Violin', 'Viola', 'Vibraphone'],
    W: ['Washboard', 'Wind Chimes', 'Whistle'],
    X: ['Xylophone'],
    Y: ['Yangqin', 'Yueqin'],
    Z: ['Zither', 'Zurna'],
  },

  occupations: {
    A: ['Actor', 'Architect', 'Accountant', 'Astronaut', 'Archaeologist', 'Animator', 'Anesthesiologist', 'Artist'],
    B: ['Baker', 'Builder', 'Banker', 'Biologist', 'Barber', 'Botanist', 'Biochemist'],
    C: ['Chef', 'Carpenter', 'Cashier', 'Chemist', 'Coach', 'Counselor', 'Chiropractor', 'Conductor'],
    D: ['Doctor', 'Dentist', 'Detective', 'Designer', 'Driver', 'Data Scientist', 'Dermatologist'],
    E: ['Engineer', 'Electrician', 'Editor', 'Economist', 'EMT'],
    F: ['Farmer', 'Firefighter', 'Florist', 'Financial Analyst'],
    G: ['Gardener', 'Geologist', 'Graphic Designer', 'Geneticist'],
    H: ['Historian', 'Hunter', 'Hydrologist', 'Hairdresser'],
    I: ['Interpreter', 'Inspector', 'Illustrator', 'Investment Banker'],
    J: ['Judge', 'Journalist', 'Jeweler', 'Janitor'],
    K: ['Kinesiologist'],
    L: ['Lawyer', 'Librarian', 'Locksmith', 'Linguist'],
    M: ['Mechanic', 'Musician', 'Manager', 'Mathematician', 'Marine Biologist'],
    N: ['Nurse', 'Nutritionist', 'Navigator', 'Neurologist'],
    O: ['Optician', 'Operator', 'Obstetrician'],
    P: ['Photographer', 'Pilot', 'Plumber', 'Programmer', 'Pharmacist', 'Psychiatrist'],
    Q: ['Quilter', 'Quarryman'],
    R: ['Reporter', 'Ranger', 'Researcher', 'Radiologist'],
    S: ['Surgeon', 'Scientist', 'Salesperson', 'Sailor', 'Software Engineer', 'Sociologist'],
    T: ['Teacher', 'Technician', 'Therapist', 'Translator', 'Toxicologist'],
    U: ['Undertaker', 'Urban Planner', 'UX Designer'],
    V: ['Veterinarian', 'Violinist', 'Video Game Designer'],
    W: ['Writer', 'Welder', 'Waiter', 'Web Developer', 'Wine Steward'],
    X: ['Xylographer'],
    Y: ['Yoga Instructor', 'Youth Counselor'],
    Z: ['Zoologist', 'Zookeeper'],
  },

  birds: {
    A: ['Albatross', 'Avocet', 'American Robin', 'Auklet', 'Anhinga', 'Amazon Parrot', 'Angel bird'],
    B: ['Bluebird', 'Blue Jay', 'Bald Eagle', 'Barn Owl', 'Bulfinch', 'Bunting'],
    C: ['Cardinal', 'Crane', 'Crow', 'Cockatoo', 'Canary', 'Condor', 'Common Loon', 'Cuckoo'],
    D: ['Duck', 'Dove', 'Dodo', 'Dunlin'],
    E: ['Eagle', 'Egret', 'Emu', 'Eastern Bluebird'],
    F: ['Flamingo', 'Falcon', 'Finch', 'Frigate Bird'],
    G: ['Goose', 'Goldfinch', 'Great Horned Owl', 'Golden Eagle', 'Grouse'],
    H: ['Hawk', 'Heron', 'Hummingbird', 'Hoopoe', 'Harrier'],
    I: ['Ibis', 'Indigo Bunting'],
    J: ['Jay', 'Junco', 'Java Sparrow'],
    K: ['Kingfisher', 'Kiwi', 'Kookaburra', 'Kestrel'],
    L: ['Lark', 'Loon', 'Lyrebird', 'Lapwing'],
    M: ['Macaw', 'Mockingbird', 'Magpie', 'Myna', 'Meadowlark'],
    N: ['Nightingale', 'Nighthawk', 'Nutcracker', 'Nuthatch'],
    O: ['Owl', 'Oriole', 'Osprey', 'Ovenbird'],
    P: ['Parrot', 'Pelican', 'Penguin', 'Peacock', 'Pigeon', 'Puffin'],
    Q: ['Quail', 'Quetzal', 'Quelea'],
    R: ['Robin', 'Raven', 'Roadrunner', 'Red Kite', 'Rook'],
    S: ['Sparrow', 'Starling', 'Swan', 'Stork', 'Snowy Owl', 'Sandpiper'],
    T: ['Toucan', 'Turkey', 'Tern', 'Teal', 'Thrush', 'Titmouse'],
    U: ['Umbrellabird', 'Upland Sandpiper'],
    V: ['Vulture', 'Verdin', 'Vireo'],
    W: ['Warbler', 'Woodpecker', 'Wren', 'White Stork'],
    X: ['Xenops'],
    Y: ['Yellow Warbler', 'Yellowhammer', 'Yellow-bellied Sapsucker'],
    Z: ['Zebra Finch', 'Zone-tailed Hawk', 'Zitting Cisticola'],
  },

  flowers: {
    A: ['Amaryllis', 'Azalea', 'Alstroemeria', 'Aster', 'Agapanthus', 'Anemone'],
    B: ['Bluebell', 'Black-Eyed Susan', 'Begonia', "Baby's Breath", 'Bird of Paradise', 'Bleeding Heart'],
    C: ['Carnation', 'Chrysanthemum', 'Cosmos', 'Crocus', 'Cyclamen', 'Calla Lily', 'Candytuft'],
    D: ['Dahlia', 'Daisy', 'Delphinium', 'Daffodil', 'Dianthus'],
    E: ['Edelweiss', 'Echinacea', 'Evening Primrose', 'Eustoma'],
    F: ['Freesia', 'Foxglove', 'Fuchsia', 'Forget-Me-Not'],
    G: ['Gardenia', 'Gladiolus', 'Geranium', 'Gypsophila', 'Gerbera'],
    H: ['Hyacinth', 'Hibiscus', 'Hollyhock', 'Heather', 'Hellebore'],
    I: ['Iris', 'Impatiens', 'Ice Plant'],
    J: ['Jasmine', 'Jonquil', "Jacob's Ladder"],
    K: ['Kangaroo Paw', 'Kniphofia'],
    L: ['Lavender', 'Lily', 'Lotus', 'Larkspur', 'Lisianthus'],
    M: ['Magnolia', 'Marigold', 'Morning Glory', 'Moonflower', 'Muscari'],
    N: ['Narcissus', 'Nemesia', 'Nigella'],
    O: ['Orchid', 'Oxeye Daisy', 'Oriental Poppy'],
    P: ['Pansy', 'Peony', 'Poppy', 'Primrose', 'Phlox', 'Petunia'],
    Q: ["Queen Anne's Lace", 'Quince Blossom'],
    R: ['Rose', 'Ranunculus', 'Red Clover', 'Rudbeckia'],
    S: ['Sunflower', 'Sweet Pea', 'Snapdragon', 'Stock', 'Statice'],
    T: ['Tulip', 'Tiger Lily', 'Thistle', 'Tuberose'],
    U: ['Ursinia'],
    V: ['Violet', 'Verbena', 'Veronica', 'Viburnum'],
    W: ['Wisteria', 'Water Lily', 'Wallflower', 'Wild Rose'],
    X: ['Xeranthemum', 'Xiphium Iris'],
    Y: ['Yarrow', 'Yellow Rose', 'Yucca Flower'],
    Z: ['Zinnia', 'Zebra Plant Flower', 'Zephyranthes'],
  },

  trees: {
    A: ['Ash', 'Apple Tree', 'Acacia', 'Alder', 'Aspen', 'Avocado Tree'],
    B: ['Birch', 'Beech', 'Baobab', 'Bonsai', 'Balsa', 'Black Walnut', 'Barbados Cherry', 'Barbados Flowerfence'],
    C: ['Cedar', 'Cherry Tree', 'Cypress', 'Chestnut', 'Catalpa', 'Coffee Tree'],
    D: ['Douglas Fir', 'Date Palm', 'Dawn Redwood'],
    E: ['Elm', 'Eucalyptus', 'Elder', 'English Oak'],
    F: ['Fig Tree', 'Fir', 'Flame Tree'],
    G: ['Ginkgo', 'Gum Tree', 'Goldenrain Tree'],
    H: ['Horse Chestnut', 'Hazel', 'Hawthorn', 'Hemlock'],
    I: ['Irish Yew', 'Indian Rosewood', 'Ironwood'],
    J: ['Juniper', 'Jacaranda', 'Japanese Maple'],
    K: ['Kapok', 'Kentucky Coffee Tree', 'Kauri'],
    L: ['Larch', 'Lemon Tree', 'Lime Tree', 'Laurel'],
    M: ['Maple', 'Magnolia', 'Mulberry', 'Monkey Puzzle', 'Moreton Bay Fig'],
    N: ['Norway Spruce', 'Neem', 'Northern Red Oak'],
    O: ['Oak', 'Olive Tree', 'Oregon Pine'],
    P: ['Pine', 'Palm', 'Poplar', 'Plum Tree', 'Pawpaw Tree'],
    Q: ['Quaking Aspen', 'Quince Tree', 'Queensland Maple'],
    R: ['Redwood', 'Rowan', 'Red Maple', 'River Birch'],
    S: ['Spruce', 'Sycamore', 'Sequoia', 'Silver Birch', 'Sweet Gum'],
    T: ['Teak', 'Tulip Tree', 'Tamarind', 'Tamarack'],
    U: ['Umbrella Tree'],
    V: ['Valley Oak', 'Viburnum Tree'],
    W: ['Walnut', 'Willow', 'White Oak', 'Wych Elm'],
    X: ['Xylosma', 'Xanthoceras'],
    Y: ['Yew', 'Yellow Birch', 'Yellowwood'],
    Z: ['Zelkova', 'Zebrawood'],
  },

  gemstones: {
    A: ['Amethyst', 'Aquamarine', 'Amber', 'Alexandrite', 'Agate', 'Amazonite'],
    B: ['Beryl', 'Bloodstone', 'Blue Topaz', 'Benitoite'],
    C: ['Citrine', 'Coral', 'Carnelian', 'Cat\'s Eye', 'Chrysoberyl', 'Chrome Diopside'],
    D: ['Diamond', 'Danburite', 'Diopside'],
    E: ['Emerald', 'Epidote', 'Enstatite'],
    F: ['Fire Opal', 'Fluorite', 'Feldspar'],
    G: ['Garnet', 'Goshenite', 'Grossular', 'Goldstone'],
    H: ['Heliodor', 'Howlite', 'Hematite', 'Hessonite'],
    I: ['Iolite', 'Indicolite'],
    J: ['Jade', 'Jasper', 'Jet', 'Jadeite'],
    K: ['Kunzite', 'Kyanite'],
    L: ['Lapis Lazuli', 'Labradorite', 'Larimar', 'Lepidolite'],
    M: ['Moonstone', 'Malachite', 'Morganite', 'Moldavite'],
    N: ['Nephrite', 'Nuummite'],
    O: ['Onyx', 'Opal', 'Obsidian'],
    P: ['Peridot', 'Pearl', 'Pyrite', 'Pink Sapphire'],
    Q: ['Quartz', 'Quartzite'],
    R: ['Ruby', 'Rose Quartz', 'Rhodonite', 'Rhodochrosite'],
    S: ['Sapphire', 'Spinel', 'Sunstone', 'Sodalite', 'Smithsonite'],
    T: ['Topaz', 'Turquoise', 'Tourmaline', "Tiger's Eye"],
    U: ['Unakite', 'Ulexite'],
    V: ['Variscite', 'Verdite'],
    W: ['Watermelon Tourmaline', 'White Opal', 'White Jade'],
    X: ['Xanthite', 'Xenotime'],
    Y: ['Yellow Sapphire', 'Yellow Diamond'],
    Z: ['Zircon', 'Zoisite'],
  },

  dinosaurs: {
    A: ['Allosaurus', 'Ankylosaurus', 'Apatosaurus', 'Argentinosaurus', 'Abelisaurus', 'Altirhinus'],
    B: ['Brachiosaurus', 'Brontosaurus', 'Baryonyx', 'Barosaurus', 'Beipiaosaurus'],
    C: ['Carnotaurus', 'Compsognathus', 'Carcharodontosaurus', 'Ceratosaurus', 'Camarasaurus'],
    D: ['Diplodocus', 'Deinonychus', 'Dilophosaurus', 'Dromaeosaurus'],
    E: ['Edmontosaurus', 'Euoplocephalus', 'Einiosaurus', 'Edmontonia'],
    F: ['Fukuiraptor', 'Futabasaurus'],
    G: ['Giganotosaurus', 'Gallimimus', 'Gasosaurus', 'Gorgosaurus'],
    H: ['Hadrosaurus', 'Hypsilophodon'],
    I: ['Iguanodon', 'Irritator'],
    J: ['Jeholornis', 'Janenschia', 'Jobaria'],
    K: ['Kentrosaurus', 'Kronosaurus', 'Kosmoceratops'],
    L: ['Lambeosaurus', 'Lesothosaurus', 'Leaellynasaura'],
    M: ['Megalosaurus', 'Maiasaura', 'Muttaburrasaurus', 'Mapusaurus'],
    N: ['Neovenator', 'Nigersaurus'],
    O: ['Oviraptor', 'Ornithomimus', 'Ouranosaurus'],
    P: ['Parasaurolophus', 'Pachycephalosaurus', 'Pteranodon', 'Plateosaurus', 'Protoceratops'],
    Q: ['Qantassaurus', 'Quaesitosaurus', 'Quilmesaurus'],
    R: ['Raptor', 'Rugops', 'Rebbachisaurus'],
    S: ['Stegosaurus', 'Spinosaurus', 'Sauroposeidon', 'Saurolophus', 'Saltasaurus'],
    T: ['Triceratops', 'Tyrannosaurus', 'Therizinosaurus', 'Troodon', 'Torosaurus'],
    U: ['Utahraptor', 'Ugrosaurus', 'Unenlagia'],
    V: ['Velociraptor', 'Vulcanodon'],
    W: ['Wuerhosaurus', 'Wannanosaurus'],
    X: ['Xenotarsosaurus', 'Xiaosaurus', 'Xuanhanosaurus'],
    Y: ['Yangchuanosaurus', 'Yandusaurus'],
    Z: ['Zuniceratops', 'Zhuchengtyrannus'],
  },

  movies: {
    A: ['Avatar', 'Aliens', 'Aladdin', 'Arrival', 'Amadeus', 'American Beauty', 'Amelie'],
    B: ['Batman', 'Braveheart', 'Blade Runner', 'Black Panther', 'Back to the Future', 'Beauty and the Beast', 'Bohemian Rhapsody'],
    C: ['Casablanca', 'Clueless', 'Captain America', 'Cinderella', 'Cast Away', 'Coco'],
    D: ['Die Hard', 'Dune', 'Dunkirk', 'Dark Knight', 'District 9', 'Deadpool'],
    E: ['Elf', 'ET', 'Everything Everywhere All At Once', 'Eternal Sunshine', 'Encanto'],
    F: ['Forrest Gump', 'Frozen', 'Fight Club', 'Finding Nemo', 'Full Metal Jacket', 'Ferris Bueller'],
    G: ['Gladiator', 'Goodfellas', 'Grease', 'Get Out', 'Ghostbusters', 'Gran Torino', 'Gravity'],
    H: ['Harry Potter', 'Home Alone', 'Her', 'Heat', 'Halloween', 'Hunt for the Wilderpeople'],
    I: ['Inception', 'Iron Man', 'Interstellar', 'Into the Wild'],
    J: ['Jaws', 'Joker', 'Jurassic Park', 'Jumanji', 'John Wick'],
    K: ['Killers of the Flower Moon', 'King Kong', 'Knives Out'],
    L: ['Lion King', 'La La Land', 'Lego Movie', 'Lawrence of Arabia', 'Luca', 'Life of Pi'],
    M: ['Matrix', 'Mad Max', 'Moana', 'Mulan', 'Moonlight', 'Midsommar', 'Memento'],
    N: ['No Country for Old Men', 'Nope', 'Nomadland', 'Nightcrawler'],
    O: ['Oppenheimer', "Ocean's Eleven", 'Oldboy'],
    P: ['Pulp Fiction', 'Pirates of the Caribbean', 'Parasite', "Pan's Labyrinth"],
    Q: ['Quiz Show', 'Quantum of Solace', 'Queen'],
    R: ['Rocky', 'Ratatouille', 'Raiders of the Lost Ark', 'Rear Window'],
    S: ['Star Wars', 'Shrek', 'Spider-Man', 'Saving Private Ryan', "Schindler's List", 'Spirited Away'],
    T: ['Titanic', 'Top Gun', 'Toy Story', 'The Godfather', 'The Shining', 'Tenet'],
    U: ['Up', 'Uncut Gems', 'Unbreakable'],
    V: ['V for Vendetta', 'Vertigo', 'Volver'],
    W: ['Wall-E', 'Wonder Woman', 'Wizard of Oz', 'Whiplash'],
    X: ['X-Men', 'XXX'],
    Y: ['Yesterday', 'Young Frankenstein', 'Your Name'],
    Z: ['Zootopia', 'Zodiac', 'Zorro', 'Zero Dark Thirty'],
  },

  games: {
    A: ["Assassin's Creed", 'Animal Crossing', 'Among Us', 'Apex Legends'],
    B: ['Batman Arkham', 'Borderlands', 'Bioshock', "Baldur's Gate", 'Battlefield'],
    C: ['Civilization', 'Call of Duty', 'Crash Bandicoot', 'Cuphead', 'Control'],
    D: ['Doom', 'Dark Souls', 'Donkey Kong', 'Dragon Age', 'Dead Space'],
    E: ['Elder Scrolls', 'Earthworm Jim', 'Elden Ring', 'Everquest', 'Earthbound'],
    F: ['Final Fantasy', 'Fortnite', 'Fallout', 'Fez', 'Far Cry'],
    G: ['God of War', 'Grand Theft Auto', 'Gears of War', 'Ghost of Tsushima'],
    H: ['Halo', 'Half-Life', 'Hollow Knight', 'Hogwarts Legacy', 'Horizon'],
    I: ['Ico', 'Into the Breach', 'Injustice', 'Inside'],
    J: ['Journey', 'Just Dance', 'Jet Set Radio'],
    K: ['Kirby', 'Kingdom Hearts', 'Katamari Damacy'],
    L: ['Legend of Zelda', 'Left 4 Dead', 'Little Big Planet', "Luigi's Mansion"],
    M: ['Minecraft', 'Mario', 'Metal Gear Solid', 'Mass Effect', 'Monster Hunter'],
    N: ['Need for Speed', 'Ninja Gaiden', 'NieR Automata'],
    O: ['Overwatch', 'Ori and the Blind Forest', 'Outer Wilds', 'Octopath Traveler'],
    P: ['Pokemon', 'Portal', 'Pac-Man', 'Persona', 'Prince of Persia'],
    Q: ['Q*bert', 'Quest for Glory', 'Quake'],
    R: ['Red Dead Redemption', 'Ratchet and Clank', 'Resident Evil'],
    S: ['Starcraft', 'Skyrim', 'Sonic', 'Spyro', 'Splatoon', 'Sekiro'],
    T: ['Tetris', 'The Last of Us', 'Tomb Raider', 'Terraria'],
    U: ['Undertale', 'Uncharted', 'Unreal Tournament'],
    V: ['Valorant', 'Valheim', 'Vampire Survivors'],
    W: ['World of Warcraft', 'Witcher', 'Wolfenstein', 'Watch Dogs'],
    X: ['XCOM', 'Xenogears', 'Xenoblade Chronicles'],
    Y: ["Yoshi's Island", 'Yakuza', "Yoku's Island Express"],
    Z: ['Zelda', 'Zork', 'Zero Escape'],
  },

  tvshows: {
    A: ['Avatar', 'Arrow', 'Arrested Development', 'Alias', 'Andor', 'Abbott Elementary', 'Atlanta'],
    B: ['Breaking Bad', 'Better Call Saul', 'Black Mirror', 'Band of Brothers', 'Bloodline', 'Buffy the Vampire Slayer', 'Brooklyn Nine-Nine'],
    C: ['Castle', 'Cheers', 'Community', 'Criminal Minds', 'Chernobyl', 'Curb Your Enthusiasm'],
    D: ['Dexter', 'Downton Abbey', 'Dark', 'Doctor Who', 'Daredevil', 'Desperate Housewives'],
    E: ['Elementary', 'Euphoria', 'ER', 'Entourage'],
    F: ['Friends', 'Fargo', 'Firefly', 'Family Guy', 'Fleabag', 'Full House'],
    G: ['Game of Thrones', "Grey's Anatomy", 'Glee', 'Gravity Falls', 'Gilmore Girls'],
    H: ['House', 'Homeland', 'Heroes', 'Halt and Catch Fire', 'House of Cards', 'How I Met Your Mother'],
    I: ["It's Always Sunny", 'Invincible', 'Insecure'],
    J: ['Justified', 'Jane the Virgin', 'Jeopardy'],
    K: ['Killing Eve', 'Kingdom', 'King of Queens'],
    L: ['Lost', 'Loki', 'Line of Duty', 'Lucifer'],
    M: ['Mad Men', 'Mindhunter', 'Modern Family', 'Mandalorian', 'Mr. Robot'],
    N: ['Narcos', 'NCIS', 'New Girl'],
    O: ['Orange is the New Black', 'Outer Banks', 'One Tree Hill', 'Our Planet'],
    P: ['Parks and Recreation', 'Prison Break', 'Peaky Blinders', 'Pose'],
    Q: ['Quantum Leap', "Queen's Gambit"],
    R: ['Rick and Morty', 'Rings of Power', 'Raised by Wolves'],
    S: ['Succession', 'Stranger Things', 'Seinfeld', 'Squid Game', 'Sherlock', 'Scrubs', 'Survivor'],
    T: ['The Wire', 'The Sopranos', 'Ted Lasso', 'Twin Peaks', 'The Office'],
    U: ['Umbrella Academy', 'Unsolved Mysteries', 'Ugly Betty'],
    V: ['Vikings', 'Veep', 'Vampire Diaries'],
    W: ['Walking Dead', 'Westworld', 'West Wing', 'White Lotus', 'Wentworth', 'Will and Grace'],
    X: ['X-Files', 'Xena Warrior Princess'],
    Y: ['Young Sheldon', 'You', 'Yellowstone'],
    Z: ['Zoo', 'Zombies'],
  },

  superheroes: {
    A: ['Aquaman', 'Ant-Man', 'Atom', 'Arrowette', 'Atom Eve'],
    B: ['Batman', 'Black Panther', 'Black Widow', 'Batgirl', 'Booster Gold', 'Blue Beetle'],
    C: ['Captain America', 'Cyclops', 'Captain Marvel', 'Catwoman', 'Colossus'],
    D: ['Deadpool', 'Daredevil', 'Doctor Strange', 'Domino', 'Drax'],
    E: ['Elastigirl', 'Elektra'],
    F: ['Flash', 'Falcon', 'Firestar', 'Firestorm'],
    G: ['Green Lantern', 'Green Arrow', 'Groot', 'Ghost Rider', 'Gambit'],
    H: ['Hulk', 'Hawkeye', 'Hawkman', 'Hit-Girl'],
    I: ['Iron Man', 'Invisible Woman', 'Iceman'],
    J: ['Jessica Jones', 'Jubilee'],
    K: ['Kick-Ass', 'Kilowog'],
    L: ['Luke Cage', 'Lightning Lad'],
    M: ['Ms. Marvel', 'Martian Manhunter', 'Moon Knight', 'Mystique'],
    N: ['Nightwing', 'Namor', 'Nick Fury', 'Nova', 'Nightcrawler'],
    O: ['Oracle'],
    P: ['Professor X', 'Power Girl', 'Photon', 'Psylocke'],
    Q: ['Quicksilver', 'Question'],
    R: ['Robin', 'Rocket Raccoon', 'Red Hood', 'Rogue'],
    S: ['Superman', 'Spider-Man', 'Storm', 'She-Hulk', 'Shazam', 'Scarlet Witch', 'Star-Lord'],
    T: ['Thor', 'The Tick', 'Toxin'],
    U: ['Ultra Boy', 'Union Jack'],
    V: ['Vision', 'Venom', 'Valkyrie'],
    W: ['Wonder Woman', 'Wolverine', 'Wasp', 'War Machine', 'White Tiger'],
    X: ['X-23', 'Xavier'],
    Y: ['Yellowjacket'],
    Z: ['Zatanna', 'Zorro', 'Zoom'],
  },

  mythology: {
    A: ['Apollo', 'Aphrodite', 'Athena', 'Ares', 'Anubis', 'Atlas', 'Aurora', 'Artemis'],
    B: ['Bacchus', 'Bes', 'Brahma', 'Brigid', 'Baldr'],
    C: ['Cronus', 'Cupid', 'Cernunnos', 'Circe'],
    D: ['Dionysus', 'Demeter', 'Danu', 'Durga'],
    E: ['Eros', 'Eris', 'Epona'],
    F: ['Freya', 'Frigg', 'Forseti'],
    G: ['Gaia', 'Ganesh'],
    H: ['Hades', 'Hermes', 'Hera', 'Horus', 'Hecate', 'Hanuman'],
    I: ['Iris', 'Isis', 'Indra', 'Inanna'],
    J: ['Jupiter', 'Janus', 'Juno'],
    K: ['Khepri', 'Krishna', 'Kali', 'Kanaloa'],
    L: ['Loki', 'Luna'],
    M: ['Mars', 'Mercury', 'Minerva', 'Morpheus', 'Morrigan'],
    N: ['Neptune', 'Nike', 'Nephthys', 'Nut', 'Nyx'],
    O: ['Odin', 'Osiris'],
    P: ['Poseidon', 'Persephone', 'Pan', 'Prometheus', 'Parvati'],
    Q: ['Quetzalcoatl'],
    R: ['Ra', 'Rhea', 'Radha'],
    S: ['Saturn', 'Shiva', 'Selene', 'Sobek', 'Set', 'Skadi'],
    T: ['Thor', 'Triton', 'Tyr', 'Thoth', 'Tethys'],
    U: ['Uranus', 'Ukko'],
    V: ['Vishnu', 'Venus', 'Vulcan'],
    W: ['Wadjet', 'Wepwawet', 'Wotan'],
    X: ['Xipe Totec', 'Xochiquetzal'],
    Y: ['Ymir', 'Yama'],
    Z: ['Zeus', 'Zephyrus', 'Zhong Kui'],
  },

  history: {
    A: ['Alexander the Great', 'Aristotle', 'Amelia Earhart', 'Archimedes', 'Augustus'],
    B: ['Boudicca', 'Beethoven', 'Bolivar', 'Bismarck'],
    C: ['Cleopatra', 'Churchill', 'Confucius', 'Columbus', 'Copernicus', 'Catherine the Great'],
    D: ['Darwin', 'Descartes', 'Diocletian'],
    E: ['Einstein', 'Elizabeth I', 'Euclid'],
    F: ['Franklin', 'Frederick the Great', 'Florence Nightingale'],
    G: ['Galileo', 'Gandhi', 'Genghis Khan', 'Gutenberg'],
    H: ['Hannibal', 'Harriet Tubman', 'Hippocrates', 'Hadrian'],
    I: ['Ivan the Terrible', 'Isabella of Castile'],
    J: ['Joan of Arc', 'Julius Caesar', 'Jefferson'],
    K: ['Kepler', 'Kublai Khan', 'Kamehameha'],
    L: ['Lincoln', 'Leonardo da Vinci', 'Louis XIV', 'Lenin', 'Lao Tzu'],
    M: ['Marie Curie', 'Magellan', 'Marco Polo', 'Michelangelo', 'Mozart', 'Martin Luther King'],
    N: ['Newton', 'Napoleon', 'Nelson', 'Nero'],
    O: ['Obama', 'Oliver Cromwell', 'Octavian'],
    P: ['Plato', 'Pocahontas', 'Pythagoras', 'Pericles', 'Pasteur'],
    Q: ['Qin Shi Huang'],
    R: ['Roosevelt', 'Rembrandt', 'Richard the Lionheart', 'Rasputin', 'Rosa Parks'],
    S: ['Shakespeare', 'Socrates', 'Sun Tzu', 'Suleiman', 'Spartacus'],
    T: ['Tesla', 'Tutankhamun', 'Thomas Edison'],
    U: ['Ulysses S. Grant'],
    V: ['Voltaire', 'Victoria', 'Vasco da Gama'],
    W: ['Washington', 'Wellington', 'William the Conqueror'],
    X: ['Xerxes'],
    Y: ['Yuri Gagarin'],
    Z: ['Zheng He', 'Zhukov'],
  },

  dances: {
    A: ['Argentine Tango', 'Afrobeat', 'Aerobics Dance', 'Apsara Dance'],
    B: ['Ballet', 'Bachata', 'Bhangra', 'Ballroom', 'Breakdance', 'B-boying', 'Belly Dance', 'Bossa Nova'],
    C: ['Cha-Cha', 'Charleston', 'Country Line Dance', 'Capoeira', 'Conga', 'Cumbia'],
    D: ['Disco', 'Danzon', 'Dougie'],
    E: ['Electric Slide', 'English Country Dance'],
    F: ['Foxtrot', 'Flamenco', 'Fandango'],
    G: ['Garba', 'Gumboot Dance', 'Go-Go'],
    H: ['Hip Hop', 'Highland Fling', 'Haka', 'Hora', 'Hustle'],
    I: ['Irish Step Dancing', 'Irish Step'],
    J: ['Jive', 'Jazz Dance', 'Jig'],
    K: ['Kathak', 'Krump', 'Kizomba'],
    L: ['Lindy Hop', 'Latin Dance', 'Lambada', 'Locking'],
    M: ['Mambo', 'Merengue', 'Moonwalk', 'Macarena', 'Mazurka'],
    N: ['Northern Soul', 'Noh Dance'],
    O: ['One-Step', 'One Step'],
    P: ['Polka', 'Paso Doble', 'Popping'],
    Q: ['Quickstep', 'Quadrille'],
    R: ['Rumba', 'Robot Dance', 'Reggaeton', 'Running Man'],
    S: ['Salsa', 'Samba', 'Swing', 'Shuffle', 'Soca'],
    T: ['Tango', 'Twist', 'Tap Dance', 'Tinikling', 'Tutting'],
    U: ['Urban Dance'],
    V: ['Viennese Waltz', 'Voguing'],
    W: ['Waltz', 'Waacking', 'West Coast Swing'],
    X: ['Xaxado', 'Xote'],
    Y: ['Yangko', 'Yosakoi'],
    Z: ['Zapateado', 'Zydeco'],
  },

  countries: {
    A: ['Argentina', 'Australia', 'Austria', 'Afghanistan', 'Albania', 'Algeria', 'Angola'],
    B: ['Brazil', 'Belgium', 'Bolivia', 'Bangladesh', 'Bahamas', 'Bhutan', 'Belize', 'Botswana', 'Bulgaria', 'Bahrain'],
    C: ['Canada', 'China', 'Colombia', 'Chile', 'Cuba', 'Croatia', 'Costa Rica', 'Cameroon', 'Cambodia', 'Cyprus'],
    D: ['Denmark', 'Dominican Republic', 'Djibouti'],
    E: ['Egypt', 'Ecuador', 'Estonia', 'Ethiopia', 'El Salvador', 'Eritrea'],
    F: ['France', 'Finland', 'Fiji'],
    G: ['Germany', 'Greece', 'Ghana', 'Guatemala', 'Gambia', 'Guinea', 'Guyana', 'Georgia'],
    H: ['Honduras', 'Hungary', 'Haiti'],
    I: ['India', 'Indonesia', 'Ireland', 'Iran', 'Iraq', 'Italy', 'Iceland', 'Israel'],
    J: ['Japan', 'Jamaica', 'Jordan'],
    K: ['Kenya', 'Kazakhstan', 'Kuwait', 'Kyrgyzstan', 'Kiribati', 'Korea'],
    L: ['Libya', 'Lebanon', 'Laos', 'Lithuania', 'Latvia', 'Liberia', 'Luxembourg', 'Lesotho'],
    M: ['Mexico', 'Morocco', 'Malaysia', 'Mongolia', 'Madagascar', 'Malta', 'Mozambique', 'Myanmar'],
    N: ['Nigeria', 'Nepal', 'Netherlands', 'Norway', 'New Zealand', 'Nicaragua', 'Namibia', 'Niger', 'North Korea'],
    O: ['Oman'],
    P: ['Peru', 'Poland', 'Portugal', 'Pakistan', 'Panama', 'Philippines', 'Paraguay', 'Papua New Guinea'],
    Q: ['Qatar'],
    R: ['Romania', 'Russia', 'Rwanda'],
    S: ['Spain', 'Sweden', 'Switzerland', 'South Africa', 'Singapore', 'Sri Lanka', 'Serbia', 'Somalia', 'Sudan', 'Samoa'],
    T: ['Thailand', 'Turkey', 'Tunisia', 'Tanzania', 'Togo', 'Tonga', 'Tajikistan', 'Turkmenistan'],
    U: ['Uruguay', 'Uganda', 'Ukraine', 'Uzbekistan', 'United Arab Emirates', 'United Kingdom', 'United States'],
    V: ['Venezuela', 'Vietnam', 'Vanuatu'],
    W: ['Wales'],
    Y: ['Yemen'],
    Z: ['Zimbabwe', 'Zambia'],
  },

  baseball: {
    A: ['Aaron Judge', 'Albert Pujols', 'Alex Rodriguez', 'Andre Dawson'],
    B: ['Babe Ruth', 'Barry Bonds', 'Bob Gibson', 'Brooks Robinson', 'Bryce Harper'],
    C: ['Cal Ripken Jr', 'Cy Young', 'Clayton Kershaw', 'Craig Biggio', 'Chipper Jones'],
    D: ['Derek Jeter', 'David Ortiz', 'Don Drysdale', 'Duke Snider'],
    E: ['Ernie Banks', 'Eddie Murray', 'Eddie Collins'],
    F: ['Frank Robinson', 'Fergie Jenkins', 'Fred McGriff'],
    G: ['Greg Maddux', 'George Brett', 'Gerrit Cole'],
    H: ['Hank Aaron', 'Honus Wagner', 'Harmon Killebrew'],
    I: ['Ichiro Suzuki', 'Ivan Rodriguez'],
    J: ['Jackie Robinson', 'Joe DiMaggio', 'Jim Palmer', 'Johnny Bench'],
    K: ['Ken Griffey Jr', 'Kirby Puckett'],
    L: ['Lou Gehrig', 'Larry Doby', 'Lefty Grove'],
    M: ['Mickey Mantle', 'Mike Trout', 'Mariano Rivera', 'Mookie Betts'],
    N: ['Nolan Ryan', 'Nelson Cruz'],
    O: ['Ozzie Smith', 'Orlando Cepeda', 'Orel Hershiser'],
    P: ['Pete Rose', 'Pedro Martinez', 'Prince Fielder'],
    Q: ['Quinn Priester'],
    R: ['Roberto Clemente', 'Randy Johnson', 'Roger Clemens', 'Rickey Henderson'],
    S: ['Sandy Koufax', 'Stan Musial', 'Satchel Paige', 'Shohei Ohtani', 'Sammy Sosa'],
    T: ['Ted Williams', 'Tom Seaver', 'Tony Gwynn', 'Tris Speaker'],
    U: ['Ugueth Urbina'],
    V: ['Vida Blue', 'Vernon Wells', 'Vladimir Guerrero'],
    W: ['Willie Mays', 'Walter Johnson', 'Warren Spahn', 'Willie McCovey'],
    X: ['Xander Bogaerts'],
    Y: ['Yogi Berra', 'Yasiel Puig', 'Yu Darvish'],
    Z: ['Zack Greinke', 'Zack Wheeler'],
  },

  football: {
    A: ['Aaron Rodgers', 'Adrian Peterson', 'Aaron Donald'],
    B: ['Barry Sanders', 'Brett Favre', 'Brian Urlacher', 'Bo Jackson'],
    C: ['Calvin Johnson', 'Cam Newton', 'Cris Carter'],
    D: ['Dan Marino', 'Deion Sanders', 'Drew Brees', 'Dick Butkus'],
    E: ['Emmitt Smith', 'Eli Manning', 'Earl Campbell', 'Eric Dickerson'],
    F: ['Fran Tarkenton', 'Franco Harris', 'Frank Gore'],
    G: ['Gale Sayers', 'George Kittle'],
    H: ['Herschel Walker', 'Hines Ward'],
    I: ['Isaac Bruce'],
    J: ['Jerry Rice', 'Jim Brown', 'Joe Montana', 'John Elway', 'Joe Namath'],
    K: ['Kurt Warner', 'Kam Chancellor', 'Khalil Mack'],
    L: ['Lawrence Taylor', 'LaDainian Tomlinson', 'Lamar Jackson', 'Luke Kuechly'],
    M: ['Michael Vick', 'Marshawn Lynch', 'Marcus Allen', 'Michael Strahan', 'Mike Ditka'],
    N: ['Ndamukong Suh', 'Nick Foles', 'Nick Chubb'],
    O: ['OJ Simpson', 'Orlando Pace', 'Odell Beckham Jr'],
    P: ['Peyton Manning', 'Patrick Mahomes', 'Patrick Willis'],
    Q: ['Quenton Nelson', 'Quinton Williams'],
    R: ['Randy Moss', 'Ray Lewis', 'Russell Wilson', 'Reggie White'],
    S: ['Steve Young', 'Saquon Barkley', 'Shannon Sharpe', 'Sean Taylor'],
    T: ['Tom Brady', 'Terrell Owens', 'Troy Aikman', 'Troy Polamalu'],
    U: ['Unitas', 'Udo Latimer'],
    V: ['Von Miller', 'Vince Young', 'Vince Wilfork'],
    W: ['Walter Payton', 'Warren Moon', 'Wes Welker'],
    X: ['Xavier Rhodes', 'Xavier McKinney'],
    Y: ['Y.A. Tittle', 'Yancey Thigpen'],
    Z: ['Zach Thomas'],
  },

  basketball: {
    A: ['Allen Iverson', 'Anthony Davis', 'Alonzo Mourning'],
    B: ['Bill Russell', 'Bob Cousy', 'Ben Wallace', 'Bob Pettit'],
    C: ['Carmelo Anthony', 'Charles Barkley', 'Chris Paul', 'Clyde Drexler'],
    D: ['Dwyane Wade', 'Dennis Rodman', 'Dikembe Mutombo', 'Dirk Nowitzki', 'David Robinson'],
    E: ['Elgin Baylor', 'Earl Monroe', 'Elvin Hayes'],
    F: ['Fred VanVleet', 'Fat Lever'],
    G: ['Giannis Antetokounmpo', 'George Mikan', 'Grant Hill'],
    H: ['Hakeem Olajuwon', 'Horace Grant'],
    I: ['Isiah Thomas'],
    J: ['Julius Erving', 'Jason Kidd', 'Jerry West', 'James Harden', 'Jayson Tatum'],
    K: ['Kobe Bryant', 'Kevin Durant', 'Kevin Garnett', 'Karl Malone', 'Kawhi Leonard', 'Kareem Abdul-Jabbar'],
    L: ['LeBron James', 'Larry Bird', 'Luka Doncic', 'Lenny Wilkens'],
    M: ['Michael Jordan', 'Magic Johnson', 'Moses Malone'],
    N: ['Nikola Jokic', 'Nate Archibald', 'Nate Robinson'],
    O: ['Oscar Robertson'],
    P: ['Patrick Ewing', 'Paul Pierce', 'Penny Hardaway'],
    Q: ['Quentin Richardson'],
    R: ['Russell Westbrook', 'Ray Allen', 'Reggie Miller'],
    S: ['Stephen Curry', 'Shaquille O\'Neal', 'Scottie Pippen', 'Steve Nash'],
    T: ['Tim Duncan', 'Tracy McGrady', 'Trae Young'],
    U: ['Udonis Haslem'],
    V: ['Vince Carter'],
    W: ['Wilt Chamberlain', 'Walt Frazier', 'Willis Reed'],
    X: ['Xavier McDaniel'],
    Y: ['Yao Ming'],
    Z: ['Zion Williamson', 'Zach Randolph'],
  },
};
